# -*- coding: utf-8 -*-
"""
Redakcja pilota 18 kart wg EduMost Standard v1.0 (zatwierdzony 2026-07-30).
Klucz: (source_n, hasło) — przed structure_apply.
"""

# (nr źródłowy strony, hasło) → pola karty
EDITORIAL_V1 = {
    (61, "prawo / lewo"): {
        "def_pl": "Prawa i lewa strona — jak prawa i lewa ręka. Na rysunku patrzymy od strony postaci.",
        "def_ua": "Права і ліва сторона — як права і ліва рука. На малюнку дивимось з боку персонажа.",
        "visual": "👉 prawo · 👈 lewo",
        "rule": "👉 prawo · 👈 lewo",
        "rule_ua": "👉 право · 👈 ліво",
    },
    (61, "góra / dół"): {
        "ua": "вгорі / внизу",
        "def_pl": "Góra — wyżej (sufit, półka). Dół — niżej (podłoga).",
        "def_ua": "Вгорі — вище. Внизу — нижче.",
        "visual": "↑ góra · ↓ dół",
        "rule": "↑ góra · ↓ dół",
        "rule_ua": "↑ вгорі · ↓ внизу",
        "nie_pomyl": [],
    },
    # cyfra — bez zmian definicji (nie zmieniać dobrego)
    (1, "liczba naturalna"): {
        # definicje OK; Nie pomyl w card_ux
    },
    (4, "suma"): {
        "visual": "składnik + składnik = suma",
        "rule": "składnik + składnik = suma",
        "rule_ua": "У 2+6=8 число 8 — саме сума.",
        "def_pl": "Suma to wynik dodawania — liczba, którą dostajesz po znaku =. Odpowiada: ile razem?",
        "def_ua": "Сума — результат додавання — число після знака =. Відповідає: скільки разом?",
    },
    (6, "z resztą"): {
        "def_pl": "Czasem nie da się podzielić po równo — zostaje reszta.",
        "def_ua": "Іноді не можна поділити порівну — лишається остача.",
        "visual": "17 : 5 = 3 r. 2",
        "rule": "17 : 5 = 3 r. 2 · reszta < dzielnik",
        "rule_ua": "17:5 = 3 остачі 2. Остача завжди менша за дільник.",
    },
    (9, "ułamek zwykły"): {
        "visual": "a/b · np. 3/4",
        "rule": "a/b · np. 3/4",
        "rule_ua": "3/4 — три з чотирьох рівних частин.",
        "def_pl": "Ułamek zwykły pokazuje część całości: licznik nad kreską, mianownik pod kreską.",
        "def_ua": "Звичайний дріб показує частину цілого: чисельник над рискою, знаменник під рискою.",
    },
    (9, "licznik"): {
        "def_pl": "Licznik to liczba nad kreską ułamka — mówi, ile równych części bierzesz.",
        "def_ua": "Чисельник — число над рискою дробу — каже, скільки рівних частин береш.",
        "visual": "3/4 → 3",
        "rule": "W ułamku 3/4 licznik to 3: bierzemy trzy części z czterech.",
        "rule_ua": "У дробі 3/4 чисельник — 3: беремо три частини з чотирьох.",
    },
    (9, "mianownik"): {
        "def_pl": "Mianownik (pod kreską) mówi, na ile równych części podzielono całość.",
        "def_ua": "Знаменник (під рискою) каже, на скільки рівних частин поділено ціле.",
        "visual": "3/4 → 4",
        "rule": "W 3/4 mianownik to 4. Mianownik nigdy nie może być 0.",
        "rule_ua": "У 3/4 знаменник — 4. Знаменник ніколи не може бути 0.",
    },
    (15, "procent"): {
        "def_pl": "Procent to setna część całości — wygodny sposób mówienia o częściach (jak „ze stu”).",
        "def_ua": "Відсоток — сота частина цілого — зручний спосіб говорити про частини («зі ста»).",
        "visual": "1% = 1/100 = 0,01",
        "rule": "1% = 1/100 = 0,01. 100% to zawsze całość.",
        "rule_ua": "1% = 1/100 = 0,01. 100% — завжди ціле.",
    },
    (19, "równanie"): {
        "def_pl": "Równanie to równość z niewiadomą — waga, która ma być zrównoważona.",
        "def_ua": "Рівняння — рівність із невідомим — терези, які мають бути в рівновазі.",
        "visual": "x + 5 = 12",
        "rule": "x + 5 = 12. Szukamy takiej liczby x, by obie strony były równe.",
        "rule_ua": "x + 5 = 12. Шукаємо таке число x, щоб обидва боки були рівні.",
    },
    (19, "niewiadoma"): {
        "def_pl": "Niewiadoma to liczba, którą mamy znaleźć — zwykle oznaczana x lub y.",
        "def_ua": "Невідоме — число, яке треба знайти — зазвичай позначається x або y.",
        "visual": "x, y…",
        "rule": "Szukamy liczby na miejscu x.",
        "rule_ua": "Шукаємо число на місці x.",
    },
    (30, "okrąg"): {
        "def_pl": "Okrąg to sama linia — brzeg, bez wnętrza. Jak obwódka talerza.",
        "def_ua": "Коло — лише лінія (край), без середини. Як край тарілки.",
        "visual": "linia w odległości r od środka",
        "rule": "linia w odległości r od środka",
        "rule_ua": "Коло = край; круг = край + всередині.",
    },
    (30, "koło"): {
        "def_pl": "Koło to okrąg razem z wnętrzem — jak cały talerz.",
        "def_ua": "Круг — лінія і все всередині — як ціла тарілка.",
        "visual": "okrąg + wnętrze",
        "rule": "okrąg + wnętrze",
        "rule_ua": "Круг = лінія + всередині; коло = лише лінія.",
    },
    (57, "twierdzenie Pitagorasa"): {
        "def_pl": "W trójkącie prostokątnym: suma kwadratów przyprostokątnych = kwadrat przeciwprostokątnej.",
        "def_ua": "У прямокутному трикутнику: сума квадратів катетів = квадрат гіпотенузи.",
        "visual": "a² + b² = c²",
        "rule": "a² + b² = c²",
        "rule_ua": "c — бік навпроти 90°. a і b — катети.",
    },
    (62, "walec"): {
        "def_pl": "Walec wygląda jak puszka: dwie okrągłe podstawy i bok.",
        "def_ua": "Циліндр схожий на банку: дві круглі основи і бік.",
        "visual": "V = πr²·h",
        "rule": "V = πr²·h · h — wysokość",
        "rule_ua": "Об’єм: πr²h. h — висота.",
    },
    (66, "nierówność"): {
        "def_pl": "Nierówność porównuje strony (nie znakiem =). Znaki: mniejszy, większy, ≤, ≥.",
        "def_ua": "Нерівність порівнює сторони (не знаком =). Знаки: менше, більше, ≤, ≥.",
        "visual": "x > 3",
        "rule": "x > 3",
        "rule_ua": "x > 3 — числа більші за 3.",
    },
    (72, "liczba wymierna"): {
        "def_pl": "Liczba, którą da się zapisać jako iloraz dwóch liczb całkowitych (mianownik ≠ 0).",
        "def_ua": "Число, яке можна записати як частку двох цілих (знаменник ≠ 0).",
        "visual": "a/b, b ≠ 0",
        "rule": "a/b, gdzie b ≠ 0",
        "rule_ua": "a/b, де b ≠ 0.",
    },
}

# usuń puste wpisy

# ——— kontynuacja redakcji tekstu (po pilocie 18) ———
EDITORIAL_V1.update({
    (31, "pole koła"): {
        "def_pl": "Pole koła to miara powierzchni „tarczy” — ile miejsca zajmuje wnętrze.",
        "def_ua": "Площа круга — міра поверхні «диска»: скільки місця всередині.",
        "visual": "P = πr²",
        "rule": "P = π·r²",
        "rule_ua": "P = π·r² — спочатку r², потім × π.",
    },
    (62, "podstawa walca"): {
        "def_pl": "Podstawy walca to dwa równe koła — góra i dół.",
        "def_ua": "Основи циліндра — два рівні круги: верх і низ.",
        "visual": "2 koła",
        "rule": "2 równe koła",
        "rule_ua": "2 рівні круги",
        "nie_pomyl": [],
    },
    (62, "wysokość walca"): {
        "def_pl": "Wysokość walca to odległość między podstawami (prostopadle).",
        "def_ua": "Висота циліндра — відстань між основами (перпендикулярно).",
        "visual": "h",
        "rule": "h — między podstawami",
        "rule_ua": "h — між основами",
        "nie_pomyl": [],
    },
    (62, "w życiu"): {
        "def_pl": "Puszki, rury, rolki papieru — często mają kształt walca.",
        "def_ua": "Банки, труби, рулони паперу — часто мають форму циліндра.",
        "visual": "puszka napoju",
        "rule": "puszka ≈ walec",
        "rule_ua": "банка ≈ циліндр",
        "nie_pomyl": [],
    },
    (63, "stożek"): {
        "def_pl": "Stożek wygląda jak rożek lodów: okrągła podstawa i wierzchołek.",
        "def_ua": "Конус схожий на ріжок морозива: кругла основа і вершина.",
        "visual": "rożek, czapka",
        "rule": "1 koło + wierzchołek",
        "rule_ua": "1 круг + вершина",
    },
    (63, "podstawa stożka"): {
        "def_pl": "Podstawa stożka to koło — spód bryły.",
        "def_ua": "Основа конуса — круг (низ тіла).",
        "visual": "koło",
        "rule": "podstawa = koło",
        "rule_ua": "основа = круг",
        "nie_pomyl": [],
    },
    (63, "wierzchołek stożka"): {
        "def_pl": "Wierzchołek stożka to punkt, w którym zbiegają się tworzące.",
        "def_ua": "Вершина конуса — точка, в якій сходяться твірні.",
        "visual": "punkt S",
        "rule": "punkt S na górze",
        "rule_ua": "точка S зверху",
        "nie_pomyl": [],
    },
    (63, "w życiu"): {
        "def_pl": "Rożek lodów, lejek, czapka — kształt stożka.",
        "def_ua": "Ріжок морозива, лійка, ковпак — форма конуса.",
        "visual": "rożek, lejek",
        "rule": "rożek ≈ stożek",
        "rule_ua": "ріжок ≈ конус",
        "nie_pomyl": [],
    },
    (64, "kula"): {
        "def_pl": "Kula to pełna „piłka” — wszystkie punkty wewnątrz i na powierzchni w odległości ≤ r od środka.",
        "def_ua": "Куля — повний «м'яч»: усі точки всередині й на поверхні на відстані ≤ r від центра.",
        "visual": "piłka",
        "rule": "kula = pełna bryła",
        "rule_ua": "куля = повне тіло",
    },
    (64, "sfera"): {
        "def_pl": "Sfera to tylko powierzchnia kuli — jak skórka piłki, bez środka.",
        "def_ua": "Сфера — лише поверхня кулі: як шкірка м'яча, без середини.",
        "visual": "powierzchnia piłki",
        "rule": "sfera = powierzchnia",
        "rule_ua": "сфера = поверхня",
    },
    (64, "środek i promień"): {
        "def_pl": "Środek i promień kuli/sfery — jak w kole: O i odległość r.",
        "def_ua": "Центр і радіус кулі/сфери — як у крузі: O і відстань r.",
        "visual": "O, r",
        "rule": "O — środek · r — promień",
        "rule_ua": "O — центр · r — радіус",
        "nie_pomyl": [],
    },
    (64, "w życiu"): {
        "def_pl": "Piłka, globus, pomarańcza — kształt zbliżony do kuli.",
        "def_ua": "М'яч, глобус, апельсин — форма близька до кулі.",
        "visual": "piłka, globus",
        "rule": "piłka ≈ kula",
        "rule_ua": "м'яч ≈ куля",
        "nie_pomyl": [],
    },
    (65, "ostrosłup"): {
        "def_pl": "Ostrosłup ma wielokątną podstawę i ściany zbiegające się w wierzchołku.",
        "def_ua": "Піраміда має многокутну основу і грані, що сходяться у вершині.",
        "visual": "podstawa + wierzchołek",
        "rule": "V = ⅓·P_podst·H",
        "rule_ua": "V = ⅓·P_осн·H",
    },
    (66, "rozwiązanie nierówności"): {
        "def_pl": "Rozwiązanie nierówności to wszystkie liczby, które spełniają warunek (często przedział).",
        "def_ua": "Розв'язок нерівності — усі числа, що задовольняють умову (часто проміжок).",
        "visual": "x > 3 → (3; ∞)",
        "rule": "zbiór rozwiązań",
        "rule_ua": "множина розв'язків",
    },
    (66, "znaki"): {
        "def_pl": "Znaki nierówności: mniejszy, większy oraz ≤ i ≥.",
        "def_ua": "Знаки нерівності: менше, більше, а також ≤ і ≥.",
        "visual": "mniejszy · większy · ≤ · ≥",
        "rule": "mniejszy · większy · ≤ · ≥",
        "rule_ua": "менше · більше · ≤ · ≥",
        "nie_pomyl": [],
    },
    (66, "na osi"): {
        "def_pl": "Rozwiązanie nierówności zaznaczamy na osi: często półprosta (promień).",
        "def_ua": "Розв'язок нерівності позначаємо на прямій: часто півпряма (промінь).",
        "visual": "○——→",
        "rule": "zaznacz na osi",
        "rule_ua": "познач на прямій",
        "nie_pomyl": [],
    },
    (66, "a równanie?"): {
        "def_pl": "Równanie ma znak = i zwykle jedno rozwiązanie. Nierówność — zakres.",
        "def_ua": "Рівняння має знак = і зазвичай один розв'язок. Нерівність — діапазон.",
        "visual": "x=3 ≠ x>3",
        "rule": "równanie (=) · nierówność (< >)",
        "rule_ua": "рівняння (=) · нерівність (< >)",
    },
})


EDITORIAL_V1.update({
    (59, "środek odcinka"): {
        "def_pl": "Środek odcinka to punkt w połowie drogi między końcami. Jego współrzędne to średnie współrzędnych końców.",
        "def_ua": "Середина відрізка — точка посередині між кінцями. Її координати — середні координат кінців.",
        "visual": "M = ((x₁+x₂)/2, (y₁+y₂)/2)",
        "rule": "M = średnia końców",
        "rule_ua": "M = середнє кінців",
    },
    (69, "skala podobieństwa"): {
        "def_pl": "Skala podobieństwa to stosunek długości odpowiadających sobie boków figur podobnych.",
        "def_ua": "Масштаб подібності — відношення довжин відповідних сторін подібних фігур.",
        "visual": "k = a'/a",
        "rule": "k = bok'/bok",
        "rule_ua": "k = сторона'/сторона",
    },
    (74, "zdarzenie"): {
        "def_pl": "Zdarzenie to wynik lub zbiór wyników doświadczenia losowego (to, co może się zdarzyć).",
        "def_ua": "Подія — результат або множина результатів випадкового досліду (те, що може статись).",
        "visual": "np. „wypadła 6”",
        "rule": "zdarzenie ⊂ wszystkich wyników",
        "rule_ua": "подія ⊂ усіх результатів",
    },
    (23, "przykład dłuższy"): {
        "def_pl": "Przy dłuższym czasie najpierw licz godziny, potem minuty — albo zamień wszystko na minuty.",
        "def_ua": "При довшому часі спочатку рахуй години, потім хвилини — або все переведи в хвилини.",
        "visual": "1 h 45 min",
        "rule": "najpierw godziny, potem minuty",
        "rule_ua": "спочатку години, потім хвилини",
        "nie_pomyl": [],
    },
    (67, "przykład: pole"): {
        "def_pl": "Wzór na pole też można przekształcać: z P = a·b wyliczysz np. a = P/b.",
        "def_ua": "Формулу площі теж можна перетворювати: з P = a·b виведеш напр. a = P/b.",
        "visual": "P = a·b → a = P/b",
        "rule": "a = P/b",
        "rule_ua": "a = P/b",
        "nie_pomyl": [],
    },
})


EDITORIAL_V1.update({
    (69, "w życiu"): {
        "def_pl": "Podobieństwo w życiu: mapa, model samochodu, powiększenie zdjęcia — ten sam kształt, inna skala.",
        "def_ua": "Подібність у житті: карта, модель авто, збільшення фото — та сама форма, інший масштаб.",
        "visual": "mapa · model · zdjęcie",
        "rule": "ten sam kształt, inna skala",
        "rule_ua": "та сама форма, інший масштаб",
        "nie_pomyl": [],
    },
})


EDITORIAL_V1.update({
    (5, "mnożenie"): {
        "rule": "czynnik × czynnik = iloczyn",
        "rule_ua": "множник × множник = добуток",
        "visual": "4 × 3 = 12",
    },
    (3, "wartość bezwzględna"): {
        "nie_pomyl": [("|−5| = 5", "wynik −5"), ("odległość od 0", "liczba przeciwna")],
        "rule": "|a| = odległość od 0",
        "rule_ua": "|a| = відстань від 0",
    },
    (4, "przykłady"): {
        "def_pl": "Ćwicz dodawanie i odejmowanie, potem sprawdź wynik.",
        "def_ua": "Тренуй додавання й віднімання, потім перевір результат.",
        "rule": "po odejmowaniu: sprawdź dodawaniem",
        "rule_ua": "після віднімання: перевір додаванням",
        "visual": "różnica + odjemnik = odjemna",
    },
    (7, "przykład"): {
        "def_pl": "Trudniejszy zapis liczysz warstwami: najpierw nawias, potem potęga, potem × i :, na końcu + i −.",
        "def_ua": "Складніший запис рахуй шарами: спочатку дужки, потім степінь, потім × і :, в кінці + і −.",
        "rule": "( ) → aⁿ → ×: → +−",
        "rule_ua": "( ) → aⁿ → ×: → +−",
        "visual": "( ) → aⁿ → ×: → +−",
    },
})


# --- pass2: dokończenie słownika ---
EDITORIAL_V1.update({
    (1, 'liczba naturalna'): {
        'rule': '1, 2, 3, 4… (czasem umowa obejmuje też 0)',
        'rule_ua': '1, 2, 3… (інколи домовленість включає й 0)',
    },
    (4, 'przykłady'): {
        'def_pl': 'Ćwicz dodawanie i odejmowanie, potem sprawdź wynik.',
        'def_ua': 'Тренуй додавання й віднімання, потім перевір результат.',
        'rule': 'po odejmowaniu sprawdź dodawaniem',
        'rule_ua': 'після віднімання перевір додаванням',
        'przykłady': ['3+5=8', '12−7=5', 'sprawdź: 5+7=12'],
        'nie_pomyl': [],
    },
    (4, 'właściwości −'): {
        'rule_ua': 'a−0=a та a−a=0. Увага: 9−4 ≠ 4−9 — результат змінюється.',
    },
    (5, 'mnożenie'): {
        'def_pl': 'Mnożenie to szybkie dodawanie tej samej liczby. 4×3 znaczy: 4+4+4.',
        'def_ua': 'Множення — швидке додавання того самого числа. 4×3 означає: 4+4+4.',
        'visual': '4 × 3 = 12',
        'rule': 'czynnik × czynnik = iloczyn',
        'rule_ua': 'множник × множник = добуток',
    },
    (6, ':1 i : siebie'): {
        'rule_ua': 'a:1=a; a:a=1 (коли a≠0). Запис a:0 заборонений.',
    },
    (13, '0, 1, 10'): {
        'rule_ua': 'a¹=a; a⁰=1 (a≠0); 10³=1000 (одиниця і три нулі).',
    },
    (14, 'przykłady'): {
        'def_pl': 'Najczęstsze pierwiastki warto znać na pamięć — jak tabliczkę mnożenia.',
        'def_ua': "Найчастіші корені варто знати напам'ять — як таблицю множення.",
        'rule': '√1=1 · √4=2 · √9=3 · √16=4 · √25=5',
        'rule_ua': '√1=1 · √4=2 · √9=3 · √16=4 · √25=5',
        'przykłady': ['√9 = 3', '√16 = 4', '√25 = 5'],
        'nie_pomyl': [],
    },
    (15, 'przykłady'): {
        'def_pl': 'Ćwicz „łatwe procenty”: 10%, 25%, 50% — potem resztę.',
        'def_ua': 'Тренуй «легкі відсотки»: 10%, 25%, 50% — потім решту.',
        'rule': '10% · 25% · 50% · 100%',
        'rule_ua': '10% · 25% · 50% · 100%',
        'przykłady': ['50% z 80 = 40', '10% z 200 = 20', '25% = ¼'],
        'nie_pomyl': [],
    },
    (21, 'przykłady'): {
        'def_pl': 'Ćwicz zamianę: przy kg ↔ g przecinek „skacze” o trzy miejsca.',
        'def_ua': 'Тренуй заміну: при кг ↔ г кома «стрибає» на три місця.',
        'rule': '1 kg = 1000 g',
        'rule_ua': '1 кг = 1000 г',
        'przykłady': ['2 kg = 2000 g', '3500 g = 3,5 kg', '0,25 kg = 250 g'],
        'nie_pomyl': [],
    },
    (23, 'przykład'): {
        'def_pl': 'przerwa 15 minut, lekcja zwykle 45. Policz od dzwonka do dzwonka.',
        'def_ua': 'перерва 15 хвилин, урок зазвичай 45. Порахуй від дзвінка до дзвінка.',
    },
    (30, 'promień'): {
        'nie_pomyl': [('promień r (środek → okrąg)', 'średnica d = 2r')],
        'rule': 'r — od środka do okręgu',
        'rule_ua': 'r — від центра до кола',
    },
    (34, 'wierzchołkowe'): {
        'rule_ua': 'навпроти = рівні. Не треба міряти обидва, якщо знаєш один.',
    },
    (37, 'przykłady'): {
        'def_pl': 'Symetryczne bywają figury i litery — ćwicz rozpoznawanie.',
        'def_ua': 'Симетричними бувають фігури і літери — тренуй розпізнавання.',
        'rule': 'oś / środek symetrii',
        'rule_ua': 'вісь / центр симетрії',
        'przykłady': ['litera A — oś pionowa', 'koło — wiele osi', 'litera N — bez osi pionowej'],
        'nie_pomyl': [],
    },
    (41, 'kombinatoryka'): {
        'def_pl': 'Kombinatoryka liczy, ile jest sposobów wyboru lub ułożenia (bez wypisywania wszystkich).',
        'def_ua': 'Комбінаторика рахує, скільки є способів вибору або розстановки (без переліку всіх).',
        'rule': 'ile sposobów?',
        'rule_ua': 'скільки способів?',
        'przykłady': ['3 koszulki × 4 spodnie = 12 strojów', 'kolejność ma znaczenie / nie ma', 'drzewko możliwości'],
    },
    (58, 'przystawanie'): {
        'nie_pomyl': [('przystawanie (ten sam rozmiar)', 'podobieństwo (może inna skala)')],
        'rule': '≅ — ten sam kształt i rozmiar',
        'rule_ua': '≅ — та сама форма і розмір',
    },
    (65, 'ostrosłup prawidłowy'): {
        'def_pl': 'Ostrosłup prawidłowy ma foremny wielokąt w podstawie i wierzchołek „nad środkiem”.',
        'def_ua': 'Правильна піраміда має правильний многокутник в основі і вершину «над центром».',
        'rule': 'podstawa foremna + wierzchołek nad środkiem',
        'rule_ua': 'правильна основа + вершина над центром',
        'nie_pomyl': [],
        'przykłady': ['ostrosłup prawidłowy czworokątny', 'ściany boczne = trójkąty', 'H — wysokość'],
    },
    (65, 'pole powierzchni'): {
        'def_pl': 'Pole powierzchni ostrosłupa = pole podstawy + pola ścian bocznych.',
        'def_ua': 'Площа поверхні піраміди = площа основи + площі бічних граней.',
        'rule': 'P = P_podst + P_boczne',
        'rule_ua': 'P = P_осн + P_бічн',
        'nie_pomyl': [],
        'przykłady': ['dodaj pole podstawy', 'dodaj trójkąty boczne', 'nie myl z objętością'],
    },
    (65, 'wysokość ostrosłupa'): {
        'def_pl': 'Wysokość ostrosłupa to odcinek od wierzchołka prostopadle do podstawy.',
        'def_ua': 'Висота піраміди — відрізок від вершини перпендикулярно до основи.',
        'rule': 'H ⊥ podstawa',
        'rule_ua': 'H ⊥ основа',
        'nie_pomyl': [],
        'przykłady': ['H spada na środek (gdy prawidłowy)', 'V = ⅓·P·H', 'nie myl z krawędzią boczną'],
    },
    (67, 'krok po kroku'): {
        'def_pl': 'Przekształcaj wzór krok po kroku: zapisz, co znasz, co szukasz, wykonaj działania po obu stronach.',
        'def_ua': 'Перетворюй формулу крок за кроком: запиши, що знаєш і що шукаєш, зроби дії з обох боків.',
        'rule': 'znam → szukam → przekształć',
        'rule_ua': 'знаю → шукаю → перетвори',
        'nie_pomyl': [],
        'przykłady': ['wypisz dane', 'wybierz wzór', 'przekształć i podstaw'],
    },
    (67, 'przekształcanie wzoru'): {
        'def_pl': 'Przekształcanie wzoru: te same działania po obu stronach równości, by wyliczyć potrzebną wielkość.',
        'def_ua': 'Перетворення формули: ті самі дії з обох боків рівності, щоб знайти потрібну величину.',
        'rule': 'działania po obu stronach',
        'rule_ua': 'дії з обох боків',
        'przykłady': ['z v=s/t → s=v·t', 'z P=a·b → a=P/b', 'nie zmieniaj tylko jednej strony'],
    },
    (67, 'przykład: prędkość'): {
        'def_pl': 'Ze wzoru v = s/t możesz wyliczyć drogę: s = v·t, albo czas: t = s/v.',
        'def_ua': 'З формули v = s/t можна знайти шлях: s = v·t, або час: t = s/v.',
        'rule': 'v=s/t · s=v·t · t=s/v',
        'rule_ua': 'v=s/t · s=v·t · t=s/v',
        'przykłady': ['v=50 km/h, t=2 h → s=100 km', 's=120, v=40 → t=3 h', 'sprawdź jednostkami'],
        'nie_pomyl': [],
    },
    (68, 'przykłady'): {
        'def_pl': 'Foremny 3-kąt = równoboczny; foremny 4-kąt = kwadrat.',
        'def_ua': 'Правильний 3-кутник = рівносторонній; правильний 4-кутник = квадрат.',
        'rule': 'foremny = równe boki i kąty',
        'rule_ua': 'правильний = рівні сторони і кути',
        'przykłady': ['trójkąt równoboczny', 'kwadrat', 'sześciokąt foremny'],
        'nie_pomyl': [],
    },
    (68, 'wielokąt foremny'): {
        'def_pl': 'Wielokąt foremny ma wszystkie boki równe i wszystkie kąty równe.',
        'def_ua': 'Правильний многокутник має всі сторони рівні і всі кути рівні.',
        'rule': 'równe boki + równe kąty',
        'rule_ua': 'рівні сторони + рівні кути',
        'przykłady': ['trójkąt równoboczny', 'kwadrat', 'sześciokąt foremny'],
    },
    (68, 'środek'): {
        'def_pl': 'Środek wielokąta foremnego — punkt jednakowo odległy od wierzchołków (środek okręgu opisanego).',
        'def_ua': 'Центр правильного многокутника — точка на однаковій відстані від вершин (центр описаного кола).',
        'rule': 'środek = środek okręgu opisanego',
        'rule_ua': 'центр = центр описаного кола',
        'nie_pomyl': [],
        'przykłady': ['środek kwadratu', 'środek sześciokąta', 'promień do wierzchołka'],
    },
    (69, 'a przystawanie?'): {
        'def_pl': 'Przystawanie to szczególne podobieństwo ze skalą k = 1 (ten sam rozmiar).',
        'def_ua': 'Рівність фігур — особлива подібність із масштабом k = 1 (той самий розмір).',
        'rule': 'k=1 → ≅',
        'rule_ua': 'k=1 → ≅',
        'przykłady': ['podobieństwo k=2', 'przystawanie k=1', 'te same kąty w obu'],
        'nie_pomyl': [('przystawanie (k=1)', 'podobieństwo (k≠1)')],
    },
    (69, 'podobieństwo'): {
        'nie_pomyl': [('podobieństwo (inna skala OK)', 'przystawanie (ta sama skala)')],
        'rule': '~ — ten sam kształt, inna skala',
        'rule_ua': '~ — та сама форма, інший масштаб',
    },
    (70, 'okrąg opisany'): {
        'def_pl': 'Okrąg opisany przechodzi przez wszystkie wierzchołki wielokąta.',
        'def_ua': 'Описане коло проходить через усі вершини многокутника.',
        'rule': 'przez wierzchołki',
        'rule_ua': 'через вершини',
        'przykłady': ['w trójkącie zawsze istnieje', 'środek = przecięcie symetralnych', 'nie myl z wpisanym'],
    },
    (70, 'okrąg wpisany'): {
        'def_pl': 'Okrąg wpisany styka się z bokami wielokąta od wewnątrz.',
        'def_ua': 'Вписане коло торкається сторін многокутника зсередини.',
        'rule': 'styczny do boków',
        'rule_ua': 'дотичне до сторін',
        'przykłady': ['w trójkącie zawsze istnieje', 'środek = przecięcie dwusiecznych', 'nie myl z opisanym'],
    },
    (70, 'w trójkącie'): {
        'def_pl': 'W każdym trójkącie da się wpisać okrąg i opisać okrąg na trójkącie.',
        'def_ua': 'У кожному трикутнику можна вписати коло і описати коло навколо трикутника.',
        'rule': 'wpisany + opisany zawsze',
        'rule_ua': 'вписане + описане завжди',
        'nie_pomyl': [],
        'przykłady': ['dwusieczne → środek wpisanego', 'symetralne → środek opisanego', 'narysuj oba'],
    },
    (71, 'obrót'): {
        'def_pl': 'Obrót to obracanie figury wokół punktu o dany kąt (jak wskazówka zegara).',
        'def_ua': 'Поворот — обертання фігури навколо точки на даний кут (як стрілка годинника).',
        'rule': 'punkt + kąt',
        'rule_ua': 'точка + кут',
        'przykłady': ['obrót o 90°', 'środek obrotu', 'nie myl z przesunięciem'],
    },
    (71, 'przesunięcie'): {
        'def_pl': 'Przesunięcie to ruch figury w bok bez obrotu — każdy punkt o ten sam wektor.',
        'def_ua': 'Паралельне перенесення — рух фігури вбік без повороту: кожна точка на той самий вектор.',
        'rule': 'ten sam wektor',
        'rule_ua': 'той самий вектор',
        'przykłady': ['przesuń o 3 w prawo', 'kształt i rozmiar bez zmian', 'nie myl z obrotem'],
    },
    (72, 'liczba niewymierna'): {
        'def_pl': 'Liczba niewymierna nie da się zapisać jako a/b (mianownik ≠ 0). W SP: np. √2, π (rozszerzenie).',
        'def_ua': 'Ірраціональне число не можна записати як a/b (знаменник ≠ 0). У SP: напр. √2, π (розширення).',
        'rule': '√2, π ∉ ℚ (rozszerzenie)',
        'rule_ua': '√2, π ∉ ℚ (розширення)',
        'przykłady': ['√2 ≈ 1,414…', 'π ≈ 3,141…', 'nie myl z ułamkiem okresowym'],
        'nie_pomyl': [('niewymierna (√2, π)', 'wymierna (½, 0,75)')],
    },
    (72, 'na osi'): {
        'def_pl': 'Wymierne i niewymierne leżą na osi liczbowej; niewymiernych nie zapiszesz dokładnym ułamkiem.',
        'def_ua': 'Раціональні й ірраціональні лежать на числовій прямій; ірраціональні не запишеш точним дробом.',
        'rule': 'wszystkie na osi',
        'rule_ua': 'усі на прямій',
        'nie_pomyl': [],
        'przykłady': ['0,5 na osi', '√2 między 1 a 2', 'π ≈ 3,14'],
    },
    (72, 'przykłady wymiernych'): {
        'def_pl': 'Wymierne: ułamki, całkowite, skończone i okresowe dziesiętne — np. ½, −3, 0,75, 0,(3).',
        'def_ua': 'Раціональні: дроби, цілі, скінченні й періодичні десяткові — напр. ½, −3, 0,75, 0,(3).',
        'rule': '½, −3, 0,75, 0,(3)',
        'rule_ua': '½, −3, 0,75, 0,(3)',
        'przykłady': ['½ = 0,5', '1/3 = 0,(3)', '−7 ∈ ℚ'],
        'nie_pomyl': [],
    },
    (73, 'środkowa'): {
        'def_pl': 'Środkowa w trójkącie łączy wierzchołek ze środkiem przeciwległego boku.',
        'def_ua': "Медіана в трикутнику з'єднує вершину із серединою протилежної сторони.",
        'rule': 'wierzchołek → środek boku',
        'rule_ua': 'вершина → середина сторони',
        'przykłady': ['3 środkowe w trójkącie', 'przecinają się w środku ciężkości', 'nie myl z wysokością'],
        'nie_pomyl': [('środkowa (do środka boku)', 'wysokość (⊥ do boku)')],
    },
    (74, 'wzór klasyczny'): {
        'def_pl': 'Klasyczny wzór: P = k/n (korzystne przez wszystkie możliwe).',
        'def_ua': 'Класична формула: P = k/n (сприятливі через усі можливі).',
        'rule': 'P = k/n',
        'rule_ua': 'P = k/n',
        'przykłady': ['kostka: P(6)=1/6', 'moneta: P(orzeł)=1/2', '0 ≤ P ≤ 1'],
    },
    (75, 'przykład'): {
        'def_pl': '2 cm na mapie przy skali 1:50 000 to 2·50 000 cm = 1 km w terenie.',
        'def_ua': '2 см на карті при масштабі 1:50 000 — це 2·50 000 см = 1 км на місцевості.',
        'rule': 'mapa × n = teren',
        'rule_ua': 'карта × n = місцевість',
        'przykłady': ['1:100 000', '3 cm → ? km', 'sprawdź jednostki'],
        'nie_pomyl': [],
    },
})


EDITORIAL_V1.update({
    (34, "wierzchołkowe"): {
        "def_pl": "Kąty wierzchołkowe leżą naprzeciw siebie przy przecięciu dwóch prostych — zawsze są równe.",
        "def_ua": "Вертикальні кути лежать навпроти при перетині двох прямих — завжди рівні.",
        "rule": "naprzeciw siebie → równe",
        "rule_ua": "навпроти → рівні",
        "przykłady": ["przy przecięciu X", "kąty naprzeciw równe", "nie myl z przyległymi"],
    },
})


# --- pass3: meta-hasła + krótkie def ---
EDITORIAL_V1.update({
    (3, 'wartość bezwzględna'): {
        'def_pl': 'Wartość bezwzględna to odległość liczby od zera — zawsze nieujemna (jak długość kroku).',
        'def_ua': "Модуль — відстань числа від нуля — завжди невід'ємна (як довжина кроку).",
        'rule': '|a| = odległość od 0',
        'rule_ua': '|a| = відстань від 0',
        'nie_pomyl': [('|−5| = 5', 'wynik −5'), ('odległość od 0', 'liczba przeciwna')],
        'przykłady': ['|−7| = 7', '|5| = 5', '|0| = 0'],
    },
    (4, 'przykłady'): {
        'nie_pomyl': [],
        'przykłady': ['3+5=8', '12−7=5', 'sprawdź: 5+7=12'],
    },
    (7, 'przykład'): {
        'nie_pomyl': [],
        'przykłady': ['a(b+c)=ab+ac', 'sprawdź liczbą', 'nie tylko jedną stronę'],
    },
    (14, 'przykłady'): {
        'nie_pomyl': [],
        'przykłady': ['√9 = 3', '√16 = 4', '√25 = 5'],
    },
    (14, 'zapis'): {
        'nie_pomyl': [],
        'przykłady': ['√9 = 3', '√16 = 4', '√25 = 5'],
    },
    (15, 'przykłady'): {
        'nie_pomyl': [],
        'przykłady': ['50% z 80 = 40', '10% z 200 = 20', '25% = ¼'],
    },
    (16, 'przykład'): {
        'nie_pomyl': [],
        'przykłady': ['2 kg = 2000 g', '3,5 kg = 3500 g', '250 g = 0,25 kg'],
    },
    (18, 'przykład'): {
        'nie_pomyl': [],
        'przykłady': ['lekcja 45 min', '2×10 min przerwy', 'od 8:00 do 9:30'],
    },
    (19, 'sprawdzenie'): {
        'nie_pomyl': [],
        'przykłady': ['x+5=12', 'sprawdź podstawieniem', 'L = P'],
    },
    (20, 'przykład'): {
        'nie_pomyl': [],
        'przykłady': ['przykład z lekcji', 'przykład z życia', 'zapisz w zeszycie'],
    },
    (21, 'przykłady'): {
        'nie_pomyl': [],
        'przykłady': ['2 kg = 2000 g', '3,5 kg = 3500 g', '250 g = 0,25 kg'],
    },
    (21, 'w życiu'): {
        'nie_pomyl': [],
        'przykłady': ['2 kg = 2000 g', '3,5 kg = 3500 g', '250 g = 0,25 kg'],
    },
    (22, 'przykład'): {
        'nie_pomyl': [],
        'przykłady': ['V = a·b·c', '2×3×4 = 24', 'pudełko 5×5×10'],
    },
    (23, 'przykład'): {
        'nie_pomyl': [],
        'przykłady': ['lekcja 45 min', '2×10 min przerwy', 'od 8:00 do 9:30'],
    },
    (24, 'przykład'): {
        'nie_pomyl': [],
        'przykłady': ['przykład z lekcji', 'przykład z życia', 'zapisz w zeszycie'],
    },
    (25, 'w życiu'): {
        'nie_pomyl': [],
        'przykłady': ['−5°C na dworze', '180°C w piekarniku', '36,6°C ciało'],
    },
    (26, 'zapis'): {
        'nie_pomyl': [],
        'przykłady': ['1 zł = 100 gr', 'reszta z 20 zł', '3,50 zł'],
    },
    (30, 'promień'): {
        'def_pl': 'Promień to odcinek od środka do punktu na okręgu — „pół średnicy”.',
        'def_ua': 'Радіус — відрізок від центра до точки на колі — «половина діаметра».',
        'rule': 'r — od środka do okręgu',
        'rule_ua': 'r — від центра до кола',
        'nie_pomyl': [('promień r (środek → okrąg)', 'średnica d = 2r')],
        'przykłady': ['r = 5 cm', 'O do brzegu', 'd = 2r'],
    },
    (37, 'przykłady'): {
        'nie_pomyl': [],
        'przykłady': ['litera A — oś', 'koło — wiele osi', 'N — bez osi pionowej'],
    },
    (47, 'w życiu'): {
        'nie_pomyl': [],
        'przykłady': ['2 kg = 2000 g', '3,5 kg = 3500 g', '250 g = 0,25 kg'],
    },
    (48, 'w życiu'): {
        'nie_pomyl': [],
        'przykłady': ['ściana ⊥ podłoga', 'róg zeszytu', 'skrzyżowanie'],
    },
    (55, 'sprawdzenie'): {
        'nie_pomyl': [],
        'przykłady': ['a(b+c)=ab+ac', 'sprawdź liczbą', 'nie tylko jedną stronę'],
    },
    (56, 'przykład'): {
        'nie_pomyl': [],
        'przykłady': ['przykład z lekcji', 'przykład z życia', 'zapisz w zeszycie'],
    },
    (57, 'w życiu'): {
        'nie_pomyl': [],
        'przykłady': ['drabina przy ścianie', 'przekątna TV', '3-4-5'],
    },
    (62, 'w życiu'): {
        'nie_pomyl': [],
        'przykłady': ['puszka napoju', 'rura', 'rolka papieru'],
    },
    (63, 'w życiu'): {
        'nie_pomyl': [],
        'przykłady': ['rożek lodów', 'lejek', 'czapka'],
    },
    (64, 'w życiu'): {
        'nie_pomyl': [],
        'przykłady': ['piłka', 'globus', 'pomarańcza'],
    },
    (66, 'a równanie?'): {
        'nie_pomyl': [],
        'przykłady': ['x+5=12', 'sprawdź podstawieniem', 'L = P'],
    },
    (68, 'przykłady'): {
        'nie_pomyl': [],
        'przykłady': ['trójkąt równoboczny', 'kwadrat', 'sześciokąt foremny'],
    },
    (69, 'a przystawanie?'): {
        'nie_pomyl': [],
        'przykłady': ['mapa', 'model auta', 'powiększenie zdjęcia'],
    },
    (69, 'w życiu'): {
        'nie_pomyl': [],
        'przykłady': ['mapa', 'model auta', 'powiększenie zdjęcia'],
    },
    (75, 'przykład'): {
        'nie_pomyl': [],
        'przykłady': ['mapa', 'model auta', 'powiększenie zdjęcia'],
    },
})


# --- pass4: meta-hasła poprawione ---
EDITORIAL_V1.update({
    (3, 'wartość bezwzględna'): {
        'def_pl': 'Wartość bezwzględna to odległość liczby od zera — zawsze nieujemna (jak długość kroku).',
        'def_ua': "Модуль — відстань числа від нуля — завжди невід'ємна (як довжина кроку).",
        'rule': '|a| = odległość od 0',
        'rule_ua': '|a| = відстань від 0',
        'nie_pomyl': [('|−5| = 5', 'wynik −5'), ('odległość od 0', 'liczba przeciwna')],
        'przykłady': ['|−7| = 7', '|5| = 5', '|0| = 0'],
    },
    (4, 'przykłady'): {
        'def_pl': 'Ćwicz dodawanie i odejmowanie, potem sprawdź wynik.',
        'def_ua': 'Тренуй додавання й віднімання, потім перевір результат.',
        'rule': 'po odejmowaniu sprawdź dodawaniem',
        'rule_ua': 'після віднімання перевір додаванням',
        'przykłady': ['3+5=8', '12−7=5', 'sprawdź: 5+7=12'],
        'nie_pomyl': [],
    },
    (7, 'przykład'): {
        'def_pl': 'Trudniejszy zapis liczysz warstwami: nawias → potęga → ×: → +−.',
        'def_ua': 'Складніший запис рахуй шарами: дужки → степінь → ×: → +−.',
        'rule': '( ) → aⁿ → ×: → +−',
        'rule_ua': '( ) → aⁿ → ×: → +−',
        'visual': '(2+3)×4 = 20',
        'przykłady': ['(2+3)×4 = 20', '2+3×4 = 14', '2+3² = 11'],
        'nie_pomyl': [],
    },
    (14, 'przykłady'): {
        'def_pl': 'Najczęstsze pierwiastki warto znać na pamięć — jak tabliczkę mnożenia.',
        'def_ua': "Найчастіші корені варто знати напам'ять — як таблицю множення.",
        'rule': '√1 · √4 · √9 · √16 · √25',
        'rule_ua': '√1 · √4 · √9 · √16 · √25',
        'przykłady': ['√9 = 3', '√16 = 4', '√25 = 5'],
        'nie_pomyl': [],
    },
    (14, 'zapis'): {
        'def_pl': 'Znak pierwiastka √ stoi przed liczbą lub wyrażeniem — szukasz liczby do kwadratu.',
        'def_ua': 'Знак кореня √ стоїть перед числом або виразом — шукаєш число до квадрата.',
        'rule': '√9 = 3, bo 3² = 9',
        'rule_ua': '√9 = 3, бо 3² = 9',
        'przykłady': ['√9 = 3', '√16 = 4', '√(4+5) = 3'],
        'nie_pomyl': [],
    },
    (15, 'przykłady'): {
        'def_pl': 'Ćwicz „łatwe procenty”: 10%, 25%, 50% — potem resztę.',
        'def_ua': 'Тренуй «легкі відсотки»: 10%, 25%, 50% — потім решту.',
        'rule': '10% · 25% · 50% · 100%',
        'rule_ua': '10% · 25% · 50% · 100%',
        'przykłady': ['50% z 80 = 40', '10% z 200 = 20', '25% = ¼'],
        'nie_pomyl': [],
    },
    (16, 'przykład'): {
        'def_pl': 'Gdy wielkości są wprost proporcjonalne, obie mnożysz (lub dzielisz) przez tę samą liczbę.',
        'def_ua': 'Коли величини прямо пропорційні, обидві множиш (або ділиш) на те саме число.',
        'rule': '× k obie wielkości',
        'rule_ua': '× k обидві величини',
        'przykłady': ['2 kg → 6 zł; 4 kg → 12 zł', 'tabela ×2', 'wykres — prosta'],
        'nie_pomyl': [],
    },
    (18, 'przykład'): {
        'def_pl': 'Redukcja: grupujesz litery osobno i zwykłe liczby osobno, potem dodajesz.',
        'def_ua': 'Зведення: групуєш літери окремо і звичайні числа окремо, потім додаєш.',
        'rule': '3x+2x+5 = 5x+5',
        'rule_ua': '3x+2x+5 = 5x+5',
        'przykłady': ['3x+2x = 5x', '7−2+4a−a', 'podobne do podobnych'],
        'nie_pomyl': [],
    },
    (19, 'sprawdzenie'): {
        'def_pl': 'Sprawdzenie równania: podstaw wynik na miejsce x i policz obie strony.',
        'def_ua': 'Перевірка рівняння: підстав результат замість x і порахуй обидва боки.',
        'rule': 'podstaw → L = P?',
        'rule_ua': 'підстав → L = P?',
        'przykłady': ['x+5=12 → x=7; 7+5=12 ✔', '2x=14 → x=7', 'nie zgaduj bez sprawdzenia'],
        'nie_pomyl': [],
    },
    (20, 'przykład'): {
        'def_pl': 'Przy zamianie jednostek długości przecinek (lub zera) „przesuwa się” o odpowiednią liczbę miejsc.',
        'def_ua': 'При заміні одиниць довжини кома (або нулі) «зсувається» на відповідну кількість місць.',
        'rule': '1 m = 100 cm = 1000 mm',
        'rule_ua': '1 м = 100 см = 1000 мм',
        'przykłady': ['2,5 m = 250 cm', '30 mm = 3 cm', '1,2 km = 1200 m'],
        'nie_pomyl': [],
    },
    (21, 'przykłady'): {
        'def_pl': 'Ćwicz zamianę masy: przy kg ↔ g przecinek „skacze” o trzy miejsca.',
        'def_ua': 'Тренуй заміну маси: при кг ↔ г кома «стрибає» на три місця.',
        'rule': '1 kg = 1000 g',
        'rule_ua': '1 кг = 1000 г',
        'przykłady': ['2 kg = 2000 g', '3500 g = 3,5 kg', '0,25 kg = 250 g'],
        'nie_pomyl': [],
    },
    (21, 'w życiu'): {
        'def_pl': 'Masę widzisz na etykietach: zakupy, przepisy, paczki.',
        'def_ua': 'Масу бачиш на етикетках: покупки, рецепти, пакунки.',
        'rule': 'nettó na etykiecie',
        'rule_ua': 'нетто на етикетці',
        'przykłady': ['mąka 1 kg', 'jogurt 150 g', 'waga kuchenna'],
        'nie_pomyl': [],
    },
    (22, 'przykład'): {
        'def_pl': 'Objętość prostopadłościanu (pudełka) liczysz, mnożąc trzy wymiary: V = a·b·c.',
        'def_ua': "Об'єм прямокутного паралелепіпеда (коробки) рахуєш, множачи три виміри: V = a·b·c.",
        'rule': 'V = a·b·c',
        'rule_ua': 'V = a·b·c',
        'przykłady': ['2×3×4 = 24', 'pudełko 5×5×10', 'wynik w cm³ / litrach'],
        'nie_pomyl': [],
    },
    (23, 'przykład'): {
        'def_pl': 'Przerwa 15 minut, lekcja zwykle 45. Policz od dzwonka do dzwonka.',
        'def_ua': 'Перерва 15 хвилин, урок зазвичай 45. Порахуй від дзвінка до дзвінка.',
        'rule': '15 min · 45 min',
        'rule_ua': '15 хв · 45 хв',
        'przykłady': ['lekcja 45 min', '2 przerwy po 10 min', 'od 8:00 do 9:30'],
        'nie_pomyl': [],
    },
    (24, 'przykład'): {
        'def_pl': 'Przy liczeniu dni uważaj na koniec lutego — w roku nieprzestępnym ma 28 dni, w przestępnym 29.',
        'def_ua': 'Коли рахуєш дні, зважай на кінець лютого — у звичайному році 28 днів, у високосному 29.',
        'rule': 'luty: 28 albo 29',
        'rule_ua': 'лютий: 28 або 29',
        'przykłady': ['od 28 II do 1 III', 'rok przestępny', '30 dni ma…'],
        'nie_pomyl': [],
    },
    (25, 'w życiu'): {
        'def_pl': 'Temperaturę czytamy w pogodzie, piekarniku, przy zdrowiu.',
        'def_ua': "Температуру читаємо в погоді, духовці, при здоров'ї.",
        'rule': '°C w życiu',
        'rule_ua': '°C у житті',
        'przykłady': ['−5°C na dworze', '180°C w piekarniku', '36,6°C ciało'],
        'nie_pomyl': [],
    },
    (26, 'zapis'): {
        'def_pl': 'Pieniądze zapisujemy jak liczbę dziesiętną: złote przed przecinkiem, grosze po.',
        'def_ua': 'Гроші записуємо як десяткове число: злоті перед комою, гроші після.',
        'rule': '1 zł = 100 gr',
        'rule_ua': '1 zł = 100 gr',
        'przykłady': ['3,50 zł', 'reszta z 20 zł', '1 zł = 100 gr'],
        'nie_pomyl': [],
    },
    (30, 'promień'): {
        'def_pl': 'Promień to odcinek od środka do punktu na okręgu — „pół średnicy”.',
        'def_ua': 'Радіус — відрізок від центра до точки на колі — «половина діаметра».',
        'rule': 'r — od środka do okręgu',
        'rule_ua': 'r — від центра до кола',
        'nie_pomyl': [('promień r', 'średnica d = 2r')],
        'przykłady': ['r = 5 cm', 'O do brzegu', 'd = 2r'],
    },
    (37, 'przykłady'): {
        'def_pl': 'Symetryczne bywają figury i litery — ćwicz rozpoznawanie osi i środka.',
        'def_ua': 'Симетричними бувають фігури і літери — тренуй розпізнавання осей і центра.',
        'rule': 'oś / środek symetrii',
        'rule_ua': 'вісь / центр симетрії',
        'przykłady': ['litera A — oś pionowa', 'koło — wiele osi', 'N — bez osi pionowej'],
        'nie_pomyl': [],
    },
    (47, 'w życiu'): {
        'def_pl': 'Wzrost 1 m 42 cm, film 1 h 45 min, mąka 1 kg 250 g — to wyrażenia dwumianowane.',
        'def_ua': 'Зріст 1 м 42 см, фільм 1 год 45 хв, борошно 1 кг 250 г — двочленні вирази.',
        'rule': '1 m 42 cm',
        'rule_ua': '1 м 42 см',
        'przykłady': ['1 h 45 min', '1 kg 250 g', '1 m 42 cm'],
        'nie_pomyl': [],
    },
    (48, 'w życiu'): {
        'def_pl': 'Ściana i podłoga, róg zeszytu, skrzyżowanie „na krzyż” — kąt prosty w otoczeniu.',
        'def_ua': 'Стіна і підлога, ріг зошита, перехрестя «навхрест» — прямий кут навколо.',
        'rule': '⊥ w życiu',
        'rule_ua': '⊥ у житті',
        'przykłady': ['ściana ⊥ podłoga', 'róg kartki', 'skrzyżowanie'],
        'nie_pomyl': [],
    },
    (55, 'sprawdzenie'): {
        'def_pl': 'Sprawdź liczbowo: podstaw konkretne x do nawiasów i do wyniku — czy wyjdzie to samo?',
        'def_ua': 'Перевір числом: підстав конкретне x у дужки і в результат — чи вийде те саме?',
        'rule': 'podstaw x=… i porównaj',
        'rule_ua': 'підстав x=… і порівняй',
        'przykłady': ['x=2 w obu stronach', 'x=0 szybki test', 'x=1'],
        'nie_pomyl': [],
    },
    (56, 'przykład'): {
        'def_pl': '60 zł dla Ali i Basi w stosunku 1:2 → 3 części; jedna = 20 → Ala 20, Basia 40.',
        'def_ua': '60 zł для Алі й Басі у відношенні 1:2 → 3 частини; одна = 20 → Аля 20, Бася 40.',
        'rule': 'suma części → wartość jednej',
        'rule_ua': 'сума частин → значення однієї',
        'przykłady': ['1:2 z 60 zł', '3:5 z 40 cukierków', 'sprawdź sumą'],
        'nie_pomyl': [],
    },
    (57, 'w życiu'): {
        'def_pl': 'Drabina przy ścianie, przekątna ekranu — twierdzenie Pitagorasa w praktyce.',
        'def_ua': 'Драбина біля стіни, діагональ екрана — теорема Піфагора на практиці.',
        'rule': 'a²+b²=c² w życiu',
        'rule_ua': 'a²+b²=c² у житті',
        'przykłady': ['drabina przy ścianie', 'przekątna TV', '3-4-5'],
        'nie_pomyl': [],
    },
    (62, 'w życiu'): {
        'def_pl': 'Puszki, rury, rolki papieru — często mają kształt walca.',
        'def_ua': 'Банки, труби, рулони паперу — часто мають форму циліндра.',
        'rule': 'puszka ≈ walec',
        'rule_ua': 'банка ≈ циліндр',
        'przykłady': ['puszka napoju', 'rura', 'rolka papieru'],
        'nie_pomyl': [],
    },
    (63, 'w życiu'): {
        'def_pl': 'Rożek lodów, lejek, czapka — kształt stożka.',
        'def_ua': 'Ріжок морозива, лійка, ковпак — форма конуса.',
        'rule': 'rożek ≈ stożek',
        'rule_ua': 'ріжок ≈ конус',
        'przykłady': ['rożek lodów', 'lejek', 'czapka'],
        'nie_pomyl': [],
    },
    (64, 'w życiu'): {
        'def_pl': 'Piłka, globus, pomarańcza — kształt zbliżony do kuli.',
        'def_ua': "М'яч, глобус, апельсин — форма близька до кулі.",
        'rule': 'piłka ≈ kula',
        'rule_ua': "м'яч ≈ куля",
        'przykłady': ['piłka', 'globus', 'pomarańcza'],
        'nie_pomyl': [],
    },
    (68, 'przykłady'): {
        'def_pl': 'Foremny 3-kąt = równoboczny; foremny 4-kąt = kwadrat.',
        'def_ua': 'Правильний 3-кутник = рівносторонній; правильний 4-кутник = квадрат.',
        'rule': 'foremny = równe boki i kąty',
        'rule_ua': 'правильний = рівні сторони і кути',
        'przykłady': ['trójkąt równoboczny', 'kwadrat', 'sześciokąt foremny'],
        'nie_pomyl': [],
    },
    (69, 'w życiu'): {
        'def_pl': 'Podobieństwo w życiu: mapa, model samochodu, powiększenie zdjęcia — ten sam kształt, inna skala.',
        'def_ua': 'Подібність у житті: карта, модель авто, збільшення фото — та сама форма, інший масштаб.',
        'rule': 'ten sam kształt, inna skala',
        'rule_ua': 'та сама форма, інший масштаб',
        'przykłady': ['mapa', 'model auta', 'powiększenie zdjęcia'],
        'nie_pomyl': [],
    },
    (75, 'przykład'): {
        'def_pl': '2 cm na mapie przy skali 1:50 000 to 2·50 000 cm = 1 km w terenie.',
        'def_ua': '2 см на карті при масштабі 1:50 000 — це 2·50 000 см = 1 км на місцевості.',
        'rule': 'mapa × n = teren',
        'rule_ua': 'карта × n = місцевість',
        'przykłady': ['1:50 000', '3 cm → ? km', 'sprawdź jednostki'],
        'nie_pomyl': [],
    },
})


# --- pass5: krótkie niejasne ---
EDITORIAL_V1.update({
    (4, 'właściwości −'): {
        'def_pl': 'Przy odejmowaniu: minus zero nic nie zmienia; liczba minus ona sama daje 0. Kolejności nie wolno odwracać!',
        'def_ua': 'При відніманні: мінус нуль нічого не змінює; число мінус воно саме дає 0. Порядок не можна міняти!',
        'rule': 'a−0=a · a−a=0',
        'rule_ua': 'a−0=a · a−a=0',
        'przykłady': ['7−0=7', '9−9=0', '9−4 ≠ 4−9'],
    },
    (6, ':1 i : siebie'): {
        'def_pl': 'Dzielenie przez 1 nie zmienia liczby. Liczba dzielona przez siebie daje 1 (dzielnik ≠ 0).',
        'def_ua': 'Ділення на 1 не змінює числа. Число, ділене на себе, дає 1 (дільник ≠ 0).',
        'rule': 'a:1=a · a:a=1',
        'rule_ua': 'a:1=a · a:a=1',
        'przykłady': ['8:1=8', '8:8=1', 'a:0 zabronione'],
        'nie_pomyl': [('a:1=a', 'a:0 — nie wolno')],
    },
    (13, '0, 1, 10'): {
        'def_pl': 'Potęga z wykładnikiem 1 to ta sama liczba. Z wykładnikiem 0 (gdy podstawa ≠ 0) daje 1. Potęgi 10: 10¹=10, 10²=100…',
        'def_ua': 'Степінь з показником 1 — те саме число. З показником 0 (коли основа ≠ 0) дає 1. Степені 10: 10¹=10, 10²=100…',
        'rule': 'a¹=a · a⁰=1 (a≠0) · 10ⁿ',
        'rule_ua': 'a¹=a · a⁰=1 (a≠0) · 10ⁿ',
        'przykłady': ['5¹=5', '5⁰=1', '10³=1000'],
    },
    (69, 'a przystawanie?'): {
        'def_pl': 'Przystawanie to szczególne podobieństwo ze skalą k = 1 (ten sam rozmiar).',
        'def_ua': 'Рівність фігур — особлива подібність із масштабом k = 1 (той самий розмір).',
        'rule': 'k=1 → ≅',
        'rule_ua': 'k=1 → ≅',
        'przykłady': ['podobieństwo k=2', 'przystawanie k=1', 'te same kąty w obu'],
        'nie_pomyl': [('przystawanie (k=1)', 'podobieństwo (k≠1)')],
    },
})

EDITORIAL_V1 = {k: v for k, v in EDITORIAL_V1.items() if v}
