# -*- coding: utf-8 -*-
"""Bank przykładów zastosowania (nie definicji) — SP 1–8."""

PRZYKLADY: dict[str, list[str]] = {
    "prawo / lewo": [
        "wskaż prawą rękę",
        "strzałka → = prawo",
        "lewo od drzwi",
        "skręć w lewo",
        "prawy róg strony",
    ],
    "góra / dół": [
        "piętro wyżej = góra",
        "strzałka ↓ = dół",
        "góra mapy",
        "schodź na dół",
        "górny rząd",
    ],
    "przed / za / obok": [
        "A przed B w kolejce",
        "C stoi za D",
        "E obok F",
        "7 przed 8",
        "5 za 4",
    ],
    "dłuższy / krótszy": [
        "linijka A dłuższa",
        "odcinek B krótszy",
        "12 cm > 9 cm",
        "który ołówek dłuższy?",
        "najkrótsza ścieżka",
    ],
    "cięższy / lżejszy": [
        "worek cięższy o 2 kg",
        "piórko lżejsze od książki",
        "3 kg > 1 kg",
        "co jest lżejsze?",
        "waż na szali",
    ],
    "więcej / mniej / tyle samo": [
        "8 > 5: więcej",
        "3 < 7: mniej",
        "4 = 4: tyle samo",
        "kto ma więcej cukierków?",
        "po równo — tyle samo",
    ],
    "liczba naturalna": [
        "1, 2, 3, …",
        "5 jabłek w koszyku",
        "47 uczniów w szkole",
        "100 metrów biegu",
        "licz od 1 w górę",
    ],
    "podstawowe znaki": [
        "I = 1 na zegarze",
        "V = 5",
        "X = 10",
        "C = 100 (centum)",
        "M = 1000 (mille)",
    ],
    "składanie liczb": [
        "3 = III",
        "4 = IV (nie IIII)",
        "9 = IX",
        "14 = XIV",
        "50 = L",
    ],
    "dodawanie znaków": [
        "VI = V+I = 6",
        "VII = V+I+I = 7",
        "XI = X+I = 11",
        "XV = X+V = 15",
        "VIII = V+I+I+I = 8",
    ],
    "odejmowanie znaków": [
        "IV = V−I = 4",
        "IX = X−I = 9",
        "XL = L−X = 40",
        "XC = C−X = 90",
        "CM = M−C = 900",
    ],
    "ograniczenia": [
        "IIII ✖ → użyj IV",
        "VV ✖ → użyj X",
        "IL ✖ (I nie przed L)",
        "max III z rzędu",
        "nie powtarzaj V, L, D",
    ],
    "większe przykłady": [
        "XIV = 14",
        "XLIV = 44",
        "XCIX = 99",
        "MMXXIV = 2024",
        "MDCCLXXVI = 1776",
    ],
    "gdzie spotykamy?": [
        "zegar: XII",
        "rozdział IV",
        "tom II książki",
        "Jan III Sobieski",
        "data na pomniku",
    ],
    "zamiana na arabskie": [
        "VII → 7",
        "XII → 12",
        "LXIV → 64",
        "XC → 90",
        "CM → 900",
    ],
    "cyfra": [
        "0–9: cyfry",
        "347 ma 3 cyfry",
        "cyfra 5 w 258",
        "zapisz cyfrą: siedem → 7",
        "9 to jedna cyfra",
    ],
    "liczba": [
        "12 to liczba",
        "258 = trzy cyfry",
        "liczba parzysta: 14",
        "porównaj liczby 23 i 31",
        "zapisz liczbą: dwadzieścia",
    ],
    "wartość pozycyjna": [
        "347: 3→300",
        "347: 4→40",
        "347: 7→7",
        "508: 5→500",
        "508: 0→0 dziesiątek",
    ],
    "liczba porządkowa": [
        "1. pierwszy uczeń",
        "2. drugi dom",
        "3. trzecie piętro",
        "4. czwarty wagon",
        "5. piąte miejsce",
    ],
    "zero": [
        "0 cukierków",
        "0°C",
        "0 zł",
        "0 punktów",
        "0 = brak",
    ],
    "parzysta / nieparzysta": [
        "8 ✔ parzysta",
        "14 ✔",
        "27 ✖ nieparzysta",
        "30 ✔",
        "41 ✖",
    ],
    "porównanie": [
        "3 < 8",
        "15 > 9",
        "20 = 20",
        "45 > 18",
        "7 < 11",
    ],
    "zaokrąglanie": [
        "14 → 10",
        "17 → 20",
        "42 → 40",
        "46 → 50",
        "198 → 200",
    ],
    "następnik / poprzednik": [
        "nast. 17 = 18",
        "poprz. 17 = 16",
        "nast. 99 = 100",
        "poprz. 100 = 99",
        "nast. 0 = 1",
    ],
    "kolejność liczb": [
        "3, 5, 7 rosnąco",
        "10, 8, 6 malejąco",
        "ustaw: 12, 4, 9",
        "która najmniejsza?",
        "ciąg: 2, 4, 6, 8",
    ],
    "podstawowe znaki": [
        "I = 1",
        "V = 5",
        "X = 10",
        "L = 50",
        "C = 100",
    ],
    "przykłady": [
        "2+3=5",
        "7+8=15",
        "8−3=5",
        "15−6=9 · sprawdź 9+6",
        "wymyśl z cukierków",
    ],
    "dodawanie znaków": [
        "VI = V+I",
        "VII = V+I+I",
        "III = I+I+I",
        "IX = X−I",
        "XV = X+V",
    ],
    "odejmowanie znaków": [
        "IV = V−I",
        "IX = X−I",
        "XL = L−X",
        "CM = M−C",
        "CD = D−C",
    ],
    "ograniczenia": [
        "max 3× ten sam znak",
        "IIII ✖ — użyj IV",
        "VV ✖ — użyj X",
        "tylko I,X,C,M",
        "nie powtarzaj V,L,D",
    ],
    "większe przykłady": [
        "XIV = 14",
        "XIX = 19",
        "XLIV = 44",
        "XCIX = 99",
        "MMXXIV = 2024",
    ],
    "gdzie spotykamy?": [
        "zegar: XII",
        "tom II książki",
        "Król Jan III",
        "MMXXIV na pomniku",
        "rozdział IV",
    ],
    "zamiana na arabskie": [
        "VII → 7",
        "XII → 12",
        "XX → 20",
        "L → 50",
        "CM → 900",
    ],
    "oś liczbowa": [
        "−2, −1, 0, 1, 2",
        "zaznacz 3 na osi",
        "−4 lewo od zera",
        "5 prawo od zera",
        "która dalej od 0?",
    ],
    "dodatnie, ujemne, zero": [
        "+5 stopni",
        "−3 piętra",
        "0 na osi",
        "+12 > 0",
        "−2 < 0",
    ],
    "wartość bezwzględna": [
        "|−7| = 7",
        "|5| = 5",
        "|0| = 0",
        "odległość od 0",
        "|-3| = |3|",
    ],
    "porównywanie": [
        "−3 < 2",
        "−1 > −5",
        "0 > −4",
        "−8 < −2",
        "która większa: −6 czy −9?",
    ],
    "dodawanie": [
        "3 + 5 = 8",
        "12 + 7 = 19",
        "−2 + 6 = 4",
        "0 + 9 = 9",
        "15 + 28 = ?",
    ],
    "odejmowanie": [
        "9 − 4 = 5",
        "20 − 13 = 7",
        "5 − 8 = −3",
        "0 − 6 = −6",
        "100 − 47 = ?",
    ],
    "liczba przeciwna": [
        "przeciw. 5 = −5",
        "przeciw. −3 = 3",
        "przeciw. 0 = 0",
        "5 + (−5) = 0",
        "−7 i 7",
    ],
    "zastosowania": [
        "temperatura −5°C",
        "piętro −1",
        "saldo −20 zł",
        "winda: +2, −1",
        "wynik meczu +3",
    ],
    "suma": [
        "suma 4 i 6 = 10",
        "S = a + b",
        "suma: 15 + 23",
        "oblicz sumę",
        "suma składników",
    ],
    "różnica": [
        "różnica 10 i 3 = 7",
        "R = a − b",
        "20 − 12 = ?",
        "różnica temperatur",
        "ile zostało?",
    ],
    "składnik": [
        "3 + 5: skł. 3 i 5",
        "składnik + składnik",
        "zamień składniki",
        "brakujący składnik?",
        "7 + ? = 12",
    ],
    "odjemna i odjemnik": [
        "10 − 3: odj. 10",
        "odj. − odjemnik",
        "15 − 8 = 7",
        "odjemnik = 8",
        "odj. większa od wyniku",
    ],
    "właściwości +": [
        "3+5 = 5+3",
        "(2+3)+4 = 2+(3+4)",
        "a+0 = a",
        "łączność w zadaniu",
        "przemienność +",
    ],
    "właściwości −": [
        "7−3 ≠ 3−7",
        "10−0 = 10",
        "a−a = 0",
        "nie przemienne",
        "odejmij od większej",
    ],
    "przykład": [
        "12 + 8 = 20",
        "P = a·b w zadaniu",
        "½ + ¼ = ?",
        "oblicz krok po kroku",
        "sprawdź wynik",
    ],
    "dodawanie na palcach / osi": [
        "3+2 na palcach",
        "start 5, +3 na osi",
        "pokaż 4, dołóż 1",
        "dwa skoki w prawo",
        "ile razem?",
    ],
    "odejmowanie: ile zostało": [
        "miałem 9, zabrałem 4",
        "10 − 3 = 7",
        "ile zostało cukierków?",
        "sprawdź: 7+3=10",
        "zabawa: zabierz 2",
    ],
    "mnożenie": [
        "4 × 3 = 12",
        "7 · 6 = 42",
        "tabliczka ×",
        "3 rzędy po 5",
        "2·2·2 = 8",
    ],
    "mnożenie = dodawanie tej samej": [
        "4×3 = 4+4+4",
        "5×2 = 5+5",
        "6×1 = 6",
        "3 razy po 7",
        "7+7+7 = 21",
    ],
    "iloczyn": [
        "iloczyn 3 i 4 = 12",
        "I = a · b",
        "oblicz iloczyn",
        "czynniki → iloczyn",
        "6 × 7 = ?",
    ],
    "czynnik": [
        "3 × 5: czyn. 3 i 5",
        "czynnik · czynnik",
        "zamień czynniki",
        "? × 4 = 20",
        "czynnik 0 → 0",
    ],
    "przemienność": [
        "3×5 = 5×3",
        "a·b = b·a",
        "2×9 = 9×2",
        "łatwiej: 4×25",
        "zamień czynniki",
    ],
    "×0 i ×1": [
        "5×0 = 0",
        "0×100 = 0",
        "8×1 = 8",
        "a×1 = a",
        "nic × 0 = 0",
    ],
    "kluczowe wyniki": [
        "6×7 = 42",
        "8×8 = 64",
        "9×9 = 81",
        "12×12 = 144",
        "5×6 = 30",
    ],
    "dzielenie": [
        "12 : 3 = 4",
        "dziel po równo",
        "28 : 7 = ?",
        "sprawdz. ×",
        "dzielenie z resztą",
    ],
    "sprawiedliwe rozdawanie": [
        "12 cuk. na 3 os.",
        "24 : 6 = 4 każdemu",
        "podziel równo",
        "po ile na osobę?",
        "reszty nie ma",
    ],
    "iloraz": [
        "iloraz 20 i 4 = 5",
        "Q = a : b",
        "oblicz iloraz",
        "dzielna : dzielnik",
        "15 : 3 = ?",
    ],
    "dzielna i dzielnik": [
        "12:3 — dzielna 12",
        "dzielnik = 3",
        "dzielna : dzielnik",
        "18 : 6 = 3",
        "dzielnik ≠ 0",
    ],
    "z resztą": [
        "17 : 5 = 3 r. 2",
        "23 : 4 = 5 r. 3",
        "reszta < dzielnik",
        "13 : 4 = ? r. ?",
        "podziel z resztą",
    ],
    "związek z ×": [
        "3×4 = 12 ↔ 12:4",
        "sprawdź dzieleniem",
        "7·8=56 → 56:8",
        "dzielenie odwrotne",
        "4·?=20",
    ],
    ":1 i : siebie": [
        "8 : 1 = 8",
        "a : 1 = a",
        "9 : 9 = 1",
        "a : a = 1 (a≠0)",
        "15 : 15 = 1",
    ],
    "nawiasy": [
        "(3+2)×4 = 20",
        "najpierw ( )",
        "2×(5+1) = 12",
        "usuń nawiasy",
        "(8−3)+2 = 7",
    ],
    "potęgi": [
        "2³ = 8",
        "najpierw potęga",
        "3² + 4 = 13",
        "5² = 25",
        "2⁴ = 16",
    ],
    "× i :": [
        "6×2 : 3 = 4",
        "48:6×2 = 16",
        "od lewej",
        "12:3×2 = 8",
        "× przed +",
    ],
    "+ i −": [
        "3+5−2 = 6",
        "10−4+1 = 7",
        "od lewej",
        "−3+8 = 5",
        "ostatnie + i −",
    ],
    "ten sam poziom": [
        "8−3+2: po kolei",
        "20:4×2: od lewej",
        "bez przeskakiwania",
        "4+6−3 = 7",
        "równe pierwszeństwo",
    ],
    "działanie pisemne": [
        "zapis w kolumnie",
        "licz krok po kroku",
        "przenieś jedynkę",
        "sprawdź szacunkiem",
        "działanie w zeszyt",
    ],
    "dodawanie pisemne": [
        "47 + 28 w słupku",
        "przenieś z dziesiątek",
        "oblicz: 156 + 387",
        "wyrównaj cyfry kolumnami",
        "sprawdź szacunkiem ≈ 540",
    ],
    "odejmowanie pisemne": [
        "82 − 47 w słupku",
        "pożycz z dziesiątek",
        "500 − 237",
        "0 w kolumnie",
        "sprawdź dodając",
    ],
    "mnożenie pisemne": [
        "23 × 14 w słupku",
        "mnoż przez cyfrę",
        "przesuń w lewo o 1",
        "oblicz: 127 × 8",
        "dodaj częściowe iloczyny",
    ],
    "dzielenie pisemne": [
        "156 : 12 w słupku",
        "ile razy mieści się?",
        "mnoż i odejmij",
        "oblicz: 384 : 16",
        "reszta < dzielnik",
    ],
    "szacowanie": [
        "49+52 ≈ 100",
        "198 ≈ 200",
        "czy wynik sensowny?",
        "287+312 ≈ 600",
        "zaokrąg i policz",
    ],
    "rozdzielność": [
        "6×13 = 6×10+6×3",
        "4×(3+2) = 20",
        "a(b+c) = ab+ac",
        "7×98 = 7×100−14",
        "łatwiej w pamięci",
    ],
    "przykład liczbowy": [
        "6×13 = 78",
        "4×(5+3) = 32",
        "15×12 = ?",
        "rozłóż i policz",
        "sprawdź wynik",
    ],
    "odwrotnie: wyłączanie": [
        "12+18 = 6·(2+3)",
        "wyłącz 6 przed ( )",
        "wspólny czynnik",
        "8+12 = 4·5",
        "grupuj wyrazy",
    ],
    "w geometrii": [
        "P = a·b prostokąt",
        "2(a+b) obwód",
        "πr² pole koła",
        "a=h w rombie",
        "wzór z zadania",
    ],
    "przez 2": [
        "14 ✔ /2",
        "27 ✖ /2",
        "ostatnia cyfra parz.",
        "68 : 2 = 34",
        "czy parzysta?",
    ],
    "przez 3": [
        "123 ✔ /3 (1+2+3=6)",
        "124 ✖ /3",
        "suma cyfr /3",
        "45 : 3 = 15",
        "456 ✔",
    ],
    "przez 4": [
        "124 ✔ /4",
        "126 ✖ /4",
        "2 ostatnie cyfry /4",
        "800 : 4 = 200",
        "36 ✔",
    ],
    "przez 5": [
        "35 ✔ /5",
        "42 ✖ /5",
        "kończy się 0 lub 5",
        "125 : 5 = 25",
        "90 ✔",
    ],
    "przez 9": [
        "729 ✔ /9 (7+2+9=18)",
        "731 ✖ /9",
        "suma cyfr /9",
        "81 : 9 = 9",
        "450 ✔",
    ],
    "przez 10": [
        "120 ✔ /10",
        "125 ✖ /10",
        "kończy się 0",
        "340 : 10 = 34",
        "1000 ✔",
    ],
    "dzielnik / wielokrotność": [
        "3|12 — dzielnik",
        "12 — wielokrotność 3",
        "5|25 ✔",
        "7|20 ✖",
        "wspólne wielokrotności",
    ],
    "liczba pierwsza": [
        "2, 3, 5, 7, 11",
        "17 ✔ pierwsza",
        "15 ✖ (3·5)",
        "1 ✖ pierwsza",
        "tylko 1 i siebie",
    ],
    "czynnik pierwszy": [
        "12 = 2²·3",
        "30 = 2·3·5",
        "18 = 2·3²",
        "rozkład na pierwsze",
        "7 — pierwszy czynnik",
    ],
    "rozkład na czynniki": [
        "24 = 2³·3",
        "36 = 2²·3²",
        "drzewko czynników",
        "60 = 2²·3·5",
        "podziel dalej",
    ],
    "nwd": [
        "NWD(12,18) = 6",
        "NWD(8,15) = 1",
        "wspólne dzielniki",
        "skracanie ułamków",
        "Euklides w zadaniu",
    ],
    "nww": [
        "NWW(4,6) = 12",
        "NWW(3,5) = 15",
        "wspólny mianownik",
        "spotkanie autobusów",
        "NWW z rozkładu",
    ],
    "liczba złożona": [
        "4 = 2·2 ✖ prosta",
        "9 = 3·3 złożona",
        "15 = 3·5",
        "1 ✖ złożona",
        "więcej niż 2 dzielniki",
    ],
    "do ułamków": [
        "NWD skraca 6/8",
        "NWW: wsp. mianownik",
        "12/18 → 2/3",
        "1/3 + 1/4: NWW",
        "upraszczaj przez NWD",
    ],
    "potęga": [
        "2⁴ = 16",
        "3³ = 27",
        "10² = 100",
        "5⁰ = 1",
        "2·2·2 = 2³",
    ],
    "podstawa i wykładnik": [
        "2⁵: podst. 2, wykł. 5",
        "10³: podst. 10",
        "aⁿ — co oznacza?",
        "3² podstawa 3",
        "wykładnik = ile razy",
    ],
    "kwadrat i sześcian": [
        "5² = 25 kwadrat",
        "4³ = 64 sześcian",
        "n² = n·n",
        "n³ = n·n·n",
        "3² i 2³ różne",
    ],
    "0, 1, 10": [
        "a⁰ = 1 (a≠0)",
        "a¹ = a",
        "10² = 100",
        "10³ = 1000",
        "5⁰ = 1",
    ],
    "mnożenie potęg": [
        "2³·2² = 2⁵",
        "aⁿ·aᵐ = aⁿ⁺ᵐ",
        "3⁴·3 = 3⁵",
        "ta sama podstawa",
        "dodaj wykładniki",
    ],
    "dzielenie potęg": [
        "2⁵:2² = 2³",
        "aⁿ:aᵐ = aⁿ⁻ᵐ",
        "10⁴:10² = 10²",
        "odejmij wykładniki",
        "5⁶:5³ = 5³",
    ],
    "notacja wykładnicza": [
        "3·10⁴ = 30000",
        "2,5·10³ = 2500",
        "6,1·10⁵",
        "zapis naukowy",
        "duże liczby krócej",
    ],
    "potęga potęgi": [
        "(2³)² = 2⁶",
        "(aⁿ)ᵐ = aⁿᵐ",
        "(5²)³ = 5⁶",
        "mnoż wykładniki",
        "(10²)⁴ = 10⁸",
    ],
    "różne podstawy, ten sam wykładnik": [
        "2³·5³ = 10³",
        "aⁿ·bⁿ = (ab)ⁿ",
        "3²·4² = 12²",
        "wyłącz wykładnik",
        "2⁴·5⁴ = 10⁴",
    ],
    "przypomnienie: ta sama podstawa": [
        "2³·2⁴ = 2⁷",
        "5⁶:5² = 5⁴",
        "a³·a² = a⁵",
        "łącz tylko takie",
        "3⁵:3 = 3⁴",
    ],
    "w nauce i technice": [
        "3·10⁸ m/s światło",
        "6,02·10²³ cząsteczki",
        "1,5·10⁶ km",
        "wielkie liczby",
        "w kalkulatorze ×10ⁿ",
    ],
    "pierwiastek kwadratowy": [
        "√9 = 3",
        "√25 = 5",
        "√16 = ?",
        "bok kwadratu √P",
        "√36 = 6",
    ],
    "zapis": [
        "√49 = 7",
        "√(a·a) = a",
        "√64 = 8",
        "symbol √ przed liczbą",
        "√100 = 10",
    ],
    "związek z potęgą": [
        "√25 = 25^½",
        "√(a²) = |a|",
        "5² = 25 ↔ √25",
        "potęga ½ = pierwiastek",
        "√81 = 9 bo 9²=81",
    ],
    "kwadraty doskonałe": [
        "1, 4, 9, 16, 25",
        "36 ✔ doskonały",
        "50 ✖ nie doskonały",
        "√49 = 7 dokładnie",
        "100 = 10²",
    ],
    "pierwiastek sześcienny": [
        "³√8 = 2",
        "³√27 = 3",
        "krawędź sześcianu",
        "³√64 = 4",
        "2³ = 8 ↔ ³√8",
    ],
    "związek z sześcianem": [
        "³√125 = 5",
        "5³ = 125",
        "bok z objętości",
        "³√1000 = 10",
        "V = a³ → a = ³√V",
    ],
    "wyłączanie sprzed pierwiastka": [
        "√12 = 2√3",
        "√50 = 5√2",
        "√72 = 6√2",
        "znajdź kwadrat",
        "√18 = 3√2",
    ],
    "włączanie pod pierwiastek": [
        "2√3 = √12",
        "5√2 = √50",
        "3√5 = √45",
        "a√b = √(a²b)",
        "4√2 = √32",
    ],
    "mnożenie i dzielenie pierwiastków": [
        "√2·√8 = 4",
        "√12 : √3 = 2",
        "√a·√b = √(ab)",
        "√50:√2 = 5",
        "√3·√3 = 3",
    ],
    "ułamek zwykły": [
        "½ — połowa",
        "¾ — trzy czwarte",
        "2/5 z tortu",
        "zaznacz 1/4",
        "3/8 na osi",
    ],
    "licznik": [
        "3/5: licznik 3",
        "ile części bierzesz",
        "7/8 — licznik 7",
        "licznik < mianownik?",
        "2/9 — góra ułamka",
    ],
    "mianownik": [
        "3/5: mianownik 5",
        "na ile części dzielisz",
        "1/4 — mianownik 4",
        "mianownik ≠ 0",
        "dół ułamka",
    ],
    "właściwy / niewłaściwy": [
        "3/5 ✔ właściwy",
        "7/4 ✖ niewłaściwy",
        "licznik < mianownik",
        "9/8 niewłaściwy",
        "2/3 właściwy",
    ],
    "liczba mieszana": [
        "1¾ = 1 + 3/4",
        "2½ kg mąki",
        "zamień: 7/3 = 2⅓",
        "3 1/5 metra",
        "odczytaj 4⅖",
    ],
    "ułamki równe": [
        "1/2 = 2/4",
        "3/6 = 1/2",
        "2/3 = 4/6",
        "5/10 = 1/2",
        "te same części",
    ],
    "skracanie": [
        "6/8 → 3/4",
        "10/15 → 2/3",
        " przez NWD",
        "12/18 → 2/3",
        "najprostsza postać",
    ],
    "rozszerzanie": [
        "1/3 → 2/6",
        "2/5 → 6/15",
        "× ten sam na górę i dół",
        "3/4 → 9/12",
        "wspólny mianownik",
    ],
    "ułamek nieskracalny": [
        "3/4 ✔ nieskracalny",
        "6/8 ✖ skracaj",
        "NWD(3,4)=1",
        "2/9 ✔",
        "w odpowiedzi skróć",
    ],
    "wspólny mianownik": [
        "1/3 i 1/4 → /12",
        "NWW mianowników",
        "2/5 i 3/10 → /10",
        "1/2 + 1/3: /6",
        "sprowadź do wspólnego",
    ],
    "ułamek = dzielenie": [
        "3/4 = 3:4",
        "1/2 = 1:2",
        "7/8 = 7:8",
        "dzielenie → ułamek",
        "5:8 = 5/8",
    ],
    "ułamek dziesiętny": [
        "0,5 = ½",
        "1,25 zł",
        "3,14 ≈ π",
        "0,75 = ¾",
        "2 miejsca po przecinku",
    ],
    "miejsca po przecinku": [
        "12,5 — 1 miejsce",
        "0,025 — 3 miejsca",
        "3,141 — trzy",
        "dopełnij zerem: 4,50",
        "przecinek dziesiątkowy",
    ],
    "równoważność": [
        "0,5 = 1/2",
        "0,25 = 1/4",
        "¾ = 0,75",
        "te same wartości",
        "1/5 = 0,2",
    ],
    "zamiana na zwykły": [
        "0,5 → 1/2",
        "0,25 → 1/4",
        "1,5 → 3/2",
        "0,125 → 1/8",
        "2,75 → 11/4",
    ],
    "+/− ten sam mianownik": [
        "2/7 + 3/7 = 5/7",
        "5/9 − 2/9 = 3/9",
        "liczniki ±, mian. bez zm.",
        "1/4 + 2/4 = 3/4",
        "4/5 − 1/5 = 3/5",
    ],
    "różne mianowniki": [
        "1/2 + 1/3 = 5/6",
        "3/4 − 1/6 = 7/12",
        "NWW mianowników",
        "2/3 + 1/4 = 11/12",
        "sprowadź, potem ±",
    ],
    "odwrotność": [
        "2/3 ↔ 3/2",
        "5 ↔ 1/5",
        "a · 1/a = 1",
        "4/7 · 7/4 = 1",
        "odwrotność × = 1",
    ],
    "skracanie przed ×": [
        "4/9 · 3/8 → skróć 3",
        "skracaj w przekątnej",
        "6/15 · 5/12",
        "upraszczaj wcześniej",
        "2/5 · 5/8 = 2/8",
    ],
    "ułamek liczby": [
        "½ z 20 = 10",
        "¾ · 24 = 18",
        "2/5 z 35 = 14",
        "1/3 · 45 = ?",
        "oblicz część",
    ],
    "przykład: część z całości": [
        "¼ z 60 = 15",
        "⅓ z 21 = 7",
        "2/5 z 40 = 16",
        "¾ z 80 = ?",
        "× ułamek · liczba",
    ],
    "całość z części": [
        "15 to ¼ → 60",
        "12 to ⅓ → 36",
        "część : ułamek",
        "20 to ½ → 40",
        "znajdź całość",
    ],
    "powiększenie o część": [
        "100 + ¼·100 = 125",
        "80 + 20% = 96",
        "powiększ o 1/5",
        "50 + 10 = 60 (+20%)",
        "nowa wartość większa",
    ],
    "pomniejszenie o część": [
        "100 − ¼·100 = 75",
        "80 − 20% = 64",
        "pomniejsz o 1/5",
        "60 − 15 = 45 (−25%)",
        "nowa wartość mniejsza",
    ],
    "procent": [
        "50% = ½",
        "25% = ¼",
        "100% = całość",
        "1% = 1/100",
        "20% z 200 = 40",
    ],
    "procent z liczby": [
        "20% z 150 = 30",
        "15% z 80 = 12",
        "× i podziel przez 100",
        "10% z 250 = 25",
        "5% z 400 = 20",
    ],
    "zwiększenie o p%": [
        "100 + 10% = 110",
        "200 + 25% = 250",
        "× (1 + p/100)",
        "cena + VAT",
        "80 + 15% = 92",
    ],
    "zmniejszenie o p%": [
        "100 − 20% = 80",
        "150 − 10% = 135",
        "× (1 − p/100)",
        "promocja −30%",
        "200 − 25% = 150",
    ],
    "zamiany": [
        "0,5 = 50% = ½",
        "¼ = 25% = 0,25",
        "1/5 = 20%",
        "75% = 0,75 = ¾",
        "100% = 1 = całość",
    ],
    "p% z liczby": [
        "30% z 90 = 27",
        "12% z 250 = 30",
        "liczba · p/100",
        "8% z 500 = 40",
        "oblicz procent liczby",
    ],
    "jaki procent?": [
        "15 z 60 = 25%",
        "8 z 32 = 25%",
        "część:całość · 100%",
        "20 z 80 = ?%",
        "ile to procent?",
    ],
    "liczba z procentu": [
        "25% to 20 → 80",
        "10% to 7 → 70",
        "część:p = całość",
        "30% to 45 → ?",
        "znajdź liczbę",
    ],
    "zwiększenie / zmniejszenie": [
        "+10% potem −10% ≠ start",
        "100→110→99",
        "dwie zmiany procent.",
        "promocja i podwyżka",
        "ostateczna cena?",
    ],
    "podwójna zmiana": [
        "100 +20% −20% = 96",
        "200 −10% +10% = 198",
        "kolejność ma znaczenie",
        "dwa rabaty",
        "oblicz końcową wartość",
    ],
    "w zadaniach": [
        "sklep: cena i rabat",
        "ankieta: ile procent?",
        "mapa: skala i odległość",
        "przepis: podwój porcję",
        "czytaj uważnie treść",
    ],
    "proporcjonalność prosta": [
        "2 kg → 10 zł, 5 kg → ?",
        "więcej → więcej",
        "v stałe: s i t",
        "3 cuk. = 6 zł, 7 = ?",
        "tabela rośnie równo",
    ],
    "współczynnik": [
        "k = y/x",
        "2:1 współczynnik",
        "cena za 1 kg",
        "k = 5 zł/kg",
        "stała proporcja k",
    ],
    "wykres": [
        "prosta przez (0,0)",
        "odczytaj y dla x=3",
        "kropki w linii",
        "wykres v(t)",
        "ruch po prostej",
    ],
    "tabela wartości": [
        "x: 1, 2, 3, 4",
        "y: 3, 6, 9, 12",
        "×3 w każdym wierszu",
        "uzupełnij brakujące",
        "sprawdź proporcję",
    ],
    "proporcja": [
        "2/3 = 4/6",
        "a/b = c/d",
        "3/5 = x/20",
        "środkowe iloczyny",
        "4/9 = 8/?",
    ],
    "podział proporcjonalny": [
        "60 zł w st. 2:3",
        "24: 2 cz. + 3 cz.",
        "podziel wg stosunku",
        "100 w 1:4 → 20 i 80",
        "suma części = całość",
    ],
    "stosunek": [
        "2:3 stosunek",
        "5:1 w przepisie",
        "a:b skróć",
        "12:8 = 3:2",
        "porównaj ilości",
    ],
    "trzy osoby": [
        "A:B:C = 2:3:5",
        "900 zł na troje",
        "2+3+5 = 10 cz.",
        "podziel 120 wg 1:2:3",
        "ile dostanie B?",
    ],
    "związek z proporcją": [
        "2/3 = 4/x",
        "stosunek → ułamek",
        "a:b = c:d",
        "3:5 = 12:20",
        "proporcja ze stosunku",
    ],
    "wyrażenie algebraiczne": [
        "2x + 5",
        "3a − 7b",
        "x² + 2x",
        "zapis z literą",
        "oblicz dla x=4",
    ],
    "elementy": [
        "2x: wyraz, współcz. 2",
        "−3y: znak, współcz., litera",
        "7 — wyraz wolny",
        "wyróżnij wyrazy",
        "3a²b — jednomian",
    ],
    "zmienna": [
        "x — niewiadoma",
        "n — numer kolejny",
        "t — czas",
        "litera zamiast liczby",
        "x może być różne",
    ],
    "wartość liczbowa": [
        "2x+3 dla x=5 → 13",
        "a² dla a=4 → 16",
        "podstaw i policz",
        "x=−2 → wynik?",
        "sprawdź w zadaniu",
    ],
    "zapis skrócony": [
        "3·x = 3x",
        "1·a = a",
        "5·x·y = 5xy",
        "−1·b = −b",
        "× pomijamy",
    ],
    "kolejność": [
        "2x+3x = 5x",
        "najpierw × potem +",
        "3(x+2) przed +",
        "kolejność działań",
        "nawiasy pierwsze",
    ],
    "jednomian": [
        "5x — jednomian",
        "−3a²b",
        "7 — jednomian stały",
        "współcz. × zmienne",
        "4xy²",
    ],
    "suma algebraiczna": [
        "2x + 3y − 5",
        "a + b + c",
        "wyrazy oddzielone +/−",
        "x² + x + 1",
        "policz wyrazy",
    ],
    "wyrazy podobne": [
        "2x i 5x — podobne",
        "3x i 3y — nie",
        "7a² i −2a²",
        "te same litery",
        "grupuj podobne",
    ],
    "redukcja": [
        "2x+5x = 7x",
        "8a − 3a = 5a",
        "3x+2+4x = 7x+2",
        "łącz podobne",
        "upraszczaj wyrażenie",
    ],
    "jednomian × suma": [
        "3(x+2) = 3x+6",
        "a(b+c) = ab+ac",
        "−2(4−x) = −8+2x",
        "mnoż przez każdy",
        "5(2a+3) = ?",
    ],
    "dwumian × dwumian": [
        "(x+2)(x+3)",
        "mnoż każdy×każdy",
        "(a+1)(a−1)",
        "(2x+1)(x+4)",
        "4 iloczyny",
    ],
    "metoda kolejności": [
        "najpierw × w nawiasie",
        "potem redukcja",
        "krok 1: ×, krok 2: +",
        "3(2x+1)+4x",
        "upraszczaj etapami",
    ],
    "znaki minus": [
        "−(x+3) = −x−3",
        "−(−5) = 5",
        "−2(x−1) = −2x+2",
        "minus przed ( )",
        "zmień znaki w nawiasie",
    ],
    "sprawdzenie": [
        "podstaw x=3 do równania",
        "L = P?",
        "czy 7=7 ✔",
        "sprawdź w zeszyt",
        "wstaw do wzoru",
    ],
    "równanie": [
        "x + 5 = 12",
        "2x = 14",
        "3x − 7 = 8",
        "znajdź x",
        "L = P",
    ],
    "niewiadoma": [
        "x — szukana liczba",
        "? w równaniu",
        "n w zadaniu",
        "jedna niewiadoma",
        "oznacz literą",
    ],
    "rozwiązanie": [
        "x = 7 ✔",
        "x = −3",
        "sprawdź podstawieniem",
        "zbiór: {5}",
        "ile rozwiązań?",
    ],
    "metoda bilansowania": [
        "x+5=12: −5 obie",
        "2x=10: :2 obie",
        "równowaga szali",
        "to samo po obu str.",
        "x+3=3+x",
    ],
    "przenoszenie": [
        "x+5=12 → x=7",
        "3x=15 → x=5",
        "−2x=8 → x=−4",
        "przenieś na drugą str.",
        "zmień znak przy +/−",
    ],
    "figury wokół nas": [
        "okno — prostokąt",
        "znak drogowy — trójk.",
        "talerz — koło",
        "płytki — kwadraty",
        "narysuj i nazwij",
    ],
    "punkt": [
        "zaznacz A",
        "• — punkt",
        "A, B, C — nazwy",
        "punkt ma położenie",
        "przecięcie linii",
    ],
    "prosta": [
        "linia bez końca",
        "↔ prosta AB",
        "równoległe proste",
        "proste prostopadłe",
        "narysuj prostą",
    ],
    "odcinek": [
        "AB — odcinek",
        "ma początek i koniec",
        "|AB| = 5 cm",
        "najkrótsza droga",
        "zmierz odcinek",
    ],
    "półprosta": [
        "promień od A",
        "→ jeden koniec",
        "półprosta AB",
        "w jedną stronę",
        "początek w A",
    ],
    "łamana": [
        "A→B→C→D",
        "kilka odcinków",
        "łamana zamknięta",
        "obwód łamanej",
        "łama się w wierzch.",
    ],
    "wielokąt": [
        "trójkąt, kwadrat",
        "5-kąt, 6-kąt",
        "wierzchołki i boki",
        "wielokąt foremny",
        "narysuj 4-kąt",
    ],
    "trójkąt": [
        "Δ ABC",
        "3 boki, 3 kąty",
        "suma kątów = 180°",
        "trójkąt równoram.",
        "oblicz trzeci kąt",
    ],
    "rodzaje trójkątów": [
        "równoboczny: 3×60°",
        "równoramienny",
        "różnoboczny",
        "ostrokątny",
        "prostokątny",
    ],
    "kwadrat": [
        "4 równe boki",
        "4 proste kąty",
        "P = a²",
        "O = 4a",
        "przekątne ⊥",
    ],
    "prostokąt": [
        "przeciwne równe",
        "4 kąty proste",
        "P = a·b",
        "O = 2(a+b)",
        "drzwi — prostokąt",
    ],
    "romb / równoległobok": [
        "romb: 4 równe boki",
        "równoległobok: a||c",
        "P = a·h",
        "przeciwne równoległe",
        "romb to równoległ.",
    ],
    "trapez": [
        "1 para || boków",
        "P = (a+b)/2 · h",
        "ramiona trapezu",
        "równoramienny trapez",
        "odczytaj podstawy",
    ],
    "proste prostopadłe": [
        "⊥ — prostopadłe",
        "kąt 90°",
        "⊥ przy przecięciu",
        "narysuj z kątomierzem",
        "AB ⊥ CD",
    ],
    "odcinki prostopadłe": [
        "odcinek ⊥ prostej",
        "najkrótsza odległość",
        "⊥ z punktu na prostą",
        "stopka prostopadłej",
        "h ⊥ podstawę",
    ],
    "odległość punktu od prostej": [
        "najkrótsza ⊥",
        "odległość = d",
        "zmierz prostopadle",
        "h w trójkącie",
        "punkt P, prosta k",
    ],
    "wysokość w figurze": [
        "h ⊥ podstawa",
        "P = a·h/2 trójk.",
        "narysuj wysokość",
        "h w trapezie",
        "odległość boków ||",
    ],
    "w życiu": [
        "sklep: reszta z 20 zł",
        "boisko: obwód",
        "przepis: ½ szklanki",
        "mapa: skala 1:50000",
        "temperatura −3°C",
    ],
    "kąt": [
        "∠ABC — wierzchołek B",
        "miara w stopniach",
        "∠ = 45°",
        "narysuj kąt 60°",
        "ramiona kąta",
    ],
    "wierzchołek": [
        "B w ∠ABC",
        "wspólny punkt ramion",
        "wierzchołek trójk.",
        "oznacz literą",
        "kąt w wierzchołku",
    ],
    "ramiona / strony": [
        "BA i BC — ramiona",
        "boki trójkąta",
        "ramiona kąta",
        "strony wielokąta",
        "narysuj oba ramiona",
    ],
    "miara kąta": [
        "∠ = 90°",
        "45°, 60°, 120°",
        "odczytaj z rysunku",
        "zmierz kątomierzem",
        "suma kątów trójk. 180°",
    ],
    "kątomierz": [
        "zmierz ∠ na rysunku",
        "odczytaj 35°",
        "narysuj kąt 120°",
        "skala 0°–180°",
        "przyłóż środek",
    ],
    "półobrót / obrót": [
        "180° = półobrót",
        "360° = pełny",
        "obróć o 90°",
        "obrót wokół O",
        "kąt pełny = 360°",
    ],
    "kąt zerowy": [
        "0° — ramiona na siebie",
        "kąt zerowy ∠",
        "brak rozwarcia",
        "te same półproste",
        "0° na kątomierzu",
    ],
    "kąt ostry": [
        "0° < ∠ < 90°",
        "45° ✔ ostry",
        "30°, 60° ostre",
        "89° ostry",
        "90° ✖ nie ostry",
    ],
    "kąt prosty": [
        "∠ = 90°",
        "symbol □ w wierzch.",
        "kąt prosty ✔",
        "narożnik stołu",
        "⊥ → kąt prosty",
    ],
    "kąt rozwarty": [
        "90° < ∠ < 180°",
        "120° ✔ rozwarty",
        "100°, 150°",
        "89° ✖",
        "otwarty rozwarcie",
    ],
    "kąt półpełny": [
        "∠ = 180°",
        "półobrót",
        "prosta — 180°",
        "ramiona przeciwne",
        "półpełny kąt",
    ],
    "kąt pełny": [
        "∠ = 360°",
        "pełny obrót",
        "zamknij okrąg",
        "360° w jednym obrocie",
        "pełny kąt",
    ],
    "proste równoległe": [
        "∥ — równoległe",
        "a ∥ b",
        "tory kolejowe ∥",
        "nie przecinają się",
        "narysuj dwie ∥",
    ],
    "sieczna": [
        "prosta przecina ∥",
        "sieczna t",
        "8 kątów przy ∥",
        "t przecina a i b",
        "oznacz kąty",
    ],
    "kąty odpowiadające": [
        "przy ∥ i siecznej",
        "∠1 = ∠5",
        "te same położenie",
        "znajdź ∠ gdy ∠=70°",
        "odpowiadające =",
    ],
    "naprzemianległe": [
        "∠ wewn. naprzem.",
        "∠3 = ∠6",
        "między ∥ a sieczną",
        "znajdź drugi kąt",
        "naprzemianległe =",
    ],
    "przyległe": [
        "∠1 + ∠2 = 180°",
        "wspólne ramię",
        "∠ przyległe",
        "suplement — 180°",
        "oblicz drugi kąt",
    ],
    "wierzchołkowe": [
        "∠1 = ∠3",
        "przy wspólnym wierzch.",
        "wierzchołkowe =",
        "x = 50° → drugi?",
        "naprzeciwko wierzch.",
    ],
    "twierdzenie": [
        "∠ odp. = przy ∥",
        "Pitagoras: a²+b²=c²",
        "suma kątów = 180°",
        "użyj twierdzenia",
        "dowód w zadaniu",
    ],
    "obliczanie trzeciego": [
        "60°+70°+? = 180°",
        "trzeci kąt = 50°",
        "180° − suma dwóch",
        "45°+90°+x=180°",
        "Δ: dwa kąty → trzeci",
    ],
    "trójkąt prostokątny": [
        "kąt prosty 90°",
        "przyprostokątne a, b",
        "przeciwprostokątna c",
        "Δ ABC, ∠C=90°",
        "Pitagoras tu działa",
    ],
    "równoramienny": [
        "2 boki równe",
        "kąty przy podstawie =",
        "∠ przy wierzchołku",
        "oś symetrii",
        "AB = AC",
    ],
    "nierówność trójkąta": [
        "3+4 > 5 ✔",
        "1+2 > 3? ✖",
        "suma 2 boków > 3.",
        "czy z 3,4,8 powstanie Δ?",
        "2+5 > 6 ✔",
    ],
    "okrąg": [
        "kreska — obwód",
        "O = środek",
        "r — promień",
        "narysuj cyrklem",
        "okrąg na rysunku",
    ],
    "koło": [
        "okrąg + wnętrze",
        "pole koła πr²",
        "talerz — koło",
        "wypełniony dysk",
        "r = 3 cm",
    ],
    "środek": [
        "O — środek koła",
        "równe odległości",
        "zaznacz O",
        "O na osi symetrii",
        "środek okręgu",
    ],
    "promień": [
        "r = 5 cm",
        "O do brzegu",
        "2r = średnica",
        "narysuj promień",
        "r w wzorze πr²",
    ],
    "średnica": [
        "d = 2r",
        "przez środek O",
        "najdłuższa cięciwa",
        "d = 10 cm, r = ?",
        "średnica ⊥ styczna",
    ],
    "cięciwa": [
        "łączy 2 punkty koła",
        "d — najdłuższa cięciwa",
        "cięciwa AB",
        "nie przechodzi przez O",
        "oblicz długość",
    ],
    "liczba π": [
        "π ≈ 3,14",
        "C = 2πr",
        "P = πr²",
        "π ≈ 22/7",
        "obwód/d = π",
    ],
    "długość okręgu": [
        "C = 2πr",
        "r=5 → C≈31,4",
        "C = πd",
        "oblicz obwód",
        "koło r=3 cm",
    ],
    "pole koła": [
        "P = πr²",
        "r=2 → P≈12,56",
        "P = π(d/2)²",
        "pole dysku",
        "r=10 → P=100π",
    ],
    "przykład c": [
        "r=7 → C=14π",
        "C=2π·5=10π",
        "d=6 → C=6π",
        "oblicz C dla r=4",
        "C ≈ 31,4 przy r=5",
    ],
    "przykład p": [
        "r=3 → P=9π",
        "P=π·4²=16π",
        "r=5 → P=25π",
        "oblicz P koła",
        "P ≈ 78,5 przy r=5",
    ],
    "zależność": [
        "r↑ → C↑ i P↑",
        "2×r → 4×P",
        "C = 2πr",
        "P = πr²",
        "tabela r, C, P",
    ],
    "obwód": [
        "O = 2(a+b)",
        "O = 4a kwadrat",
        "dookoła figury",
        "O trójkąta: suma boków",
        "zmierz i dodaj",
    ],
    "pole": [
        "P = a·b prostokąt",
        "P = a² kwadrat",
        "ile w środku?",
        "P = πr² koło",
        "cm², m²",
    ],
    "równoległobok": [
        "przeciwne || i =",
        "P = a·h",
        "a jako podstawa",
        "narysuj równoległ.",
        "h ⊥ podstawę",
    ],
    "pole rombu": [
        "P = a·h",
        "P = (d₁·d₂)/2",
        "przekątne rombu",
        "a=6, h=4 → P=24",
        "romb — 4 równe boki",
    ],
    "pole trapezu": [
        "P = (a+b)/2 · h",
        "a, b — podstawy",
        "h między podstawami",
        "a=5, b=9, h=4",
        "P = 28",
    ],
    "ar": [
        "1 ar = 100 m²",
        "pole działki w ar",
        "2,5 ar = 250 m²",
        "ogród 10 ar",
        "ar na wsi",
    ],
    "hektar": [
        "1 ha = 100 ar",
        "1 ha = 10000 m²",
        "pole 3 ha",
        "las 500 ha",
        "ha w mapach",
    ],
    "zamiana jednostek pola": [
        "1 m² = 10000 cm²",
        "2 ha = 200 ar",
        "5000 m² = 0,5 ha",
        "3 ar = 300 m²",
        "przelicz cm²↔m²",
    ],
    "symetria": [
        "lustrzane odbicie",
        "figura = obraz",
        "motyl — symetria",
        "oś symetrii",
        "złóż wzdłuż osi",
    ],
    "oś symetrii": [
        "linia lustrzanego odb.",
        "2 osie kwadratu",
        "1 oś trójkąta równ.",
        "narysuj oś",
        "figura po obu stronach",
    ],
    "środek symetrii": [
        "punkt O — środek",
        "180° obrót wokół O",
        "przeciwne punkty",
        "O w równoległoboku",
        "środek symetrii figury",
    ],
    "rysowanie": [
        "narysuj oś symetrii",
        "odbij punkt A",
        "cyrkiel i linijka",
        "symetralna odcinka",
        "krok po kroku w zeszycie",
    ],
    "w przyrodzie": [
        "motyl — symetria",
        "liść — oś symetrii",
        "płatki kwiatu",
        "snieżynka",
        "twarz — prawie symet.",
    ],
    "symetralna odcinka": [
        "⊥ w połowie odcinka",
        "równo odległa od A,B",
        "narysuj symetralną",
        "punkt P: PA = PB",
        "środek + prostopadła",
    ],
    "własność symetralnej": [
        "PA = PB na symetr.",
        "każdy punkt równo daleko",
        "P na symetralnej",
        "odległości do końców =",
        "własność w zadaniu",
    ],
    "dwusieczna kąta": [
        "dzieli kąt na 2 =",
        "∠1 = ∠2",
        "narysuj dwusieczną",
        "punkt równo od ramion",
        "∠60° → 2×30°",
    ],
    "własność dwusiecznej": [
        "P równo od ramion",
        "PA = PB",
        "P na dwusiecznej",
        "odległość do ramion =",
        "w trójkącie — własność",
    ],
    "w trójkącie": [
        "symetralne — w środku O",
        "dwusieczne — wspólny punkt",
        "h, środkowa, dwusieczna",
        "Pitagoras w Δ prost.",
        "suma kątów 180°",
    ],
    "układ współrzędnych": [
        "oś X i Y",
        "punkt (3, 2)",
        "kratka milimetrowa",
        "mapa kratkowa",
        "początek (0,0)",
    ],
    "oś x": [
        "pozioma →",
        "x = 3 na osi",
        "odczytaj x punktu",
        "oś abscys",
        "w prawo dodatnie",
    ],
    "oś y": [
        "pionowa ↑",
        "y = 4 na osi",
        "odczytaj y punktu",
        "oś ordynat",
        "w górę dodatnie",
    ],
    "punkt (x, y)": [
        "A(3, 5)",
        "najpierw x, potem y",
        "zaznacz (2, −1)",
        "odczytaj współrz.",
        "B(−4, 2)",
    ],
    "ćwiartki": [
        "I: (+,+)",
        "II: (−,+)",
        "III: (−,−)",
        "IV: (+,−)",
        "w której ćwiartce?",
    ],
    "początek układu": [
        "O(0, 0)",
        "przecięcie osi",
        "zero na obu osiach",
        "punkt startowy",
        "(0,0) — początek",
    ],
    "środek odcinka": [
        "M = ((x₁+x₂)/2, …)",
        "A(2,4) B(6,8) → M(4,6)",
        "połowa drogi",
        "środek AB",
        "oblicz M",
    ],
    "długość odcinka": [
        "|AB| = √((x₂−x₁)²+…)",
        "A(0,0) B(3,4) → 5",
        "odległość w układzie",
        "Pitagoras na kratce",
        "zmierz na kratce",
    ],
    "drugi koniec": [
        "M(3,4), A(1,2) → B=?",
        "znajdź B gdy znasz A,M",
        "symetria względem M",
        "B = 2M − A",
        "drugi koniec odcinka",
    ],
    "punkty kratowe": [
        "całkowite x i y",
        "(2, 3) kratowy",
        "licz punkty w figurze",
        "obwód na kratce",
        "pole na kratce",
    ],
    "przystawanie": [
        "Δ ABC ≅ Δ DEF",
        "BBB, BKB, KBK",
        "figury identyczne",
        "przesuń i nałóż",
        "cecha przystawania",
    ],
    "cecha bbb": [
        "3 boki = → Δ ≅",
        "5=5, 7=7, 9=9",
        "BBB w zadaniu",
        "porównaj boki",
        "trzy pary równych",
    ],
    "cecha bkb": [
        "2 boki i kąt między",
        "BKB → Δ ≅",
        "bok-kąt-bok",
        "kąt między bokami",
        "2 pary boków + kąt",
    ],
    "cecha kbk": [
        "2 kąty i bok między",
        "KBK → Δ ≅",
        "kąt-bok-kąt",
        "∠=∠, bok, ∠=∠",
        "2 pary kątów + bok",
    ],
    "po co to?": [
        "dowód w geometrii",
        "figury równe",
        "oblicz brakujący bok",
        "Δ ≅ → kąty =",
        "użyj cechy",
    ],
    "twierdzenie pitagorasa": [
        "a²+b²=c²",
        "c — przeciwprost.",
        "3²+4²=5²",
        "oblicz brakujący bok",
        "tylko Δ prostokątny",
    ],
    "przyprostokątne i przeciwprostokątna": [
        "a, b — przyprost.",
        "c — najdłuższy",
        "przy kącie prostym",
        "c² = a²+b²",
        "oznacz na rysunku",
    ],
    "obliczanie przeciwprostokątnej": [
        "a=3, b=4 → c=5",
        "c = √(a²+b²)",
        "6 i 8 → c=10",
        "c = √25 = 5",
        "najdłuższy bok",
    ],
    "obliczanie przyprostokątnej": [
        "c=5, a=3 → b=4",
        "b = √(c²−a²)",
        "c=13, b=5 → a=12",
        "krótszy bok",
        "a² = c²−b²",
    ],
    "trójki pitagorejskie": [
        "3, 4, 5",
        "5, 12, 13",
        "8, 15, 17",
        "6, 8, 10",
        "sprawdź a²+b²=c²",
    ],
    "bryła": [
        "sześcian, prostopadł.",
        "ma objętość",
        "3 wymiary",
        "siatka bryły",
        "kostka — sześcian",
    ],
    "sześcian": [
        "6 równych ścian",
        "V = a³",
        "kostka do gry",
        "a = 3 cm",
        "12 krawędzi =",
    ],
    "prostopadłościan": [
        "6 prostokątnych ścian",
        "V = a·b·c",
        "pudełko",
        "3 różne wymiary",
        "karton — prostopadł.",
    ],
    "ostrosłup": [
        "podstawa + ściany boczne",
        "wierzchołek W",
        "ostrosłup czworokątny",
        "V = ⅓·P_p·h",
        "siatka ostrosłupa",
    ],
    "walec / stożek / kula": [
        "puszka — walec",
        "czapka — stożek",
        "piłka — kula",
        "która bryła?",
        "walec ≠ stożek ≠ kula",
    ],
    "objętość sześcianu": [
        "V = a³",
        "a=4 → V=64",
        "V = a·a·a",
        "kostka 2 cm",
        "V w cm³",
    ],
    "graniastosłup": [
        "2 równoległe podstawy",
        "V = P_p · h",
        "prosty graniastosłup",
        "pryzmat trójkątny",
        "6 ścian prostokątnych",
    ],
    "graniastosłup prosty": [
        "krawędzie ⊥ podstawy",
        "h = wysokość",
        "V = P_p · h",
        "prostopadłe boki",
        "narysuj prosty graniast.",
    ],
    "siatka bryły": [
        "rozpłaszczona bryła",
        "złóż siatkę",
        "oblicz pole siatki",
        "siatka sześcianu",
        "6 kwadratów",
    ],
    "pole powierzchni": [
        "suma pól ścian",
        "P = 2(ab+ac+bc)",
        "prostopadłościan",
        "cm² powierzchni",
        "ile farby na pudełko?",
    ],
    "objętość graniastosłupa": [
        "V = P_p · h",
        "P_p=12, h=5 → V=60",
        "podstawa × wysokość",
        "V w cm³",
        "prostopadłościan V=abc",
    ],
    "ostrosłup — przypomnienie": [
        "V = ⅓ P_p h",
        "wierzchołek nad środkiem",
        "h prostopadle do P_p",
        "ostrosłup prawidłowy",
        "siatka: podstawa + △",
    ],
    "jednostki długości": [
        "mm, cm, dm, m, km",
        "linijka — cm",
        "1 m = 100 cm",
        "5 km do szkoły",
        "długość w metrach",
    ],
    "zamiana": [
        "150 cm = 1,5 m",
        "3 km = 3000 m",
        "25 mm = 2,5 cm",
        "przelicz jednostki",
        "×10 lub ÷10",
    ],
    "mierzenie": [
        "linijka: 8 cm",
        "miara taśmą",
        "zapisz z jednostką",
        "zmierz bok",
        "obwód zmierz i dodaj",
    ],
    "obwód a długość": [
        "obwód = suma boków",
        "długość odcinka",
        "O kwadratu = 4a",
        "C koła = 2πr",
        "dookoła vs w linii",
    ],
    "jednostki masy": [
        "mg, g, dag, kg, t",
        "waga w kg",
        "1 kg = 1000 g",
        "500 g mąki",
        "masa w gramach",
    ],
    "ważenie": [
        "waga: 2,5 kg",
        "szalki wagi",
        "porównaj masy",
        "250 g + 750 g",
        "waż jabłka",
    ],
    "objętość": [
        "V = a·b·c",
        "V w cm³ lub l",
        "ile mieści się?",
        "3 wymiary",
        "objętość bryły",
    ],
    "litr": [
        "1 l soku",
        "butelka 1,5 l",
        "1 l = 1 dm³",
        "miarka 2 l",
        "litr w kuchni",
    ],
    "mililitr": [
        "500 ml wody",
        "1 ml = 1 cm³",
        "1000 ml = 1 l",
        "łyżka ≈ 15 ml",
        "ml w aptece",
    ],
    "przeliczanie": [
        "2 l = 2000 ml",
        "500 ml = 0,5 l",
        "3 dm³ = 3 l",
        "×1000 ml↔l",
        "250 ml + 750 ml",
    ],
    "objętość bryły": [
        "V = a³ sześcian",
        "V = abc prostopadł.",
        "V = ⅓P_p h ostrosłup",
        "V w cm³",
        "ile kostek w pudełku?",
    ],
    "jednostki czasu": [
        "s, min, h",
        "45 min lekcja",
        "1 h = 60 min",
        "3 h podróży",
        "sekundy na stoperze",
    ],
    "zegar": [
        "odczytaj 3:45",
        "zegar analogowy",
        "15:30 = pół do 4",
        "za 20 min która?",
        "zegar cyfrowy",
    ],
    "upływ czasu": [
        "8:00 → 8:45 = 45 min",
        "1 h 20 min",
        "ile minut przerwa?",
        "od 9:15 do 10:00",
        "oblicz różnicę czasu",
    ],
    "doba": [
        "24 h = 1 doba",
        "7:00 rano — start",
        "22:00 wieczorem",
        "pełna doba",
        "2 doby = 48 h",
    ],
    "przykład dłuższy": [
        "8:20 → 11:05 = 2h45m",
        "3 dni 5 h = ? h",
        "film 2h 15min",
        "podróż 5h 30min",
        "suma czasów",
    ],
    "jednostki kalendarzowe": [
        "dzień, tydzień, miesiąc",
        "7 dni = tydzień",
        "12 miesięcy = rok",
        "365 dni w roku",
        "pon–nd — tydzień",
    ],
    "data": [
        "28.07.2026",
        "dzień.miesiąc.rok",
        "data urodzin",
        "który dziś dzień?",
        "zapisz datę",
    ],
    "urodziny i święta": [
        "15.03 — urodziny",
        "24.12 — Wigilia",
        "11.11 — święto",
        "ile dni do…?",
        "kalendarz szkolny",
    ],
    "rok przestępny": [
        "366 dni",
        "luty ma 29 dni",
        "co 4 lata",
        "2024 ✔ przestępny",
        "2025 ✖ zwykły",
    ],
    "miesiące": [
        "styczeń–grudzień",
        "31, 28/29, 31, …",
        "luty — najkrótszy",
        "4 miesiące = kwiecień",
        "30 dni w kwietniu",
    ],
    "kolejność dni": [
        "pon, wt, śr, czw",
        "po środzie — czwartek",
        "7 dni tygodnia",
        "wczoraj, dziś, jutro",
        "trzeci dzień tygodnia",
    ],
    "stopień celsjusza": [
        "20°C ciepło",
        "−5°C mróz",
        "°C na termometrze",
        "+15°C wiosna",
        "0°C — lód",
    ],
    "termometr": [
        "odczytaj +18°C",
        "rtęć wzrasta",
        "−3°C na termometrze",
        "temperatura ciała 36,6°C",
        "zmierz temperaturę",
    ],
    "powyżej / poniżej zera": [
        "+5°C powyżej 0",
        "−8°C poniżej 0",
        "−2 < 0 < 3",
        "mróz poniżej zera",
        "dodatnia temp.",
    ],
    "różnica temperatur": [
        "+20°C i −5°C → 25°",
        "8°C → 15°C = +7°",
        "oblicz różnicę |t₁−t₂|",
        "−3°C i +7°C",
        "o ile cieplej?",
    ],
    "złoty i grosz": [
        "1 zł = 100 gr",
        "5,50 zł",
        "2 zł 30 gr",
        "47 gr reszty",
        "zł + grosze",
    ],
    "5 zł na bułkę": [
        "bułka 2,50 zł",
        "reszta 2,50 zł",
        "10 zł − 2,50 zł",
        "czy starczy 5 zł?",
        "ile kosztuje?",
    ],
    "dodawanie / odejmowanie": [
        "3,50 + 2,20 = 5,70",
        "10 − 4,80 = 5,20",
        "suma paragonu",
        "reszta z 20 zł",
        "pieniądze w zadaniu",
    ],
    "reszta": [
        "10 zł − 3,60 = 6,40",
        "reszta z 50 zł",
        "ile odda kasjer?",
        "20 − 14,75 = ?",
        "sprawdź resztę",
    ],
    "porównywanie cen": [
        "2,99 vs 3,49 zł",
        "która tańsza?",
        "A tańsza o 50 gr",
        "porównaj promocje",
        "taniej o 1,20 zł",
    ],
    "budżet": [
        "20 zł na zakupy",
        "czy starczy na 3 rzeczy?",
        "plan wydatków",
        "15 + 8 > 20 ✖",
        "ile zostanie?",
    ],
    "prędkość": [
        "v = s/t",
        "60 km/h",
        "szybciej = większe v",
        "v w km/h lub m/s",
        "oblicz v",
    ],
    "jednostki": [
        "km/h, m/s",
        "km, m, cm",
        "kg, g",
        "h, min, s",
        "zapisz z jednostką",
    ],
    "droga i czas": [
        "s = v·t",
        "60 km/h × 2 h = 120 km",
        "t = s/v",
        "120 km w 2 h → v=?",
        "droga w zadaniu",
    ],
    "skala mapy": [
        "skala 1:50 000",
        "1 cm → 500 m",
        "2 cm na mapie → ?",
        "odczytaj skalę z mapy",
        "1:100 000 → 1 cm = 1 km",
    ],
    "obliczanie odległości": [
        "3 cm × 50000",
        "150 km na mapie",
        "skala × pomiar",
        "5 cm przy 1:200000",
        "realna odległość",
    ],
    "przykład v": [
        "s=120 km, t=2 h → v=60",
        "v = s/t",
        "90 km w 1,5 h",
        "v = 72 km/h",
        "oblicz prędkość",
    ],
    "wyrażenie dwumianowane": [
        "(a+b)² = a²+2ab+b²",
        "(x+3)²",
        "wzór skróconego mnożenia",
        "(2x−1)²",
        "rozwinięcie wzoru",
    ],
    "zamiana na mniejszą": [
        "2 km = 2000 m",
        "3 kg = 3000 g",
        "×1000 m→km odwrotnie",
        "1,5 m = 150 cm",
        "większa → mniejsza ×",
    ],
    "zamiana na większą": [
        "500 cm = 5 m",
        "2500 g = 2,5 kg",
        "÷1000 g→kg",
        "1500 ml = 1,5 l",
        "mniejsza → większa ÷",
    ],
    "i ułamek dziesiętny": [
        "1,5 m = 1½ m",
        "2,75 kg",
        "0,5 l = ½ l",
        "mieszane jednostki",
        "3,25 h = 3h 15min",
    ],
    "statystyka": [
        "ankieta w klasie",
        "zbierz dane",
        "tabela i wykres",
        "średnia, mediana",
        "opis zbioru danych",
    ],
    "dane": [
        "5, 8, 3, 8, 6",
        "wyniki testu",
        "ulubione kolory",
        "zbiór liczb",
        "zebrane w tabeli",
    ],
    "etapy": [
        "1. zbierz dane",
        "2. uporządkuj",
        "3. wykres",
        "4. oblicz średnią",
        "5. wnioski",
    ],
    "tabela": [
        "x | y",
        "1 | 3",
        "2 | 6",
        "odczytaj z tabeli",
        "uzupełnij brakujące",
    ],
    "wykres słupkowy": [
        "słupki — ilości",
        "odczytaj wartość",
        "porównaj słupki",
        "ankieta na wykresie",
        "oś pozioma — kategorie",
    ],
    "wykres kołowy": [
        "całość = 100%",
        "wycinek 25%",
        "proporcje w kole",
        "odczytaj udział",
        "podział na części",
    ],
    "średnia arytmetyczna": [
        "(5+8+3)/3 = 5,33",
        "suma : liczba",
        "średnia ocen",
        "x̄ = (a+b+c)/3",
        "oblicz średnią",
    ],
    "mediana": [
        "3,5,8 → med=5",
        "środkowa po sortowaniu",
        "4,7,7,9 → 7",
        "para: średnia dwóch",
        "mediana vs średnia",
    ],
    "moda": [
        "8,3,8,5 → moda=8",
        "najczęstsza wartość",
        "2 mody możliwe",
        "moda kolorów",
        "która najczęściej?",
    ],
    "przykład średniej": [
        "oceny 4,5,6 → 5",
        "(12+18+15)/3=15",
        "średnia temperatur",
        "x̄ = 7,5",
        "oblicz x̄",
    ],
    "przykład mediany": [
        "2,5,9 → med=5",
        "1,3,3,7 → 3",
        "6 wartości: średnia 3 i 4",
        "mediana pensji",
        "posortuj i znajdź",
    ],
    "przykład mody": [
        "A,A,B,C → moda A",
        "5,5,2,8,5 → 5",
        "ankieta: moda niebieski",
        "brak mody: 1,2,3",
        "najczęstszy wynik",
    ],
    "kombinatoryka": [
        "ile sposobów wyboru?",
        "menu: 3 zupy, 2 dania",
        "ubrania: 2 spodnie, 3 koszule",
        "licz możliwości",
        "diagram drzewa",
    ],
    "zasada mnożenia": [
        "3×4 = 12 sposobów",
        "2 bluzy × 3 spodnie",
        "mnoż liczby opcji",
        "5×2×3 = 30",
        "niezależne wybory",
    ],
    "zasada dodawania": [
        "3 lub 4 = 7 sposobów",
        "droga A albo B",
        "dodaj opcje wykluczające",
        "2+3+1 = 6",
        "albo… albo…",
    ],
    "prawdopodobieństwo": [
        "P = korzystne/wszystkie",
        "rzut kostką: P(6)=1/6",
        "0 ≤ P ≤ 1",
        "pewność P=1",
        "niemożliwe P=0",
    ],
    "+ plus / dodawanie": [
        "3 + 5 = 8",
        "plus łączy",
        "znak +",
        "dodaj składniki",
        "4+4+4 = 3×4",
    ],
    "− minus / odejmowanie": [
        "9 − 4 = 5",
        "minus odejmuje",
        "− temperatura",
        "7−3 = 4",
        "znak −",
    ],
    "× · mnożenie": [
        "4 × 3 = 12",
        "· też mnożenie",
        "2·5 = 10",
        "iloczyn",
        "× w zadaniu",
    ],
    ": / dzielenie": [
        "12 : 3 = 4",
        "/ też dzielenie",
        "8/2 = 4",
        "dziel po równo",
        "iloraz",
    ],
    "= < > ≤ ≥ ≠": [
        "5 = 5",
        "3 < 7",
        "10 ≥ 8",
        "4 ≠ 9",
        "≤ mniejsze lub równe",
    ],
    "= &lt; &gt; ≤ ≥ ≠": [
        "5 = 5",
        "3 < 7",
        "10 ≥ 8",
        "4 ≠ 9",
        "≤ mniejsze lub równe",
    ],
    "() [] √ ² % π ∠ ∥": [
        "(3+2)×4",
        "√16 = 4",
        "5² = 25",
        "20% = 0,2",
        "∠ABC, a∥b",
    ],
    "walec": [
        "puszka — walec",
        "2 podstawy koła",
        "V = πr²h",
        "h — wysokość",
        "siatka: 2○ + prost.",
    ],
    "podstawa walca": [
        "koło promienia r",
        "2 podstawy =",
        "P_p = πr²",
        "r podstawy",
        "obracaj trójkąt",
    ],
    "wysokość walca": [
        "h między podstawami",
        "h prostopadle",
        "V = πr²h",
        "h = 10 cm",
        "obrót wokół osi",
    ],
    "stożek": [
        "czapka — stożek",
        "rożek lodów — stożek",
        "1 podstawa: koło",
        "stożek ≠ walec",
        "wskaż wierzchołek",
    ],
    "podstawa stożka": [
        "koło r",
        "1 podstawa",
        "P_p = πr²",
        "r stożka",
        "leży płasko",
    ],
    "wierzchołek stożka": [
        "W — czubek",
        "h od W do P_p",
        "1 wierzchołek",
        "wierzchołek nad środkiem",
        "W w prawidłowym",
    ],
    "kula": [
        "piłka — to kula",
        "globus ≈ kula",
        "środek O, promień r",
        "kula ≠ sfera",
        "która bryła to kula?",
    ],
    "sfera": [
        "skórka piłki = sfera",
        "sfera = powierzchnia",
        "kula = pełna w środku",
        "sfera ≠ kula",
        "punkty w odległości r",
    ],
    "środek i promień": [
        "O — środek",
        "r od O do powierzchni",
        "2r = średnica",
        "zaznacz O i r",
        "każdy punkt w r od O",
    ],
    "ostrosłup prawidłowy": [
        "wierzchołek nad środkiem",
        "podstawa foremna",
        "h prostopadle",
        "boki boczne = △",
        "siatka symetryczna",
    ],
    "objętość ostrosłupa": [
        "V = ⅓ P_p h",
        "P_p=20, h=6 → V=40",
        "⅓ × podstawa × h",
        "V w cm³",
        "porównaj z graniast.",
    ],
    "wysokość ostrosłupa": [
        "h ⊥ podstawa",
        "h od W do P_p",
        "h w wzorze V",
        "h = 8 cm",
        "nie smuka!",
    ],
    "nierówność": [
        "x + 3 > 7",
        "2x ≤ 10",
        "x > 4",
        "zapis z >, <, ≥",
        "rozwiązanie na osi",
    ],
    "rozwiązanie nierówności": [
        "x > 4: x=5 ✔",
        "x ≤ 3: 3 ✔, 4 ✖",
        "zaznacz na osi",
        "x > 2 → 5 pasuje",
        "zbiór rozwiązań",
    ],
    "znaki": [
        "+ − × : = < >",
        "√ π % ∠",
        "odczytaj zapis",
        "znak w równaniu",
        "co oznacza ×?",
    ],
    "na osi": [
        "zaznacz x=3",
        "x > 2: prawo od 2",
        "−1, 0, 1 na osi",
        "koloruj rozwiązania",
        "odcinek na osi",
    ],
    "a równanie?": [
        "x+5=12 → tak",
        "3>7 → nie",
        "2x=8 → tak",
        "czy to równanie?",
        "niewiadoma + =",
    ],
    "przekształcanie wzoru": [
        "v=s/t → t=s/v",
        "P=a·b → a=P/b",
        "wyznacz h z V=abc",
        "przenieś na drugą str.",
        "s = v·t",
    ],
    "przykład: prędkość": [
        "v=120/2=60 km/h",
        "s=90, t=1,5 → v=60",
        "v=s/t w zadaniu",
        "t=s/v → t=2 h",
        "oblicz v, s lub t",
    ],
    "przykład: pole": [
        "P=6·4=24 cm²",
        "P=a·b prostokąt",
        "a=P/b → a=5",
        "P=πr², r=3",
        "wyznacz b z P=ab",
    ],
    "krok po kroku": [
        "1. dane 2. wzór",
        "3. podstaw 4. wynik",
        "5. jednostka",
        "sprawdź sens wyniku",
        "zapis w zeszycie",
    ],
    "wielokąt foremny": [
        "5 boków =, 5 kątów =",
        "trójkąt równoboczny",
        "kwadrat foremny",
        "sześciokąt foremny",
        "obrót symetrii",
    ],
    "podobieństwo": [
        "Δ ~ Δ",
        "kąty =, boki proporcj.",
        "skala k=2",
        "figury podobne",
        "powiększenie / pomniejsz.",
    ],
    "skala podobieństwa": [
        "k = 2: boki ×2",
        "k=3 → pole ×9",
        "a'/a = k",
        "skala 1:2",
        "oblicz brakujący bok",
    ],
    "a przystawanie?": [
        "BBB → tak, ≅",
        "podobne ≠ zawsze ≅",
        "sprawdź cechę",
        "Δ ABC ≅ Δ DEF?",
        "identyczne po nałożeniu",
    ],
    "okrąg wpisany": [
        "w trójkącie",
        "dotyka 3 boków",
        "środek równo daleko",
        "r promienia wpisanego",
        "narysuj w Δ",
    ],
    "okrąg opisany": [
        "wierzchołki na okręgu",
        "środek na symetralnych",
        "R promienia opisanego",
        "Δ w okręgu",
        "obwód opisany",
    ],
    "przesunięcie": [
        "przesuń Δ o 5 w prawo",
        "figura → w prawo 3 cm",
        "ta sama figura, inne miejsce",
        "każdy punkt o tyle samo",
        "przesuń kwadrat w górę",
    ],
    "obrót": [
        "obróć figurę o 90°",
        "wokół punktu O",
        "jak wskazówka zegara",
        "obrót ≠ przesunięcie",
        "obróć kwadrat o 180°",
    ],
    "a symetria?": [
        "oś symetrii — lustrzane",
        "obrót 180° — środkowa",
        "figura = obraz?",
        "motyl — tak",
        "litera F — nie",
    ],
    "liczba wymierna": [
        "½, −3, 0,75",
        "p/q, q≠0",
        "0,5 ✔ wymierna",
        "√2 ✖ (SP: niewym.)",
        "−7/4 wymierna",
    ],
    "środkowa": [
        "od wierzchołka do środka boku",
        "m = połowa boku",
        "3 środkowe w Δ",
        "środkowa z wierzch. A",
        "nie mylić z wysokością",
    ],
    "trzy środkowe": [
        "3 środkowe przecinają się",
        "punkt ciężkości",
        "każda do środka boku",
        "narysuj 3 środkowe",
        "G — punkt przecięcia",
    ],
    "a wysokość / dwusieczna?": [
        "h ⊥ bok",
        "dwusieczna dzieli kąt",
        "3 h w trójkącie",
        "3 dwusieczne → 1 punkt",
        "różne linie w Δ",
    ],
    "doświadczenie losowe": [
        "rzut kostką",
        "losowanie kuli",
        "rzut monetą",
        "losowy wybór",
        "wynik niepewny",
    ],
    "zdarzenie": [
        "wypadek 6 na kostce",
        "orzeł na monecie",
        "czerwona kula",
        "zdarzenie korzystne",
        "P zdarzenia",
    ],
    "wzór klasyczny": [
        "P = k/w",
        "k — korzystne",
        "w — wszystkie",
        "P(6)=1/6",
        "P(orzeł)=1/2",
    ],
    "drzewko możliwości": [
        "2 koszule × 3 spodnie",
        "gałąź: koszula A",
        "policz liście = wyniki",
        "ile dróg do szkoły?",
        "3·2·2 = 12 ubrań",
    ],
    "liczba niewymierna": [
        "√2 ✔ niewymierna",
        "π ✔ niewymierna",
        "√4 = 2 → wymierna",
        "√2 ≠ a/b",
        "π ≈ 3,14 (przybliżenie)",
    ],
    "przykłady wymiernych": [
        "−3 ∈ ℚ",
        "0 ∈ ℚ",
        "2/5 ∈ ℚ",
        "1,25 = 5/4 ∈ ℚ",
        "7 = 7/1 ∈ ℚ",
    ],
    # --- alias ---
    "z literami": [
        "2a + 3a = 5a",
        "x + x = 2x",
        "3n · 4 = 12n",
        "ab + ab = 2ab",
        "a(b+c) = ab+ac",
    ],
}


def examples_for(term: str) -> list[str] | None:
    key = (term or "").strip().lower()
    if key in PRZYKLADY:
        return list(PRZYKLADY[key])
    padded = f" {key} "
    matches = [
        k
        for k in PRZYKLADY
        if key == k or key.startswith(k + " ") or f" {k} " in padded
    ]
    if not matches:
        return None
    best = max(matches, key=len)
    return list(PRZYKLADY[best])
