# -*- coding: utf-8 -*-
"""Map page number -> list of illustration keys (one per card, '' = none)."""

PAGE_FIGS = {
    1: ["apples5", "digits", "", "place_value", "even_odd", "compare", "round_line", "prev_next", "order"],
    2: ["roman", "roman", "", "", "", "", "", ""],
    3: ["integers", "integers", "abs", "compare", "", "", "abs", "thermo"],
    4: ["add_dots", "add_dots", "sub_dots", "sub_dots", "apples5", "sub_dots", "", "", ""],
    5: ["mul_grid", "mul_grid", "mul_grid", "", "", "mul_grid"],
    6: ["div_groups", "div_groups", "div_groups", "", "", ""],
    7: ["order_ops", "power", "order_ops", "", "order_ops", "order_ops"],
    8: ["even_odd", "", "", "", "", "", "", ""],
    9: ["frac_pie", "frac_pie", "frac_pie", "frac_bars", "mix", "frac_bars"],
    10: ["frac_bars", "frac_bars", "frac_bars", "frac_bars", "compare", "frac_pie"],
    11: ["decimal", "decimal", "decimal", "frac_bars", "compare", "round_line"],
    12: ["frac_add", "frac_add", "frac_bars", "frac_pie", "frac_pie", "frac_bars"],
    13: ["power", "power", "power", "power", "", ""],
    14: ["root", "root", "root", "power", "root", ""],
    15: ["percent", "percent", "percent", "percent", "frac_pie", "percent"],
    16: ["prop", "prop", "prop", "bars", "prop", "balance"],
    17: ["equation", "", "", "equation", "", "order_ops"],
    18: ["", "equation", "", "", "", "equation"],
    19: ["equation", "equation", "equation", "balance", "balance", "balance"],
    20: ["ruler", "ruler", "ruler", "compare", "peri_area", "ruler"],
    21: ["mass", "mass", "compare", "mass", "mass", ""],
    22: ["volume", "volume", "volume", "volume", "volume", "cube"],
    23: ["clock", "clock", "clock", "clock", "clock", "clock"],
    24: ["calendar", "calendar", "calendar", "calendar", "calendar", "calendar"],
    25: ["thermo", "thermo", "thermo", "compare", "thermo", "thermo"],
    26: ["money", "money", "money", "money", "compare", "money"],
    27: ["speed", "speed", "speed", "scale_map", "scale_map", "speed"],
    28: ["", "", "ruler", "", "", "shapes"],
    29: ["shapes", "shapes", "shapes", "shapes", "shapes", "shapes"],
    30: ["circle", "circle", "circle", "circle", "circle", "circle"],
    31: ["circle", "circle", "circle", "circle", "circle", "circle"],
    32: ["angle", "angle", "angle", "angle", "angle", "angles"],
    33: ["angles", "angles", "angle", "angles", "angles", "angles"],
    34: ["parallel", "parallel", "parallel", "parallel", "angles", "angles"],
    35: ["peri_area", "peri_area", "peri_area", "shapes", "shapes", "peri_area"],
    36: ["cube", "cube", "cube", "cube", "circle", "cube"],
    37: ["symmetry", "symmetry", "symmetry", "symmetry", "symmetry", "symmetry"],
    38: ["coords", "coords", "coords", "coords", "coords", "coords"],
    39: ["bars", "bars", "bars", "bars", "bars", "pie_chart"],
    40: ["bars", "bars", "bars", "bars", "bars", "bars"],
    41: ["dice", "mul_grid", "", "", "dice", "dice"],
    42: ["signs", "signs", "signs", "signs", "compare", "signs"],
    43: ["", "", "", "", "", ""],
    44: ["", "", "", "", ""],
    45: ["", "", "", "", "", ""],
    46: ["frac_pie", "frac_bars", "frac_bars", "percent", "percent"],
    47: ["ruler", "ruler", "ruler", "decimal", ""],
    48: ["angle", "angle", "angle", "peri_area", ""],
    49: ["angles", "angles", "angle", "shapes", "shapes"],
    50: ["shapes", "shapes", "peri_area", "peri_area", ""],
    51: ["cube", "cube", "cube", "cube", "cube", "cube"],
    52: ["percent", "percent", "percent", "percent", "percent", ""],
    53: ["power", "power", "power", "power", ""],
    54: ["root", "root", "root", "root", "root"],
    55: ["equation", "equation", "equation", "equation", ""],
    56: ["prop", "prop", "prop", "prop", "balance"],
    57: ["", "", "", "", "", ""],
    58: ["shapes", "shapes", "shapes", "shapes", ""],
    59: ["coords", "coords", "coords", "coords", ""],
    60: ["symmetry", "symmetry", "angle", "angle", "shapes"],
}
