# -*- coding: utf-8 -*-
"""Hardcoded bilingual content for all mini-dictionary pages."""

def C(pl, ua, visual, def_pl, def_ua, wide="", **kwargs):
    d = {"pl": pl, "ua": ua, "visual": visual, "def_pl": def_pl, "def_ua": def_ua, **kwargs}
    if wide:
        d["wide"] = wide
    return d

def R(pl, ua, formula=""):
    """Zasada na koniec strony. formula = wyróżniony wzór (opcjonalnie)."""
    d = {"pl": pl, "ua": ua}
    if formula:
        d["formula"] = formula
    return d

def P(n, file, cat, cat_pl, cat_ua, title_pl, title_ua, intro_pl, intro_ua, tip_pl, tip_ua, cards, remember):
    return {
        "n": n, "file": file, "cat": cat, "cat_pl": cat_pl, "cat_ua": cat_ua,
        "title_pl": title_pl, "title_ua": title_ua,
        "intro_pl": intro_pl, "intro_ua": intro_ua,
        "tip_pl": tip_pl, "tip_ua": tip_ua,
        "cards": cards, "remember": remember,
    }

PAGES = []

def add(*args, **kwargs):
    PAGES.append(P(*args, **kwargs) if args else P(**kwargs))

# --- 1-15 ---
PAGES += [
P(1,"page01.html","A","LICZBY","ЧИСЛА","Liczby naturalne","Натуральні числа",
"To podstawowe liczby, których używamy do liczenia","Це основні числа, які ми використовуємо для лічби",
"Cyfra ≠ liczba — to początek!","Цифра ≠ число — це старт!",
[C("liczba naturalna","натуральне число","1, 2, 3, 4, 5, …",
   "Liczby, którymi liczymy: ile jabłek, ile dzieci, ile kroków.",
   "Числа, якими лічимо: скільки яблук, дітей, кроків.",
   rule="Zaczynamy od 1 i idziemy dalej: 1, 2, 3, 4… (w niektórych umowach szkolnych też od 0).",
   rule_ua="Починаємо від 1 і далі: 1, 2, 3… (у деяких шкільних домовленнях також від 0).", media="photo"),
 C("cyfra","цифра","0 1 2 3 4 5 6 7 8 9",
   "Cyfra to „klocek” do budowania liczb. Jest ich tylko dziesięć.",
   "Цифра — «цеглинка» для чисел. Їх лише десять.",
   rule="Z cyfr składasz liczby: 3 to cyfra i liczba; 35 to liczba z dwóch cyfr.",
   rule_ua="З цифр складаєш числа.", media="diagram"),
 C("liczba","число","347",
   "Liczba mówi, ile czegoś jest. Może mieć wiele cyfr.",
   "Число каже, скільки чогось є.",
   rule="Czytamy od lewej: setki, dziesiątki, jednostki.",
   rule_ua="Читаємо зліва: сотні, десятки, одиниці.", media="cover"),
 C("wartość pozycyjna","позиційне значення","3 → setki · 4 → dziesiątki · 7 → jednostki",
   "To samo „3” znaczy co innego w zależności od miejsca.",
   "Та сама «3» означає різне залежно від місця.",
   rule="Im bardziej w lewo, tym większa wartość miejsca.",
   rule_ua="Що лівіше — то більше значення розряду.", media="diagram"),
 C("liczba porządkowa","порядкове число","1. pierwszy · 2. drugi · 3. trzeci",
   "Mówi o kolejności: kto pierwszy, kto drugi — nie „ile”, tylko „który z kolei”.",
   "Каже про порядок: хто перший, хто другий — не «скільки», а «який за порядком».",
   klasa="klasy 1–3", media="cover"),
 C("zero","нуль","0",
   "Zero = nic / pusto. W kl. 1–3 bywa umowa: naturalne od 1 albo od 0.",
   "Нуль = нічого / порожньо. У кл. 1–3 буває домовленість: натуральні від 1 або від 0.",
   klasa="klasy 1–3", media="diagram"),
 C("parzysta / nieparzysta","парне / непарне","0,2,4,6,8 / 1,3,5,7,9",
   "Parzysta dzieli się równo na 2. Nieparzysta — zostaje 1.",
   "Парне ділиться порівну на 2. Непарне — лишається 1.",
   rule="Patrz na ostatnią cyfrę — to wystarczy.",
   rule_ua="Дивись на останню цифру.", media="diagram"),
 C("porównanie","порівняння","3 < 7 · 5 = 5 · 9 > 2",
   "Sprawdzamy, która liczba jest mniejsza, równa albo większa.",
   "Перевіряємо, яке число менше, рівне чи більше.",
   rule="Otwarty dziób znaku < > zawsze w stronę większej liczby.",
   rule_ua="«Рот» знака < > завжди до більшого числа.", media="cover"),
 C("zaokrąglanie","округлення","47 → 50",
   "Zamieniamy liczbę na bliską, wygodną do liczenia.",
   "Міняємо число на близьке, зручне для рахунку.",
   rule="Patrz na następną cyfrę: 0–4 w dół, 5–9 w górę.",
   rule_ua="Дивись на наступну цифру: 0–4 вниз, 5–9 вгору.", media="diagram"),
 C("następnik / poprzednik","наступник / попередник","8 ← 9 → 10",
   "Poprzednik: o 1 mniej. Następnik: o 1 więcej.",
   "Попередник: на 1 менше. Наступник: на 1 більше.",
   rule="Na osi liczbowej: sąsiad z lewej i z prawej.",
   rule_ua="На числовій прямій: сусід зліва і справа.", media="diagram"),
 C("kolejność liczb","порядок чисел","1 → 2 → 3 → 4 → 5 → 6",
   "Układamy liczby od najmniejszej do największej (lub odwrotnie).",
   "Розкладаємо від найменшого до найбільшого.",
   rule="Porównuj po kolei albo ustaw na osi.",
   rule_ua="Порівнюй по черзі або постав на пряму.", media="cover")],
[R("Liczymy nimi przedmioty i zdarzenia.","Ними лічимо предмети і події."),
 R("Cyfra ≠ liczba (cyfr jest 10).","Цифра ≠ число (цифр 10)."),
 R("Miejsce cyfry = jej wartość.","Місце цифри = її значення."),
 R("Parzystość: ostatnia cyfra.","Парність: остання цифра."),
 R("Zaokrąglaj, by łatwiej szacować.","Округлюй, щоб легше оцінювати.")]),

P(2,"page02.html","A","LICZBY","ЧИСЛА","Liczby rzymskie","Римські числа",
"System zapisu liczb używany od starożytności","Система запису чисел із давніх часів",
"Mniejszy z prawej → dodaj; z lewej → odejmij.","Менший праворуч → додай; ліворуч → відніми.",
[C("Podstawowe znaki","Основні знаки","I=1 V=5 X=10 L=50<br>C=100 D=500 M=1000","Siedem znaków tworzy wszystkie liczby rzymskie.","Сім знаків створюють усі римські числа.","wide-2"),
 C("Składanie liczb","Складання чисел","1=I · 4=IV · 9=IX<br>14=XIV · 50=L · 100=C","Liczba powstaje z połączenia znaków.","Число утворюється з поєднання знаків."),
 C("Dodawanie znaków","Додавання знаків","VI = V+I = 6","Gdy mniejszy znak stoi po prawej — dodajemy.","Коли менший знак праворуч — додаємо."),
 C("Odejmowanie znaków","Віднімання знаків","IV = V−I = 4","Gdy mniejszy znak stoi po lewej — odejmujemy.","Коли менший знак ліворуч — віднімаємо."),
 C("Ograniczenia","Обмеження","I przed V,X · X przed L,C · C przed D,M","Tylko I, X, C mogą stać przed większym do odjęcia.","Лише I, X, C можуть стояти перед більшим для віднімання."),
 C("Większe przykłady","Більші приклади","44=XLIV · 99=XCIX<br>2024=MMXXIV","Czytamy od lewej według zasad +/−.","Читаємо зліва за правилами +/−.","wide-2"),
 C("Gdzie spotykamy?","Де зустрічаємо?","zegary · rozdziały · pomniki · filmy","Na zegarach, w książkach, na budowlach, w kulturze.","На годинниках, у книгах, на будівлях, у культурі.","wide-2"),
 C("Zamiana na arabskie","Перетворення на арабські","LXIV → 50+10+4 = 64","Czytaj, odejmij gdy trzeba, dodaj, zsumuj.","Читай, відніми коли треба, додай, підсумуй.","wide-3")],
[R("Znaki: I=1 V=5 X=10 L=50 C=100 D=500 M=1000.","Знаки: I=1 V=5 X=10 L=50 C=100 D=500 M=1000."),
 R("Mniejszy po prawej → dodaj (VI=6).","Менший праворуч → додай (VI=6)."),
 R("Mniejszy po lewej → odejmij (IV=4).","Менший ліворуч → відніми (IV=4)."),
 R("I przed V,X · X przed L,C · C przed D,M.","I перед V,X · X перед L,C · C перед D,M.")]),

P(3,"page03.html","A","LICZBY","ЧИСЛА","Liczby całkowite","Цілі числа",
"Liczby dodatnie, ujemne i zero","Додатні, від'ємні числа і нуль",
"Na osi: im bardziej w lewo, tym mniejsza.","На прямій: що лівіше — то менше.",
[C("oś liczbowa","числова пряма","… −3 −2 −1 0 1 2 3 …","Prosta z liczbami w kolejności.","Пряма з числами в порядку."),
 C("dodatnie, ujemne, zero","додатні, від'ємні, нуль","ujemne | 0 | dodatnie","Lewo od 0 — ujemne, prawo — dodatnie.","Ліворуч від 0 — від'ємні, праворуч — додатні."),
 C("wartość bezwzględna","модуль (абсолютне значення)","|5|=5 · |−5|=5","Odległość od zera na osi.","Відстань від нуля на прямій."),
 C("porównywanie","порівняння","−7 &lt; −2 &lt; 0 &lt; 4","Im bardziej w lewo, tym mniejsza.","Чим лівіше, тим менше."),
 C("dodawanie","додавання","(−3)+(+5)=2","Uwzględniamy znaki i |a|.","Враховуємо знаки і |a|."),
 C("odejmowanie","віднімання","a−b = a+(−b)","Odejmowanie = dodawanie przeciwnej.","Віднімання = додавання протилежного."),
 C("liczba przeciwna","протилежне число","przeciwna do 7 → −7","Ta sama |a|, przeciwny znak.","Той самий |a|, протилежний знак."),
 C("zastosowania","застосування","temperatura · dług · piętra","Poniżej zera, dług, piętra pod ziemią.","Нижче нуля, борг, поверхи під землею.","wide-2")],
[R("Całkowite = N + 0 + ujemne.","Цілі = N + 0 + від'ємні."),
 R("|a| = odległość od 0.","|a| = відстань від 0."),
 R("a−b = a+(−b).","a−b = a+(−b)."),
 R("Na osi: lewo = mniejsze.","На прямій: ліворуч = менше.")]),

P(4,"page04.html","B","DZIAŁANIA","ДІЇ","Dodawanie i odejmowanie","Додавання й віднімання",
"Dwa podstawowe działania w matematyce","Дві основні дії в математиці",
"Suma = wynik + · różnica = wynik −","Сума = результат + · різниця = результат −",
[C("dodawanie","додавання","3 + 5 = 8","Składamy dwie liczby w sumę.","Складаємо два числа в суму."),
 C("suma","сума","składnik + składnik = suma","Wynik dodawania.","Результат додавання."),
 C("odejmowanie","віднімання","9 − 4 = 5","Odejmujemy jedną liczbę od drugiej.","Віднімаємо одне число від іншого."),
 C("różnica","різниця","odjemna − odjemnik = różnica","Wynik odejmowania.","Результат віднімання."),
 C("dodawanie na palcach / osi","додавання на пальцях / прямій","✋ 3+2 · ——→ na osi",
   "Jak w kl. 1–2: najpierw na palcach albo skacząc w prawo po osi liczbowej.",
   "Як у кл. 1–2: спочатку на пальцях або стрибаючи вправо по числовій прямій.",
   klasa="klasy 1–2", media="diagram"),
 C("odejmowanie: ile zostało","віднімання: скільки лишилось","9 − 4 → ile zostało?",
   "Jak w kl. 1–2: miałem 9, zabrałem 4 — ile zostało?",
   "Як у кл. 1–2: мав 9, забрав 4 — скільки лишилось?",
   klasa="klasy 1–2", media="cover"),
 C("składnik","доданок","1 + 3 = 4","Liczba, którą dodajemy.","Число, яке додаємо."),
 C("odjemna i odjemnik","зменшуване і від'ємник","8 − 3 = 5","Odjemna — od czego; odjemnik — ile.","Зменшуване — від чого; від'ємник — скільки."),
 C("właściwości +","властивості +","3+5=5+3<br>(2+3)+4=2+(3+4)","Przemienność i łączność.","Переставна і сполучна."),
 C("właściwości −","властивості −","a−0=a · a−a=0","Minus 0 nie zmienia; minus siebie = 0.","Мінус 0 не змінює; мінус себе = 0."),
 C("przykłady","приклади","2+3=5 · 7+8=15<br>8−3=5 · 15−6=9","Ćwicz obie operacje.","Тренуй обидві дії.")],
[R("Dodawanie — łączymy.","Додавання — об'єднуємо."),
 R("Odejmowanie — zabieramy.","Віднімання — забираємо."),
 R("Wynik po znaku =.","Результат після =."),
 R("Sprawdź odwrotnie.","Перевір навпаки."),
 R("Ćwicz codziennie.","Тренуйся щодня.")]),

P(5,"page05.html","B","DZIAŁANIA","ДІЇ","Tabliczka mnożenia","Таблиця множення",
"Mnożenie to szybkie dodawanie tej samej liczby","Множення — швидке додавання того самого числа",
"× = wielokrotne + · a×0=0 · a×1=a","× = багаторазове + · a×0=0 · a×1=a",
[C("mnożenie","множення","4 × 3 = 12","Powtarzane dodawanie.","Повторюване додавання."),
 C("mnożenie = dodawanie tej samej","множення = додавання тієї самої","4×3 = 4+4+4",
   "Trzy paczki po 4 cukierki: 4 + 4 + 4. Mnożenie to skrót takiego dodawania.",
   "Три пачки по 4 цукерки: 4 + 4 + 4. Множення — скорочення такого додавання.",
   klasa="klasy 1–3", media="diagram"),
 C("iloczyn","добуток","czynnik × czynnik = iloczyn","Wynik mnożenia.","Результат множення."),
 C("czynnik","множник","2 × 5 = 10","Liczba, którą mnożymy.","Число, яке множимо."),
 C("przemienność","переставна властивість","3×4 = 4×3","Kolejność nie zmienia wyniku.","Порядок не змінює результату."),
 C("×0 i ×1","×0 і ×1","a×0=0 · a×1=a","Przez 0 = 0; przez 1 = ta sama.","На 0 = 0; на 1 = те саме."),
 C("kluczowe wyniki","ключові результати","5×5=25 · 6×7=42<br>7×8=56 · 9×9=81","Naucz się 1×1 do 10×10.","Вивчи 1×1 до 10×10.","wide-3")],
[R("Mnożenie = wielokrotne +.","Множення = багаторазове +."),
 R("Iloczyn = wynik.","Добуток = результат."),
 R("a×0=0, a×1=a.","a×0=0, a×1=a."),
 R("Tabliczka = fundament.","Таблиця = фундамент.")]),

P(6,"page06.html","B","DZIAŁANIA","ДІЇ","Dzielenie","Ділення",
"Rozdzielanie na równe części albo ile razy mieści się liczba w liczbie","Розподіл на рівні частини або скільки разів вміщується",
"Nie dziel przez 0! Sprawdź ×.","Не діли на 0! Перевір ×.",
[C("dzielenie","ділення","12 : 3 = 4","Równe części.","Рівні частини."),
 C("sprawiedliwe rozdawanie","справедлива роздача","12 cukierków : 3 dzieci",
   "Dzielenie = rozdajemy po równo: każdemu tyle samo, nic nie zostaje „na boku”.",
   "Ділення = роздаємо порівну: кожному стільки само, нічого не лишається «збоку».",
   klasa="klasy 1–3", media="cover"),
 C("iloraz","частка","dzielna : dzielnik = iloraz","Wynik dzielenia.","Результат ділення."),
 C("dzielna i dzielnik","ділене і дільник","15 : 5 = 3","Dzielna — co; dzielnik — przez co.","Ділене — що; дільник — на що."),
 C("z resztą","з остачею","17 : 5 = 3 r. 2","Gdy nie wychodzi równo.","Коли не виходить порівну."),
 C("związek z ×","зв'язок із ×","12:3=4 ↔ 4×3=12","Sprawdzamy mnożeniem.","Перевіряємо множенням."),
 C(":1 i : siebie","на 1 і на себе","a:1=a · a:a=1","Przez 1 — ta sama; przez siebie — 1 (≠0).","На 1 — те саме; на себе — 1 (≠0).")],
[R("Dzielenie = równe części.","Ділення = рівні частини."),
 R("Nie dziel przez 0!","Не діли на 0!"),
 R("Sprawdzaj ×.","Перевіряй ×."),
 R("Iloraz = wynik.","Частка = результат.")]),

P(7,"page07.html","B","DZIAŁANIA","ДІЇ","Kolejność działań","Порядок дій",
"Kolejność: co liczymy najpierw, a co później","Порядок: що рахуємо спочатку, а що пізніше",
"Nawiasy → potęgi → ×: → +−","Дужки → степені → ×: → +−",
[C("nawiasy","дужки","(2+3)×4 = 20","Najpierw nawiasy.","Спочатку дужки."),
 C("potęgi","степені","2+3² = 11","Po nawiasach — potęgi.","Після дужок — степені."),
 C("× i :","× і :","2+3×4 = 14","Przed + i −.","Перед + і −."),
 C("+ i −","+ і −","10−3+2 = 9","Na końcu, od lewej.","Наприкінці, зліва."),
 C("ten sam poziom","той самий рівень","24:6×2 = 8","Od lewej do prawej.","Зліва направо."),
 C("przykład","приклад","2+3×(8−2²)=14","Krok po kroku według reguły.","Крок за кроком за правилом.","wide-3")],
[R("1. Nawiasy","1. Дужки"),
 R("2. Potęgi","2. Степені"),
 R("3. × i :","3. × і :"),
 R("4. + i −","4. + і −")]),

P(8,"page08.html","B","DZIAŁANIA","ДІЇ","Podzielność","Подільність",
"Czy liczba dzieli się bez reszty","Чи число ділиться без остачі",
"Szybkie sprawdzanie liczb!","Швидка перевірка чисел!",
[C("przez 2","на 2","końcówka 0,2,4,6,8","Ostatnia cyfra parzysta.","Остання цифра парна."),
 C("przez 3","на 3","suma cyfr ÷ 3","Suma cyfr podzielna przez 3.","Сума цифр ділиться на 3."),
 C("przez 4","на 4","2 ostatnie cyfry ÷ 4","Liczba z dwóch ostatnich ÷ 4.","Число з двох останніх ÷ 4."),
 C("przez 5","на 5","końcówka 0 lub 5","Ostatnia 0 lub 5.","Остання 0 або 5."),
 C("przez 9","на 9","suma cyfr ÷ 9","Suma cyfr ÷ 9.","Сума цифр ÷ 9."),
 C("przez 10","на 10","końcówka 0","Ostatnia cyfra 0.","Остання цифра 0."),
 C("dzielnik / wielokrotność","дільник / кратне","dzielniki 12: 1,2,3,4,6,12","Dzielnik dzieli bez reszty.","Дільник ділить без остачі."),
 C("liczba pierwsza","просте число","2,3,5,7,11,13…","Dokładnie dwa dzielniki: 1 i ona sama.","Рівно два дільники: 1 і воно саме.","wide-2")],
[R("2 — cyfra parzysta.","2 — парна цифра."),
 R("3 i 9 — suma cyfr.","3 і 9 — сума цифр."),
 R("5 — 0 lub 5.","5 — 0 або 5."),
 R("10 — końcówka 0.","10 — кінець 0.")]),
]

PAGES += [
P(9,"page09.html","C","UŁAMKI","ДРОБИ","Ułamki zwykłe (1)","Звичайні дроби (1)",
"Poznajemy ułamki, porównujemy, skracamy i rozszerzamy","Пізнаємо дроби, порівнюємо, скорочуємо й розширюємо",
"Ułamki są wszędzie!","Дроби всюди!",
[C("ułamek zwykły","звичайний дріб","a/b · np. 3/4","Licznik nad kreską, mianownik pod kreską.","Чисельник над рискою, знаменник під рискою."),
 C("licznik","чисельник","3/4 → 3","Ile części bierzemy.","Скільки частин беремо."),
 C("mianownik","знаменник","3/4 → 4","Na ile równych części podzielono całość.","На скільки рівних частин поділено ціле."),
 C("właściwy / niewłaściwy","правильний / неправильний","2/5 &lt; 1 · 7/4 &gt; 1","Właściwy: licznik &lt; mianownik.","Правильний: чисельник &lt; знаменник."),
 C("liczba mieszana","мішане число","1 3/4 = 7/4","Część całkowita + ułamek właściwy.","Ціла частина + правильний дріб."),
 C("ułamki równe","рівні дроби","1/2 = 2/4 = 3/6","Różny zapis, ta sama wartość.","Різний запис, те саме значення.")],
[R("Licznik — ile części.","Чисельник — скільки частин."),
 R("Mianownik — na ile części.","Знаменник — на скільки частин."),
 R("Mianownik ≠ 0.","Знаменник ≠ 0.")]),

P(10,"page10.html","C","UŁAMKI","ДРОБИ","Ułamki zwykłe (2)","Звичайні дроби (2)",
"Skracanie, rozszerzanie i porównywanie","Скорочення, розширення й порівняння",
"Łatwiej dzielić i rozumieć świat!","Легше ділити і розуміти світ!",
[C("skracanie","скорочення","4/6 = 2/3","÷ licznik i mianownik tą samą liczbą ≠ 0.","÷ чисельник і знаменник тим самим ≠ 0."),
 C("rozszerzanie","розширення","2/3 = 4/6","× licznik i mianownik tą samą liczbą ≠ 0.","× чисельник і знаменник тим самим ≠ 0."),
 C("ułamek nieskracalny","нескоротний дріб","12/18 → 2/3","Dzielimy przez NWD.","Ділимо на НСД."),
 C("wspólny mianownik","спільний знаменник","1/2 i 1/3 → 3/6 i 2/6","Potrzebny do +/− i porównań.","Потрібний для +/− і порівнянь."),
 C("porównywanie","порівняння","2/5 &lt; 3/5 · 1/2 &gt; 1/3","Ten sam mianownik → większy licznik = większy ułamek.","Однаковий знаменник → більший чисельник = більший дріб."),
 C("ułamek = dzielenie","дріб = ділення","3/4 = 3:4","Licznik dzielony przez mianownik.","Чисельник ділений на знаменник.")],
[R("Skracamy ÷.","Скорочуємо ÷."),
 R("Rozszerzamy ×.","Розширюємо ×."),
 R("Wartość się nie zmienia.","Значення не змінюється.")]),

P(11,"page11.html","C","UŁAMKI","ДРОБИ","Ułamki dziesiętne","Десяткові дроби",
"Mianownik 10, 100, 1000…","Знаменник 10, 100, 1000…",
"Z przecinkiem w codziennym życiu!","З комою в повсякденні!",
[C("ułamek dziesiętny","десятковий дріб","0,5 · 2,75 · 3,14","Zapis z przecinkiem.","Запис із комою."),
 C("miejsca po przecinku","розряди після коми","2,375 → 1/10, 1/100, 1/1000","Kolejne cyfry to dziesiętne, setne, tysięczne.","Наступні цифри — десяті, соті, тисячні."),
 C("równoważność","рівнозначність","0,5 = 0,50 = 0,500","Zera na końcu nie zmieniają wartości.","Нулі в кінці не змінюють значення."),
 C("zamiana na zwykły","на звичайний","0,25 = 25/100 = 1/4","Licznik = cyfry po przecinku.","Чисельник = цифри після коми."),
 C("porównywanie","порівняння","1,25 &lt; 1,3","Porównujemy rozrząd po rozrządzie.","Порівнюємо розряд за розрядом."),
 C("zaokrąglanie","округлення","3,141 → 3,14","≥5 w górę, &lt;5 w dół.","≥5 вгору, &lt;5 вниз.")],
[R("Przecinek oddziela część całkowitą.","Кома відокремлює цілу частину."),
 R("0,5 = 1/2 = 50%.","0,5 = 1/2 = 50%."),
 R("Zera na końcu nie zmieniają.","Нулі в кінці не змінюють.")]),

P(12,"page12.html","C","UŁAMKI","ДРОБИ","Działania na ułamkach","Дії з дробами",
"Dodajemy, odejmujemy, mnożymy i dzielimy","Додаємо, віднімаємо, множимо і ділимо",
"Zrozum zasady!","Зрозумій правила!",
[C("+/− ten sam mianownik","+/− однаковий знаменник","2/7 + 3/7 = 5/7","+/− liczniki, mianownik bez zmian.","+/− чисельники, знаменник без змін."),
 C("różne mianowniki","різні знаменники","1/2+1/3 = 5/6","Najpierw wspólny mianownik.","Спочатку спільний знаменник."),
 C("mnożenie","множення","2/3 × 4/5 = 8/15","Licznik×licznik, mianownik×mianownik.","Чисельник×чисельник, знаменник×знаменник."),
 C("dzielenie","ділення","2/3 : 4/5 = 2/3 × 5/4","× przez odwrotność.","× на обернений."),
 C("odwrotność","обернений дріб","3/4 → 4/3","Zamieniamy licznik i mianownik.","Міняємо чисельник і знаменник."),
 C("skracanie przed ×","скорочення перед ×","2/9 × 3/4 = 1/6","Skracamy przekątnie, gdy się da.","Скорочуємо по діагоналі, якщо можна.")],
[R("+/− : wspólny mianownik.","+/− : спільний знаменник."),
 R("× : liczniki i mianowniki.","× : чисельники і знаменники."),
 R(": : × odwrotność."," : : × обернений.")]),

P(13,"page13.html","B","DZIAŁANIA","ДІЇ","Potęgi","Степені",
"Krótszy zapis mnożenia","Коротший запис множення",
"Łatwiejsze liczenie większych liczb!","Легший рахунок більших чисел!",
[C("potęga","степінь","2³ = 2×2×2 = 8","Iloczyn jednakowych czynników.","Добуток однакових множників."),
 C("podstawa i wykładnik","основа і показник","aⁿ","Podstawa — co; wykładnik — ile razy.","Основа — що; показник — скільки разів."),
 C("kwadrat i sześcian","квадрат і куб","5²=25 · 2³=8","² = kwadrat; ³ = sześcian.","² = квадрат; ³ = куб."),
 C("0, 1, 10","0, 1, 10","a¹=a · a⁰=1 (≠0)<br>10ⁿ = 1 i n zer","Do 1 = ona sama; do 0 = 1.","До 1 = воно саме; до 0 = 1."),
 C("mnożenie potęg","множення степенів","aᵐ · aⁿ = aᵐ⁺ⁿ","Dodajemy wykładniki.","Додаємо показники."),
 C("dzielenie potęg","ділення степенів","aᵐ : aⁿ = aᵐ⁻ⁿ","Odejmujemy wykładniki (a≠0).","Віднімаємо показники (a≠0).")],
[R("aⁿ = a·a·… (n razy).","aⁿ = a·a·… (n разів)."),
 R("a¹=a, a⁰=1 (≠0).","a¹=a, a⁰=1 (≠0)."),
 R("× dodaj, : odejmij wykładniki.","× додай, : відніми показники.")]),

P(14,"page14.html","B","DZIAŁANIA","ДІЇ","Pierwiastki","Корені",
"Pierwiastek kwadratowy z liczby","Квадратний корінь з числа",
"Odwraca potęgę drugą.","Повертає піднесення до квадрата.",
[C("pierwiastek kwadratowy","квадратний корінь","√9 = 3","Liczba, której kwadrat daje podpierwiastkową.","Число, квадрат якого дає підкореневий вираз."),
 C("zapis","запис","√ □","Znak √ i wyrażenie podpierwiastkowe.","Знак √ і підкореневий вираз."),
 C("przykłady","приклади","√4=2 · √16=4 · √25=5 · √100=10","Szukamy liczby do kwadratu.","Шукаємо число до квадрата."),
 C("związek z potęgą","зв'язок зі степенем","(√a)² = a","Działania odwrotne.","Обернені дії."),
 C("kwadraty doskonałe","повні квадрати","1,4,9,16,25,36,49,64,81,100","Warto znać na pamięć.","Варто знати напам'ять."),
 C("szacowanie","оцінювання","√50 ≈ 7,1 (7²=49)","Najbliższy kwadrat doskonały.","Найближчий повний квадрат.")],
[R("√a · √a = a (a≥0).","√a · √a = a (a≥0)."),
 R("W SP: a ≥ 0.","У школі: a ≥ 0."),
 R("Zapamiętaj kwadraty do 10².","Запам'ятай квадрати до 10².")]),

P(15,"page15.html","C","UŁAMKI","ДРОБИ","Procenty","Відсотки",
"Porównywanie i obliczanie części całości","Порівняння й обчислення частин цілого",
"Procent = ułamek /100!","Відсоток = дріб /100!",
[C("procent","відсоток","1% = 1/100 = 0,01","Ułamek o mianowniku 100.","Дріб зі знаменником 100."),
 C("procent z liczby","відсоток від числа","p% z a = a·p/100","Mnożymy a przez p/100.","Множимо a на p/100."),
 C("zwiększenie o p%","збільшення на p%","a(1+p/100)","Dodajemy p% od a do a.","Додаємо p% від a до a."),
 C("zmniejszenie o p%","зменшення на p%","a(1−p/100)","Odejmujemy p% od a.","Віднімаємо p% від a."),
 C("zamiany","перетворення","25% = 1/4 = 0,25","% ↔ ułamek ↔ dziesiętny.","% ↔ дріб ↔ десятковий."),
 C("przykłady","приклади","20% z 50 = 10<br>15% z 200 = 30","10%=1/10, 50%=1/2, 25%=1/4.","10%=1/10, 50%=1/2, 25%=1/4.")],
[R("1% = 1/100.","1% = 1/100."),
 R("p% z a = a·p/100.","p% від a = a·p/100."),
 R("100% = całość.","100% = ціле.")]),

P(16,"page16.html","B","DZIAŁANIA","ДІЇ","Proporcjonalność","Пропорційність",
"Proporcjonalność prosta","Пряма пропорційність",
"Jedna rośnie — druga też!","Одна зростає — друга теж!",
[C("proporcjonalność prosta","пряма пропорційність","y = k·x","Stosunek y/x jest stały.","Відношення y/x стале."),
 C("współczynnik","коефіцієнт","k = y/x","Stała proporcjonalności.","Стала пропорційності."),
 C("wykres","графік","prosta przez (0,0)","Linia prosta przez początek układu.","Пряма через початок координат."),
 C("tabela wartości","таблиця значень","x: 1,2,3 → y: 2,4,6","Gdy znamy parę, liczymy inne.","Якщо знаємо пару, рахуємо інші."),
 C("przykład","приклад","3 kg → 12 zł ⇒ 5 kg → 20 zł","× tyle samo razy obie wielkości.","× стільки само разів обидві величини."),
 C("proporcja","пропорція","a/b = c/d","Iloczyn skrajnych = iloczyn środkowych.","Добуток крайніх = добуток середніх.")],
[R("Stosunek stały.","Відношення стале."),
 R("Wykres: prosta przez (0,0).","Графік: пряма через (0,0)."),
 R("a/b = c/d → a·d = b·c.","a/b = c/d → a·d = b·c.")]),

P(17,"page17.html","B","DZIAŁANIA","ДІЇ","Wyrażenia algebraiczne","Алгебраїчні вирази",
"Zapisy z literami i liczbami","Записи з літерами і числами",
"Litery pomagają zapisać ogólną zasadę!","Літери допомагають записати загальне правило!",
[C("wyrażenie algebraiczne","алгебраїчний вираз","3x + 5y − 8","Kombinacja liczb, liter i działań.","Комбінація чисел, літер і дій."),
 C("elementy","елементи","liczby · litery · znaki działań","Części składowe zapisu.","Складники запису."),
 C("zmienna","змінна","x, y, a, n…","Litera oznaczająca nieznaną lub zmienną wartość.","Літера для невідомого або змінного значення."),
 C("wartość liczbowa","числове значення","x=2 → 3x+1=7","Podstawiamy liczbę zamiast litery.","Підставляємо число замість літери."),
 C("zapis skrócony","скорочений запис","3x = x+x+x · xy = x·y","Bez znaku mnożenia przy literach.","Без знака множення біля літер."),
 C("kolejność","порядок","jak w arytmetyce","Nawiasy, potęgi, ×:, +−.","Дужки, степені, ×:, +−.")],
[R("Litera = zmienna.","Літера = змінна."),
 R("Podstaw → oblicz.","Підстав → обчисли."),
 R("3x znaczy 3·x.","3x означає 3·x.")]),

P(18,"page18.html","B","DZIAŁANIA","ДІЇ","Sumy algebraiczne","Алгебраїчні суми",
"Uproszczone zapisy z liter i liczb","Спрощені записи з літер і чисел",
"Łączymy wyrazy podobne!","Поєднуємо подібні доданки!",
[C("jednomian","одночлен","5x² · −3ab · 7","Iloczyn liczby i liter (lub sama liczba).","Добуток числа і літер (або саме число)."),
 C("suma algebraiczna","алгебраїчна сума","3x − 2y + 5","Dodajemy lub odejmujemy jednomiany.","Додаємо або віднімаємо одночлени."),
 C("wyrazy podobne","подібні доданки","3x i −5x","Te same litery z tymi samymi wykładnikami.","Ті самі літери з тими самими показниками."),
 C("redukcja","зведення","3x + 5x = 8x","Dodajemy współczynniki wyrazów podobnych.","Додаємо коефіцієнти подібних доданків."),
 C("współczynnik","коефіцієнт","w 7a²b → 7","Czynnik liczbowy jednomianu.","Числовий множник одночлена."),
 C("przykład","приклад","2a+5−a+3 = a+8","Grupujemy podobne i liczby.","Групуємо подібні і числа.")],
[R("Podobne wyrazy łączymy.","Подібні доданки об'єднуємо."),
 R("Dodajemy współczynniki.","Додаємо коефіцієнти."),
 R("Upraszczamy zapis.","Спрощуємо запис.")]),

P(19,"page19.html","B","DZIAŁANIA","ДІЇ","Równania","Рівняння",
"Równość z niewiadomą","Рівність із невідомим",
"Krok po kroku znajdź niewiadomą!","Крок за кроком знайди невідоме!",
[C("równanie","рівняння","x + 5 = 12","Równość z niewiadomą.","Рівність із невідомим."),
 C("niewiadoma","невідоме","x, y…","Liczba, którą mamy znaleźć.","Число, яке треба знайти."),
 C("rozwiązanie","розв'язок","x = 7","Wartość, która spełnia równanie.","Значення, що задовольняє рівняння."),
 C("metoda bilansowania","метод рівноваги","x+5=12 → x=12−5","To samo robimy po obu stronach.","Те саме робимо з обох боків."),
 C("przenoszenie","перенесення","+ staje się − po drugiej stronie","Zmiana strony = zmiana znaku.","Зміна сторони = зміна знака."),
 C("sprawdzenie","перевірка","7+5=12 ✓","Podstaw wynik do równania.","Підстав результат у рівняння.")],
[R("Cel: znaleźć niewiadomą.","Мета: знайти невідоме."),
 R("To samo po obu stronach.","Те саме з обох боків."),
 R("Zawsze sprawdzaj.","Завжди перевіряй.")]),
]

PAGES += [
P(20,"page20.html","E","MIARY","ВЕЛИЧИНИ","Długość","Довжина",
"Mierzymy, porównujemy i zamieniamy","Вимірюємо, порівнюємо й перетворюємо",
"I wiemy wszystko o długości!","І все знаємо про довжину!",
[C("jednostki długości","одиниці довжини","km hm dam m dm cm mm","Podstawowa w SP: metr (m).","Основна в школі: метр (m)."),
 C("zamiana","перетворення","1 km = 1000 m<br>1 m = 100 cm = 1000 mm","×/÷ przez 10, 100, 1000…","×/÷ на 10, 100, 1000…"),
 C("mierzenie","вимірювання","linijka · taśma · miarka","Przykładamy narzędzie od 0.","Прикладаємо інструмент від 0."),
 C("porównywanie","порівняння","1,2 m &gt; 95 cm","Najpierw te same jednostki.","Спочатку однакові одиниці."),
 C("obwód a długość","периметр і довжина","obwód = suma długości boków","Długość „dookoła” figury.","Довжина «навколо» фігури."),
 C("przykład","приклад","2,5 m = 250 cm = 2500 mm","Przesuwamy przecinek / zera.","Зсуваємо кому / нулі.")],
[R("1 m = 100 cm = 1000 mm.","1 m = 100 cm = 1000 mm."),
 R("1 km = 1000 m.","1 km = 1000 m."),
 R("Zamieniamy do jednej jednostki.","Перетворюємо до однієї одиниці.")]),

P(21,"page21.html","E","MIARY","ВЕЛИЧИНИ","Masa","Маса",
"Ile coś waży","Скільки що важить",
"Ważymy w gramach i kilogramach.","Зважуємо в грамах і кілограмах.",
[C("jednostki masy","одиниці маси","t · kg · g · mg","Podstawowa: kilogram (kg).","Основна: кілограм (kg)."),
 C("zamiana","перетворення","1 kg = 1000 g<br>1 t = 1000 kg","×/÷ przez 1000.","×/÷ на 1000."),
 C("porównywanie","порівняння","1 kg &gt; 800 g","Te same jednostki przed porównaniem.","Однакові одиниці перед порівнянням."),
 C("ważenie","зважування","waga szalkowa / elektroniczna","Masa to ilość materii.","Маса — кількість речовини."),
 C("przykłady","приклади","250 g = 0,25 kg<br>2,5 kg = 2500 g","Przecinek o 3 miejsca.","Кома на 3 місця."),
 C("w życiu","у житті","zakupy · przepisy · paczki","Czytamy etykiety z masą netto.","Читаємо етикетки з масою нетто.")],
[R("1 kg = 1000 g.","1 kg = 1000 g."),
 R("1 t = 1000 kg.","1 t = 1000 kg."),
 R("Porównuj w jednej jednostce.","Порівнюй в одній одиниці.")]),

P(22,"page22.html","E","MIARY","ВЕЛИЧИНИ","Objętość i litr","Об'єм і літр",
"Ile miejsca zajmuje ciecz / ciało","Скільки місця займає рідина / тіло",
"Litr pomaga mierzyć płyny!","Літр допомагає міряти рідини!",
[C("objętość","об'єм","cm³ · m³ · l · ml","Miara zajmowanego miejsca.","Міра зайнятого простору."),
 C("litr","літр","1 l = 1000 ml","Jednostka objętości płynów.","Одиниця об'єму рідин."),
 C("mililitr","мілілітр","1 ml = 1 cm³","Tysięczna część litra.","Тисячна частина літра."),
 C("przeliczanie","перетворення","2,5 l = 2500 ml","×/÷ 1000.","×/÷ 1000."),
 C("objętość bryły","об'єм тіла","V = a·b·c (prostopadłościan)","Długość × szerokość × wysokość.","Довжина × ширина × висота."),
 C("przykład","приклад","pudełko 2×3×4 cm → V=24 cm³","Mnożymy trzy wymiary.","Множимо три виміри.")],
[R("1 l = 1000 ml = 1000 cm³.","1 l = 1000 ml = 1000 cm³."),
 R("Objętość = ile miejsca.","Об'єм = скільки місця."),
 R("Płyny często w litrach.","Рідини часто в літрах.")]),

P(23,"page23.html","E","MIARY","ВЕЛИЧИНИ","Czas","Час",
"Jak długo coś trwa","Скільки щось триває",
"Planujemy i wiemy, ile trwa!","Плануємо і знаємо, скільки триває!",
[C("jednostki czasu","одиниці часу","1 h = 60 min<br>1 min = 60 s","Godzina, minuta, sekunda.","Година, хвилина, секунда."),
 C("zegar","годинник","12-godzinny / 24-godzinny","Pokazuje bieżącą godzinę.","Показує поточну годину."),
 C("upływ czasu","проміжок часу","14:20 → 15:05 = 45 min","Koniec minus początek.","Кінець мінус початок."),
 C("doba","доба","1 doba = 24 h","Pełny dzień i noc.","Повний день і ніч."),
 C("zamiana","перетворення","2,5 h = 2 h 30 min = 150 min","Uważaj na system 60, nie 100!","Увага: система 60, не 100!"),
 C("przykład","приклад","przerwa 15 min · lekcja 45 min",
   "W szkole: przerwa 15 minut, lekcja zwykle 45. Policz od dzwonka do dzwonka.",
   "У школі: перерва 15 хвилин, урок зазвичай 45. Порахуй від дзвінка до дзвінка.",
   klasa="klasy 1–3"),
 C("przykład dłuższy","довший приклад","od 8:45 do 10:10 = 1 h 25 min","Liczymy godziny, potem minuty.","Рахуємо години, потім хвилини.")],
[R("60 s = 1 min, 60 min = 1 h.","60 с = 1 хв, 60 хв = 1 год."),
 R("1 doba = 24 h.","1 доба = 24 год."),
 R("Czas liczymy w systemie 60.","Час рахуємо в системі 60.")]),

P(24,"page24.html","E","MIARY","ВЕЛИЧИНИ","Kalendarz","Календар",
"Doba, tydzień, miesiąc, rok","Доба, тиждень, місяць, рік",
"Pomaga planować ważne dni!","Допомагає планувати важливі дні!",
[C("jednostki kalendarzowe","календарні одиниці","doba · tydzień · miesiąc · rok","1 tydzień = 7 dni.","1 тиждень = 7 днів."),
 C("data","дата","18.07.2026","Dzień, miesiąc, rok.","День, місяць, рік."),
 C("urodziny i święta","день народження і свята","urodziny · ferie · Dzień Dziecka",
   "Kalendarz w kl. 1–3: kiedy urodziny, kiedy ferie, który dziś dzień tygodnia.",
   "Календар у кл. 1–3: коли день народження, коли канікули, який сьогодні день тижня.",
   klasa="klasy 1–3", media="cover"),
 C("rok przestępny","високосний рік","luty = 29 dni","Co 4 lata (z wyjątkami) — 366 dni.","Кожні 4 роки (з винятками) — 366 днів."),
 C("miesiące","місяці","28/29, 30 lub 31 dni","Pamiętaj długości miesięcy.","Пам'ятай довжину місяців."),
 C("kolejność dni","порядок днів","pn wt śr cz pt so nd","Tydzień ma 7 dni.","Тиждень має 7 днів."),
 C("przykład","приклад","od 28.02 do 3.03","Uważaj na długość lutego.","Увага на довжину лютого.")],
[R("7 dni = 1 tydzień.","7 днів = 1 тиждень."),
 R("Rok ≈ 365 dni.","Рік ≈ 365 днів."),
 R("Przestępny: +1 dzień w lutym.","Високосний: +1 день у лютому.")]),

P(25,"page25.html","E","MIARY","ВЕЛИЧИНИ","Temperatura","Температура",
"Jak ciepło albo jak zimno","Наскільки тепло чи холодно",
"Termometr mówi prawdę!","Термометр каже правду!",
[C("stopień Celsjusza","градус Цельсія","°C","Jednostka temperatury w szkole.","Одиниця температури в школі."),
 C("termometr","термометр","skala ze znakiem +/−","Pokazuje temperaturę.","Показує температуру."),
 C("powyżej / poniżej zera","вище / нижче нуля","+5°C · −8°C","Poniżej 0 — mróz (ujemne).","Нижче 0 — мороз (від'ємні)."),
 C("porównywanie","порівняння","−3°C &lt; 2°C","Jak liczby całkowite na osi.","Як цілі числа на прямій."),
 C("różnica temperatur","різниця температур","z −4 do +6 = 10°","|koniec − początek|.","|кінець − початок|."),
 C("w życiu","у житті","pogoda · piekarnik · ciało","Czytamy prognozy i przepisy.","Читаємо прогнози й рецепти.")],
[R("Jednostka: °C.","Одиниця: °C."),
 R("Ujemne = poniżej zera.","Від'ємні = нижче нуля."),
 R("Różnica = |t₂ − t₁|.","Різниця = |t₂ − t₁|.")]),

P(26,"page26.html","E","MIARY","ВЕЛИЧИНИ","Pieniądze","Гроші",
"Złote i grosze","Злоті й гроші",
"Liczymy, wydajemy, oszczędzamy!","Рахуємо, витрачаємо, заощаджуємо!",
[ C("złoty i grosz","злотий і грош","1 zł = 100 gr","Podstawowe jednostki w PL.","Основні одиниці в PL."),
 C("zapis","запис","12,50 zł","Złote przed przecinkiem, grosze po.","Злоті перед комою, гроші після."),
 C("5 zł na bułkę","5 zł на булочку","bułka 5 zł · reszta z 10 zł",
   "Jak w kl. 1–3: masz 10 zł, bułka kosztuje 5 zł — ile zostanie? Ile bułek kupisz za 15 zł?",
   "Як у кл. 1–3: маєш 10 zł, булочка коштує 5 zł — скільки лишиться? Скільки булочок купиш за 15 zł?",
   klasa="klasy 1–3", media="cover"),
 C("dodawanie / odejmowanie","додавання / віднімання","3,40 + 1,75 = 5,15","Jak ułamki dziesiętne.","Як десяткові дроби."),
 C("reszta","решта","10 − 7,30 = 2,70","Kwota dana − cena.","Дана сума − ціна."),
 C("porównywanie cen","порівняння цін","za 100 g / za 1 kg","Sprowadź do tej samej jednostki.","Зведи до тієї самої одиниці."),
 C("budżet","бюджет","przychód − wydatek","Planowanie wydatków.","Планування витрат.")],
[R("1 zł = 100 gr.","1 zł = 100 gr."),
 R("Liczymy jak dziesiętne.","Рахуємо як десяткові."),
 R("Sprawdzaj resztę.","Перевіряй решту.")]),

P(27,"page27.html","E","MIARY","ВЕЛИЧИНИ","Prędkość i skala","Швидкість і масштаб",
"Jak szybko i jak na mapie","Як швидко і як на карті",
"Prędkość = droga / czas!","Швидкість = шлях / час!",
[C("prędkość","швидкість","v = s/t","Droga podzielona przez czas.","Шлях поділений на час."),
 C("jednostki","одиниці","km/h · m/s","Kilometry na godzinę, metry na sekundę.","Кілометри на годину, метри на секунду."),
 C("droga i czas","шлях і час","s = v·t · t = s/v","Trzy wzory z trójkąta.","Три формули з трикутника."),
 C("skala mapy","масштаб карти","1:100 000","1 cm na mapie = 100 000 cm w terenie.","1 см на карті = 100 000 см на місцевості."),
 C("obliczanie odległości","обчислення відстані","3 cm · 100 000 = 3 km","Mnożymy miarę na mapie przez skalę.","Множимо міру на карті на масштаб."),
 C("przykład v","приклад v","120 km / 2 h = 60 km/h","Droga ÷ czas.","Шлях ÷ час.")],
[R("v = s/t, s = v·t, t = s/v.","v = s/t, s = v·t, t = s/v."),
 R("Skala 1:n — pomniejszenie.","Масштаб 1:n — зменшення."),
 R("Uważaj na jednostki.","Увага на одиниці.")]),

P(28,"page28.html","D","GEOMETRIA","ГЕОМЕТРІЯ","Figury płaskie (1)","Плоскі фігури (1)",
"Podstawowe figury na płaszczyźnie","Основні фігури на площині",
"Geometria wokół nas!","Геометрія навколо нас!",
[C("figury wokół nas","фігури навколо нас","okno = prostokąt · znak = trójkąt",
   "Szukaj figur w klasie i na podwórku: okno, drzwi, znak drogowy, piłka.",
   "Шукай фігури в класі й на подвір'ї: вікно, двері, дорожній знак, м'яч.",
   klasa="klasy 1–3", media="cover"),
 C("punkt","точка","A · B · C","Nie ma wymiarów — położenie.","Не має вимірів — положення."),
 C("prosta","пряма","nieskończona linia","Nie ma początku ani końca.","Не має початку й кінця."),
 C("odcinek","відрізок","AB","Część prostej między dwoma punktami.","Частина прямої між двома точками."),
 C("półprosta","півпряма","początek + kierunek","Ma początek, nie ma końca.","Має початок, не має кінця."),
 C("łamana","ламана","ciąg odcinków","Odcinki połączone końcami.","Відрізки, з'єднані кінцями."),
 C("wielokąt","многокутник","trójkąt · czworokąt…","Figura zamknięta z odcinków.","Замкнена фігура з відрізків.")],
[R("Punkt, prosta, odcinek, półprosta.","Точка, пряма, відрізок, півпряма."),
 R("Wielokąt = zamknięta łamana.","Многокутник = замкнена ламана."),
 R("Nazwy od wierzchołków.","Назви від вершин.")]),

P(29,"page29.html","D","GEOMETRIA","ГЕОМЕТРІЯ","Figury płaskie (2)","Плоскі фігури (2)",
"Trójkąty i czworokąty","Трикутники і чотирикутники",
"Rozpoznaj po bokach i kątach!","Розпізнай за сторонами й кутами!",
[C("figury wokół nas","фігури навколо нас","dach = trójkąт · drzwi = prostokąt",
   "Dach jak trójkąt, drzwi i zeszyt jak prostokąt, kafelek jak kwadrat.",
   "Дах як трикутник, двері й зошит як прямокутник, плитка як квадрат.",
   klasa="klasy 1–3", media="cover"),
 C("trójkąt","трикутник","3 boki, 3 kąty","Suma kątów = 180°.","Сума кутів = 180°."),
 C("rodzaje trójkątów","види трикутників","równoboczny · równoramienny · różnoboczny","Według boków; ostro-/prawo-/rozwartokątny wg kątów.","За сторонами; гостро-/прямо-/тупокутний за кутами."),
 C("kwadrat","квадрат","4 równe boki, 4 kąty proste","Szczególny prostokąt i romb.","Особливий прямокутник і ромб."),
 C("prostokąt","прямокутник","kąty proste, boki parami","Przeciwległe boki równe.","Протилежні сторони рівні."),
 C("romb / równoległobok","ромб / паралелограм","równoległe boki","Romb: wszystkie boki równe.","Ромб: усі сторони рівні."),
 C("trapez","трапеція","1 para boków równoległych","Dokładnie jedna para równoległych.","Рівно одна пара паралельних.")],
[R("Trójkąt: suma kątów 180°.","Трикутник: сума кутів 180°."),
 R("Kwadrat: boki równe + kąty 90°.","Квадрат: сторони рівні + кути 90°."),
 R("Ucz się cech charakterystycznych.","Вчи характерні ознаки.")]),
]

PAGES += [
P(30,"page30.html","D","GEOMETRIA","ГЕОМЕТРІЯ","Koło i okrąg","Коло і круг",
"Okrąg, koło i ich elementy","Коло, круг і їхні елементи",
"Środek, promień, średnica!","Центр, радіус, діаметр!",
[C("okrąg","коло","linia w równej odległości od środka","Tylko brzeg (obwód).","Лише межа (обвід)."),
 C("koło","круг","okrąg + wnętrze","Cała „tarcza”.","Увесь «диск»."),
 C("środek","центр","punkt O","Równo odległy od wszystkich punktów okręgu.","Однаково віддалений від усіх точок кола."),
 C("promień","радіус","r = OA","Odcinek od środka do okręgu.","Відрізок від центра до кола."),
 C("średnica","діаметр","d = 2r","Przechodzi przez środek; najdłuższa cięciwa.","Проходить через центр; найдовша хорда."),
 C("cięciwa","хорда","odcinek łączący 2 punkty okręgu","Średnica to szczególna cięciwa.","Діаметр — особлива хорда.")],
[R("d = 2r.","d = 2r."),
 R("Okrąg = linia; koło = + wnętrze.","Коло = лінія; круг = + внутрішня."),
 R("Wszystkie promienie równe.","Усі радіуси рівні.")]),

P(31,"page31.html","D","GEOMETRIA","ГЕОМЕТРІЯ","Długość okręgu i pole koła (π)","Довжина кола і площа круга (π)",
"Liczba π i wzory","Число π і формули",
"π ≈ 3,14 — zapamiętaj!","π ≈ 3,14 — запам'ятай!",
[C("liczba π","число π","π ≈ 3,14","Stosunek obwodu do średnicy.","Відношення довжини кола до діаметра."),
 C("długość okręgu","довжина кола","C = 2πr = πd","Obwód koła / długość okręgu.","Периметр круга / довжина кола."),
 C("pole koła","площа круга","P = πr²","Pole „tarczy”.","Площа «диска»."),
 C("przykład C","приклад C","r=5 → C≈2·3,14·5=31,4","Podstaw do wzoru.","Підстав у формулу."),
 C("przykład P","приклад P","r=5 → P≈3,14·25=78,5","Najpierw r², potem ×π.","Спочатку r², потім ×π."),
 C("zależność","залежність","gdy r×2, to C×2, P×4","Pole rośnie z kwadratem promienia.","Площа зростає з квадратом радіуса.")],
[R("π ≈ 3,14.","π ≈ 3,14."),
 R("C = 2πr.","C = 2πr."),
 R("P = πr².","P = πr².")]),

P(32,"page32.html","D","GEOMETRIA","ГЕОМЕТРІЯ","Kąt — pojęcie","Кут — поняття",
"Figura z dwóch półprostych o wspólnym początku","Фігура з двох півпрямих зі спільним початком",
"Wierzchołek i dwa ramiona!","Вершина і дві сторони!",
[C("kąt","кут","∠AOB","Dwie półproste ze wspólnym początkiem.","Дві півпрямі зі спільним початком."),
 C("wierzchołek","вершина","punkt O","Wspólny początek ramion.","Спільний початок сторін."),
 C("ramiona / strony","сторони","promienie OA, OB","Tworzą kąt.","Утворюють кут."),
 C("miara kąta","міра кута","stopień (°)","Pełny obrót = 360°.","Повний оберт = 360°."),
 C("kątomierz","кутомір","półkole ze skalą","Narzędzie do mierzenia kątów.","Інструмент для вимірювання кутів."),
 C("półobrót / obrót","півоберт / оберт","180° · 360°","Półprosta przeciwna; pełny obrót.","Протилежний промінь; повний оберт.")],
[R("Kąt = 2 promienie + wierzchołek.","Кут = 2 промені + вершина."),
 R("Jednostka: stopień (°).","Одиниця: градус (°)."),
 R("Pełny obrót = 360°.","Повний оберт = 360°.")]),

P(33,"page33.html","D","GEOMETRIA","ГЕОМЕТРІЯ","Rodzaje kątów","Види кутів",
"Kąt określamy miarą w stopniach","Кут визначаємо мірою в градусах",
"Od zerowego do pełnego!","Від нульового до повного!",
[C("kąt zerowy","нульовий кут","0°","Ramiona się pokrywają.","Сторони збігаються."),
 C("kąt ostry","гострий кут","0° &lt; α &lt; 90°","Mniejszy od prostego.","Менший за прямий."),
 C("kąt prosty","прямий кут","90°","Jak róg kartki / kwadratu.","Як кут аркуша / квадрата."),
 C("kąt rozwarty","тупий кут","90° &lt; α &lt; 180°","Większy od prostego, mniejszy od półpełnego.","Більший за прямий, менший за розгорнутий."),
 C("kąt półpełny","розгорнутий кут","180°","Ramiona tworzą prostą.","Сторони утворюють пряму."),
 C("kąt pełny","повний кут","360°","Pełny obrót.","Повний оберт.")],
[R("Ostry &lt; 90° &lt; rozwarty.","Гострий &lt; 90° &lt; тупий."),
 R("Prosty = 90°.","Прямий = 90°."),
 R("Półpełny = 180°, pełny = 360°.","Розгорнутий = 180°, повний = 360°.")]),

P(34,"page34.html","D","GEOMETRIA","ГЕОМЕТРІЯ","Pary kątów / kąty przy ∥","Пари кутів / кути при ∥",
"Dwie proste równoległe przecięte sieczną","Дві паралельні прямі, перетнуті січною",
"Wiele kątów ma równe miary!","Багато кутів мають рівні міри!",
[C("proste równoległe","паралельні прямі","a ∥ b","Nie przecinają się.","Не перетинаються."),
 C("sieczna","січна","prosta k","Przecina obie równoległe.","Перетинає обидві паралельні."),
 C("kąty odpowiadające","відповідні кути","równe przy a∥b","W tych samych „pozycjach” przy przecięciach.","В тих самих «позиціях» при перетинах."),
 C("naprzemianległe","навхрест лежачі","równe przy a∥b","Po przeciwnych stronach siecznej, między prostymi.","По протилежних боках січної, між прямими."),
 C("przyległe","суміжні","suma 180°","Wspólne ramię, suma półpełnego.","Спільна сторона, сума розгорнутого."),
 C("wierzchołkowe","вертикальні","równe","Naprzeciw siebie przy przecięciu.","Навпроти при перетині.")],
[R("Przy a∥b: odpowiadające równe.","При a∥b: відповідні рівні."),
 R("Naprzemianległe równe.","Навхрест рівні."),
 R("Przyległe: suma 180°.","Суміжні: сума 180°.")]),

P(35,"page35.html","D","GEOMETRIA","ГЕОМЕТРІЯ","Obwód i pole","Периметр і площа",
"Mierzymy dookoła i wewnątrz","Міряємо навколо і всередині",
"Geometria mierzy świat wokół nas!","Геометрія міряє світ навколо нас!",
[C("obwód","периметр","P = suma długości boków","Długość „dookoła”.","Довжина «навколо»."),
 C("pole","площа","jednostki: cm², m²","Miara powierzchni.","Міра поверхні."),
 C("prostokąt","прямокутник","Obw=2(a+b) · Pole=a·b","Bok × bok; 2×(dł+szer).","Сторона × сторона; 2×(довж+шир)."),
 C("kwadrat","квадрат","Obw=4a · Pole=a²","Wszystkie boki równe.","Усі сторони рівні."),
 C("trójkąt","трикутник","Pole = (a·h)/2","Podstawa × wysokość / 2.","Основа × висота / 2."),
 C("równoległobok","паралелограм","Pole = a·h","Podstawa × wysokość.","Основа × висота.")],
[R("Obwód = suma boków.","Периметр = сума сторін."),
 R("Pole prostokąta = a·b.","Площа прямокутника = a·b."),
 R("Pole trójkąta = (a·h)/2.","Площа трикутника = (a·h)/2.")]),

P(36,"page36.html","D","GEOMETRIA","ГЕОМЕТРІЯ","Bryły","Просторові тіла",
"Figury przestrzenne — mają objętość","Просторові фігури — мають об'єм",
"Poznaj najważniejsze bryły!","Познайомся з найважливішими тілами!",
[C("bryła","просторове тіло","3D: długość × szerokość × wysokość","Figura przestrzenna (ma objętość).","Просторова фігура (має об'єм)."),
 C("sześcian","куб","wszystkie krawędzie równe","6 kwadratowych ścian.","6 квадратних граней."),
 C("prostopadłościan","прямокутний паралелепіпед","V = a·b·c","Ściany — prostokąty.","Грані — прямокутники."),
 C("ostrosłup","піраміда","podstawa + ściany boczne → wierzchołek","Np. ostrosłup kwadratowy.","Напр. квадратна піраміда."),
 C("walec / stożek / kula","циліндр / конус / куля","okrągłe bryły","Walec: 2 podstawy koła; kula: wszystkie punkty w odległości r.","Циліндр: 2 основи-круги; куля: усі точки на відстані r."),
 C("objętość sześcianu","об'єм куба","V = a³","Krawędź do sześcianu.","Ребро до куба.")],
[R("Bryła ma objętość.","Тіло має об'єм."),
 R("Sześcian: V=a³.","Куб: V=a³."),
 R("Prostopadłościan: V=a·b·c.","Прямокутний паралелепіпед: V=a·b·c.")]),

P(37,"page37.html","D","GEOMETRIA","ГЕОМЕТРІЯ","Symetria","Симетрія",
"Porządek i harmonia figur","Порядок і гармонія фігур",
"Dostrzegaj piękno i porządek!","Помічай красу і порядок!",
[C("symetria","симетрія","odbicie / obrót","Figury wyglądają tak samo po odbiciu lub obrocie.","Фігури виглядають так само після відбиття або обертання."),
 C("oś symetrii","вісь симетрії","prosta „lustra”","Dzieli figurę na dwie lustrzane części.","Ділить фігуру на дві дзеркальні частини."),
 C("środek symetrii","центр симетрії","punkt obrotu 180°","Figura pokrywa się po obrocie o 180°.","Фігура збігається після повороту на 180°."),
 C("przykłady","приклади","kwadrat · koło · litery H, O, X","Wiele figur i liter jest symetrycznych.","Багато фігур і літер симетричні."),
 C("rysowanie","малювання","przenoś punkty prostopadle do osi","Odległość od osi po obu stronach równa.","Відстань від осі з обох боків рівна."),
 C("w przyrodzie","у природі","motyl · liść · płatki","Symetria wokół nas.","Симетрія навколо нас.")],
[R("Oś = „lustro”.","Вісь = «дзеркало»."),
 R("Odległości od osi równe.","Відстані від осі рівні."),
 R("Kwadrat ma 4 osie.","Квадрат має 4 осі.")]),

P(38,"page38.html","D","GEOMETRIA","ГЕОМЕТРІЯ","Współrzędne","Координати",
"Układ współrzędnych na płaszczyźnie","Система координат на площині",
"X pozioma, Y pionowa!","X горизонтальна, Y вертикальна!",
[C("układ współrzędnych","система координат","osie X i Y","Do opisu położenia punktów.","Для опису положення точок."),
 C("oś X","вісь X","pozioma","W prawo +, w lewo −.","Праворуч +, ліворуч −."),
 C("oś Y","вісь Y","pionowa","W górę +, w dół −.","Вгору +, вниз −."),
 C("punkt (x, y)","точка (x, y)","A(3, 2)","Najpierw x, potem y.","Спочатку x, потім y."),
 C("ćwiartki","чверті","I, II, III, IV","Zależą od znaków x i y.","Залежать від знаків x і y."),
 C("początek układu","початок координат","O(0, 0)","Przecięcie osi.","Перетин осей.")],
[R("Zapis: (x, y).","Запис: (x, y)."),
 R("X w prawo +, Y w górę +.","X праворуч +, Y вгору +."),
 R("O(0,0) — początek.","O(0,0) — початок.")]),

P(39,"page39.html","F","DANE","ДАНІ","Statystyka (1)","Статистика (1)",
"Zbieramy, porządkujemy i analizujemy dane","Збираємо, упорядковуємо й аналізуємо дані",
"Liczby i wykresy opisują świat!","Числа і графіки описують світ!",
[C("statystyka","статистика","dane → wnioski","Dział opisujący zjawiska liczbami i wykresami.","Розділ, що описує явища числами і графіками."),
 C("dane","дані","wyniki pomiarów / ankiet","Informacje zebrane do analizy.","Інформація, зібрана для аналізу."),
 C("etapy","етапи","zbierz → uporządkuj → przedstaw → analizuj","Kolejność pracy ze statystyką.","Порядок роботи зі статистикою."),
 C("tabela","таблиця","wiersze i kolumny","Porządkuje dane.","Упорядковує дані."),
 C("wykres słupkowy","стовпчикова діаграма","słupki wysokości = wartości","Porównanie kategorii.","Порівняння категорій."),
 C("wykres kołowy","кругова діаграма","części koła = udziały","Pokazuje części całości.","Показує частини цілого.")],
[R("Dane zbieramy i porządkujemy.","Дані збираємо й упорядковуємо."),
 R("Wykres pomaga zobaczyć.","Графік допомагає побачити."),
 R("Analizuj → wnioski.","Аналізуй → висновки.")]),

P(40,"page40.html","F","DANE","ДАНІ","Statystyka (2)","Статистика (2)",
"Średnia, mediana, moda","Середнє, медіана, мода",
"Zrozum dane i wyciągnij wnioski!","Зрозумій дані і зроби висновки!",
[C("średnia arytmetyczna","середнє арифметичне","suma ÷ liczba danych","Suma wszystkich wartości / ich liczba.","Сума всіх значень / їх кількість."),
 C("mediana","медіана","wartość środkowa","Po uporządkowaniu — środkowa (lub średnia dwóch środkowych).","Після впорядкування — середня (або середнє двох середніх)."),
 C("moda","мода","najczęstsza wartość","Wartość występująca najczęściej.","Значення, що трапляється найчастіше."),
 C("przykład średniej","приклад середнього","(2+5+5+8)/4 = 5","Dodaj i podziel.","Додай і поділи."),
 C("przykład mediany","приклад медіани","2,5,5,8 → (5+5)/2=5","Uporządkuj, weź środek.","Упорядкуй, візьми середину."),
 C("przykład mody","приклад моди","2,5,5,8 → moda=5","Szukaj najczęstszej.","Шукай найчастішу.")],
[R("Średnia = suma / n.","Середнє = сума / n."),
 R("Mediana = środek po sortowaniu.","Медіана = середина після сортування."),
 R("Moda = najczęstsza.","Мода = найчастіша.")]),

P(41,"page41.html","F","DANE","ДАНІ","Kombinatoryka i prawdopodobieństwo","Комбінаторика і ймовірність",
"Liczenie możliwości i szans","Підрахунок можливостей і шансів",
"Policz wszystkie możliwości!","Порахуй усі можливості!",
[C("kombinatoryka","комбінаторика","ile sposobów?","Liczenie sposobów wyboru i ułożenia.","Підрахунок способів вибору й упорядкування."),
 C("zasada mnożenia","правило множення","3·4 = 12 dróg","Gdy etapy niezależne — mnożymy.","Коли етапи незалежні — множимо."),
 C("zasada dodawania","правило додавання","albo… albo…","Gdy wykluczające się opcje — dodajemy.","Коли взаємовиключні варіанти — додаємо."),
 C("drzewko możliwości","дерево можливостей","gałęzie wyborów","Rysunek etapów: każdy wybór to nowa gałąź.","Малюнок етапів: кожен вибір — нова гілка."),
 C("prawdopodobieństwo","ймовірність","P = korzystne / wszystkie","Szansa zdarzenia od 0 do 1.","Шанс події від 0 до 1."),
 C("przykład P","приклад P","kostka: P(6)=1/6","1 korzystny / 6 możliwych.","1 сприятливий / 6 можливих.")],
[R("Mnożymy etapy niezależne.","Множимо незалежні етапи."),
 R("P = korzystne/wszystkie.","P = сприятливі/усі."),
 R("0 ≤ P ≤ 1.","0 ≤ P ≤ 1.")]),

P(42,"page42.html","F","DANE","ДАНІ","Ściąga znaków","Шпаргалка знаків",
"Znaki działań, porównań i własności","Знаки дій, порівнянь і властивостей",
"Szybko zapisz matematykę!","Швидко запиши математику!",
[C("+ plus / dodawanie","плюс / додавання","3 + 5","Dodajemy.","Додаємо."),
 C("− minus / odejmowanie","мінус / віднімання","9 − 4","Odejmujemy.","Віднімаємо."),
 C("× · mnożenie","множення","4 × 3","Mnożymy.","Множимо."),
 C(": / dzielenie","ділення","12 : 3","Dzielimy.","Ділимо."),
 C("= &lt; &gt; ≤ ≥ ≠","порівняння","5 = 5 · 3 &lt; 7","Równe, mniejsze, większe…","Рівне, менше, більше…"),
 C("() [] √ ² % π ∠ ∥","inne znaki","nawiasy, pierwiastek, potęga, %, pi, kąt, równoległość","Znaki specjalne w matematyce.","Спеціальні знаки в математиці.","wide-3")],
[R("Znaki skracają zapis.","Знаки скорочують запис."),
 R("Najpierw naucz się + − × : =.","Спочатку вивчи + − × : =."),
 R("Potem: √ ² % π ∠ ∥.","Потім: √ ² % π ∠ ∥.")]),
]

from pages_new_43_60 import build_new_pages

PAGES += build_new_pages()

from pages_new_61 import build_page_61

PAGES.append(build_page_61())

from pages_new_extra import build_extra_pages

PAGES += build_extra_pages()

from handbook_enrich import apply as _apply_handbook

_apply_handbook(PAGES)

from structure_apply import apply_phase_a

PAGES[:] = apply_phase_a(PAGES)

