# -*- coding: utf-8 -*-
"""
Nowe strony 43–60: domknięcie podstawy programowej SP (kl. 1–8).
Treść: poziom strony-wzorca (PL nauczyciel + UA + metodyka).
"""


def C(pl, ua, visual, def_pl, def_ua, wide="", **kwargs):
    d = {"pl": pl, "ua": ua, "visual": visual, "def_pl": def_pl, "def_ua": def_ua, **kwargs}
    if wide:
        d["wide"] = wide
    return d


def R(pl, ua, formula=""):
    d = {"pl": pl, "ua": ua}
    if formula:
        d["formula"] = formula
    return d


def P(n, file, cat, cat_pl, cat_ua, title_pl, title_ua, intro_pl, intro_ua, tip_pl, tip_ua, cards, remember):
    return {
        "n": n, "file": file, "cat": cat, "cat_pl": cat_pl, "cat_ua": cat_ua,
        "title_pl": title_pl, "title_ua": title_ua,
        "intro_pl": intro_pl, "intro_ua": intro_ua,
        "tip_pl": tip_pl, "tip_ua": tip_ua,
        "cards": cards, "remember": remember,
    }


def build_new_pages():
    return [
        # ——— 43 ———
        P(
            43, "page43.html", "B", "DZIAŁANIA", "ДІЇ",
            "Działania pisemne i szacowanie", "Письмові дії й оцінювання",
            "Liczymy „w słupku” i sprawdzamy, czy wynik ma sens.",
            "Рахуємо «стовпчиком» і перевіряємо, чи результат має сенс.",
            "Najpierw oszacuj, potem licz dokładnie!",
            "Спочатку оціни, потім рахуй точно!",
            [
                C("działanie pisemne", "письмова дія", "słupek + − × :",
                  "Działanie pisemne to liczenie w słupku — cyfra pod cyfrą, od prawej do lewej.",
                  "Письмова дія — рахунок стовпчиком: цифра під цифрою, справа наліво.",
                  rule="Ustaw liczby równo (jedności pod jednościami). Zaczynaj od prawej kolumny.",
                  rule_ua="Став числа рівно (одиниці під одиницями). Починай з правого стовпця.",
                  media="diagram"),
                C("dodawanie pisemne", "письмове додавання", "47 + 28 = 75",
                  "Dodajemy kolumnami: najpierw jedności, potem dziesiątki — z przeniesieniem, gdy trzeba.",
                  "Додаємо стовпцями: спочатку одиниці, потім десятки — з переносом, коли треба.",
                  rule="Gdy suma w kolumnie ≥ 10, zapisujesz jedność wyniku, a 1 przenosisz w lewo.",
                  rule_ua="Коли сума в стовпці ≥ 10, пишеш одиницю результату, а 1 переносиш ліворуч.",
                  media="diagram"),
                C("odejmowanie pisemne", "письмове віднімання", "52 − 17 = 35",
                  "Odejmujemy kolumnami. Gdy w kolumnie „za mało” — pożyczamy z sąsiada z lewej.",
                  "Віднімаємо стовпцями. Коли в стовпці «замало» — позичаємо в сусіда зліва.",
                  rule="Pożyczka: jedna dziesiątka staje się 10 jednościami. Sprawdź wynik dodawaniem!",
                  rule_ua="Позичка: один десяток стає 10 одиницями. Перевір результат додаванням!",
                  media="diagram"),
                C("mnożenie pisemne", "письмове множення", "23 × 4 = 92",
                  "Mnożymy każdą cyfrę mnożnej przez mnożnik — z przeniesieniem, jak przy dodawaniu.",
                  "Множимо кожну цифру множеного на множник — з переносом, як при додаванні.",
                  rule="Przy mnożniku dwucyfrowym: osobno × jedności, osobno × dziesiątki (z przesunięciem), na końcu dodaj.",
                  rule_ua="При двоцифровому множнику: окремо × одиниці, окремо × десятки (зі зсувом), наприкінці додай.",
                  media="diagram"),
                C("dzielenie pisemne", "письмове ділення", "84 : 4 = 21",
                  "Dzielenie pisemne: ile razy dzielnik mieści się w kolejnych „kawałkach” dzielnej.",
                  "Письмове ділення: скільки разів дільник вміщується в наступних «шматках» діленого.",
                  rule="Krok: weź cyfry → ile razy → zapisz → reszta → ściągnij następną cyfrę.",
                  rule_ua="Крок: візьми цифри → скільки разів → запиши → остача → знеси наступну цифру.",
                  media="diagram"),
                C("szacowanie", "оцінювання", "47+28 ≈ 50+30 = 80",
                  "Szacowanie to szybkie przybliżenie wyniku — zanim policzysz dokładnie.",
                  "Оцінювання — швидке наближення результату ще до точного рахунку.",
                  rule="Zaokrąglij do wygodnych liczb, policz w pamięci, porównaj z dokładnym wynikiem.",
                  rule_ua="Округли до зручних чисел, порахуй у пам'яті, порівняй із точним результатом.",
                  media="cover"),
            ],
            [
                R("W słupku: jedności pod jednościami.", "У стовпчику: одиниці під одиницями."),
                R("Najpierw oszacuj — potem licz.", "Спочатку оціни — потім рахуй.", "≈"),
                R("Odejmowanie sprawdź dodawaniem.", "Віднімання перевір додаванням."),
            ],
        ),

        # ——— 44 ———
        P(
            44, "page44.html", "B", "DZIAŁANIA", "ДІЇ",
            "Rozdzielność mnożenia", "Розподільна властивість множення",
            "Mnożenie „rozdzielamy” na dodawanie — łatwiej liczyć w pamięci.",
            "Множення «розподіляємо» на додавання — легше рахувати в пам'яті.",
            "a·(b+c) = a·b + a·c",
            "a·(b+c) = a·b + a·c",
            [
                C("rozdzielność", "розподільність", "a·(b+c)=a·b+a·c",
                  "Rozdzielność: mnożenie „wchodzi” do nawiasu z sumą — mnożysz każdy składnik osobno.",
                  "Розподільність: множення «заходить» у дужки із сумою — множиш кожен доданок окремо.",
                  rule="a·(b+c) = a·b + a·c. Działa też przy odejmowaniu: a·(b−c)=a·b−a·c.",
                  rule_ua="a·(b+c) = a·b + a·c. Працює і при відніманні: a·(b−c)=a·b−a·c.",
                  media="diagram"),
                C("przykład liczbowy", "числовий приклад", "6·(10+3)=6·10+6·3",
                  "Zamiast 6·13 liczysz 6·10 + 6·3 = 60+18 = 78 — wygodniej w pamięci.",
                  "Замість 6·13 рахуєш 6·10 + 6·3 = 60+18 = 78 — зручніше в пам'яті.",
                  rule="Rozbij trudniejszą liczbę na sumę „ładnych” części (10+3, 20+4…).",
                  rule_ua="Розбий складніше число на суму «гарних» частин (10+3, 20+4…).",
                  media="cover"),
                C("odwrotnie: wyłączanie", "навпаки: винесення", "4·7+4·3=4·(7+3)",
                  "Gdy oba składniki mają wspólny czynnik — możesz go wyłączyć przed nawias.",
                  "Коли обидва доданки мають спільний множник — можна винести його перед дужки.",
                  rule="a·b + a·c = a·(b+c). To ta sama rozdzielność „w drugą stronę”.",
                  rule_ua="a·b + a·c = a·(b+c). Та сама розподільність «в інший бік».",
                  media="diagram"),
                C("w geometrii", "у геометрії", "pole = a·(b+c)",
                  "Pole prostokąta złożonego z dwóch części = suma pól — to też rozdzielność.",
                  "Площа прямокутника з двох частин = сума площ — це теж розподільність.",
                  rule="Duży prostokąt a na (b+c): P = a·(b+c) = a·b + a·c.",
                  rule_ua="Великий прямокутник a на (b+c): P = a·(b+c) = a·b + a·c.",
                  media="photo"),
                C("z literami", "з літерами", "x(x+2)=x²+2x",
                  "W algebrze rozdzielność otwiera nawiasy: mnożysz literę przez każdy wyraz.",
                  "В алгебрі розподільність розкриває дужки: множиш літеру на кожен доданок.",
                  rule="x·(x+2) = x·x + x·2 = x² + 2x. Nie zapomnij o obu częściach!",
                  rule_ua="x·(x+2) = x·x + x·2 = x² + 2x. Не забудь обидві частини!",
                  media="cover"),
            ],
            [
                R("a·(b+c) = a·b + a·c", "a·(b+c) = a·b + a·c", "rozdzielność"),
                R("Pomaga w rachunku pamięciowym.", "Допомагає в усному рахунку."),
                R("Otwiera nawiasy w algebrze.", "Розкриває дужки в алгебрі."),
            ],
        ),

        # ——— 45 ———
        P(
            45, "page45.html", "B", "DZIAŁANIA", "ДІЇ",
            "NWD, NWW i rozkład na czynniki", "НСД, НСК і розклад на множники",
            "Szukamy wspólnych dzielników i wielokrotności — klucz do ułamków.",
            "Шукаємо спільні дільники й кратні — ключ до дробів.",
            "Czynniki pierwsze jak klocki liczby!",
            "Прості множники як кубики числа!",
            [
                C("czynnik pierwszy", "простий множник", "12 = 2·2·3",
                  "Czynnik pierwszy to liczba pierwsza w rozkładzie — „klocek”, z którego budujesz liczbę.",
                  "Простий множник — просте число в розкладі: «кубик», з якого будуєш число.",
                  rule="Rozkładaj przez kolejne liczby pierwsze: 2, 3, 5, 7… aż zostanie 1.",
                  rule_ua="Розкладайте через наступні прості: 2, 3, 5, 7… доки не лишиться 1.",
                  media="diagram"),
                C("rozkład na czynniki", "розклад на множники", "60=2²·3·5",
                  "Rozkład na czynniki pierwsze zapisuje liczbę jako iloczyn liczb pierwszych.",
                  "Розклад на прості множники записує число як добуток простих чисел.",
                  rule="Drzewko lub dzielenie „schodkami”: 60÷2=30÷2=15÷3=5.",
                  rule_ua="Дерево або ділення «сходинками»: 60÷2=30÷2=15÷3=5.",
                  media="diagram"),
                C("NWD", "НСД", "NWD(12,18)=6",
                  "NWD (największy wspólny dzielnik) — największa liczba, która dzieli obie liczby.",
                  "НСД (найбільший спільний дільник) — найбільше число, що ділить обидва числа.",
                  rule="Z rozkładu: weź wspólne czynniki w najmniejszych potęgach. Albo: kolejne dzielenie.",
                  rule_ua="З розкладу: візьми спільні множники в найменших степенях. Або: послідовне ділення.",
                  media="cover"),
                C("NWW", "НСК", "NWW(4,6)=12",
                  "NWW (najmniejsza wspólna wielokrotność) — najmniejsza liczba podzielna przez obie.",
                  "НСК (найменше спільне кратне) — найменше число, кратне обом.",
                  rule="Z rozkładu: wszystkie czynniki w największych potęgach. Albo: NWW = a·b / NWD.",
                  rule_ua="З розкладу: усі множники в найбільших степенях. Або: НСК = a·b / НСД.",
                  media="cover"),
                C("liczba złożona", "складене число", "4, 6, 8, 9, 15…",
                  "Liczba złożona ma więcej niż dwa dzielniki — nie jest pierwsza ani 1.",
                  "Складене число має більше ніж два дільники — не просте і не 1.",
                  rule="1 nie jest pierwsza ani złożona. Pierwsza: dokładnie dwa dzielniki (1 i ona sama).",
                  rule_ua="1 не просте і не складене. Просте: рівно два дільники (1 і воно саме).",
                  media="diagram"),
                C("do ułamków", "для дробів", "skracanie przez NWD",
                  "NWD skraca ułamki. NWW pomaga znaleźć wspólny mianownik.",
                  "НСД скорочує дроби. НСК допомагає знайти спільний знаменник.",
                  rule="12/18 → NWD=6 → 2/3. Wspólny mianownik 1/4 i 1/6 → NWW(4,6)=12.",
                  rule_ua="12/18 → НСД=6 → 2/3. Спільний знаменник 1/4 і 1/6 → НСК(4,6)=12.",
                  media="photo"),
            ],
            [
                R("Rozkład = iloczyn liczb pierwszych.", "Розклад = добуток простих."),
                R("NWD — największy wspólny dzielnik.", "НСД — найбільший спільний дільник.", "NWD"),
                R("NWW — najmniejsza wspólna wielokrotność.", "НСК — найменше спільне кратне.", "NWW"),
            ],
        ),

        # ——— 46 ———
        P(
            46, "page46.html", "C", "UŁAMKI", "ДРОБИ",
            "Ułamek liczby i całość z części", "Дріб числа й ціле з частини",
            "Ile to jest 3/4 z liczby? Jak znaleźć całość, gdy znasz część?",
            "Скільки це 3/4 від числа? Як знайти ціле, коли знаєш частину?",
            "Część ↔ całość — dwa kierunki!",
            "Частина ↔ ціле — два напрями!",
            [
                C("ułamek liczby", "дріб числа", "3/4 z 20 = 15",
                  "Ułamek liczby to część tej liczby: dzielisz na równe części (mianownik) i bierzesz kilka (licznik).",
                  "Дріб числа — частина цього числа: ділиш на рівні частини (знаменник) і береш кілька (чисельник).",
                  rule="p/q z a = (a : q) · p  albo  (a · p) : q.",
                  rule_ua="p/q від a = (a : q) · p  або  (a · p) : q.",
                  media="diagram"),
                C("przykład: część z całości", "приклад: частина від цілого", "2/5 z 30",
                  "30 cukierków, bierzesz 2/5: 30:5=6, 6·2=12. Albo 30·2=60, 60:5=12.",
                  "30 цукерок, береш 2/5: 30:5=6, 6·2=12. Або 30·2=60, 60:5=12.",
                  rule="Najpierw znajdź jedną część (a:q), potem pomnóż przez p.",
                  rule_ua="Спочатку знайди одну частину (a:q), потім помнож на p.",
                  media="photo"),
                C("całość z części", "ціле з частини", "3/4 = 15 → całość 20",
                  "Znasz część (ułamek) i jej wartość — szukasz całej liczby.",
                  "Знаєш частину (дріб) і її значення — шукаєш усе число.",
                  rule="Jedna część = wartość : licznik. Całość = jedna część · mianownik.",
                  rule_ua="Одна частина = значення : чисельник. Ціле = одна частина · знаменник.",
                  media="diagram"),
                C("powiększenie o część", "збільшення на частину", "o 1/4 więcej",
                  "Powiększenie o ułamek: dodajesz tę część do całości (jak +25%).",
                  "Збільшення на дріб: додаєш цю частину до цілого (як +25%).",
                  rule="Nowa = a + (p/q)·a = a·(1 + p/q). Np. o 1/4 więcej → ×5/4.",
                  rule_ua="Нове = a + (p/q)·a = a·(1 + p/q). Напр. на 1/4 більше → ×5/4.",
                  media="cover"),
                C("pomniejszenie o część", "зменшення на частину", "o 1/5 mniej",
                  "Pomniejszenie o ułamek: odejmujesz tę część od całości.",
                  "Зменшення на дріб: віднімаєш цю частину від цілого.",
                  rule="Nowa = a − (p/q)·a = a·(1 − p/q). Np. o 1/5 mniej → ×4/5.",
                  rule_ua="Нове = a − (p/q)·a = a·(1 − p/q). Напр. на 1/5 менше → ×4/5.",
                  media="cover"),
            ],
            [
                R("Część z a: (a:q)·p.", "Частина від a: (a:q)·p."),
                R("Z części → znajdź 1 część → całość.", "З частини → знайди 1 частину → ціле."),
                R("O część więcej/mniej = mnożnik (1±p/q).", "На частину більше/менше = множник (1±p/q)."),
            ],
        ),

        # ——— 47 ———
        P(
            47, "page47.html", "E", "MIARY", "ВЕЛИЧИНИ",
            "Wyrażenia dwumianowane", "Двочленні вирази мір",
            "2 m 15 cm — dwa miana naraz. Zamieniamy na jedną jednostkę.",
            "2 м 15 см — дві одиниці разом. Перетворюємо на одну одиницю.",
            "Jedna miara = łatwiejsze liczenie!",
            "Одна міра = легший рахунок!",
            [
                C("wyrażenie dwumianowane", "двочленний вираз", "2 m 15 cm",
                  "Wyrażenie dwumianowane łączy dwie jednostki tej samej wielkości (np. m i cm).",
                  "Двочленний вираз з'єднує дві одиниці тієї самої величини (напр. м і см).",
                  rule="Czytamy: „2 metry i 15 centymetrów”. Potem zamieniamy do jednej jednostki.",
                  rule_ua="Читаємо: «2 метри і 15 сантиметрів». Потім переводимо в одну одиницю.",
                  media="cover"),
                C("zamiana na mniejszą", "на меншу одиницю", "2 m 15 cm = 215 cm",
                  "Na mniejszą jednostkę: większą część × ile mniejszych w jednej + reszta.",
                  "На меншу одиницю: більшу частину × скільки менших в одній + решта.",
                  rule="2 m 15 cm = 2·100 + 15 = 215 cm. 3 kg 200 g = 3200 g.",
                  rule_ua="2 м 15 см = 2·100 + 15 = 215 см. 3 кг 200 г = 3200 г.",
                  media="diagram"),
                C("zamiana na większą", "на більшу одиницю", "215 cm = 2 m 15 cm",
                  "Na większą: dzielisz z resztą — iloraz to większa jednostka, reszta zostaje.",
                  "На більшу: ділиш з остачею — частка це більша одиниця, остача лишається.",
                  rule="215 cm = 2 m 15 cm, bo 215:100 = 2 reszty 15.",
                  rule_ua="215 см = 2 м 15 см, бо 215:100 = 2 остача 15.",
                  media="diagram"),
                C("i ułamek dziesiętny", "і десятковий дріб", "2 m 15 cm = 2,15 m",
                  "Często zapisujemy jako ułamek dziesiętny w większej jednostce.",
                  "Часто записуємо як десятковий дріб у більшій одиниці.",
                  rule="2 m 15 cm = 2,15 m. 1 h 30 min = 1,5 h.",
                  rule_ua="2 м 15 см = 2,15 м. 1 год 30 хв = 1,5 год.",
                  media="cover"),
                C("w życiu", "у житті", "wzrost, czas, masa",
                  "Wzrost 1 m 42 cm, film 1 h 45 min, mąka 1 kg 250 g — to wyrażenia dwumianowane.",
                  "Зріст 1 м 42 см, фільм 1 год 45 хв, борошно 1 кг 250 г — двочленні вирази.",
                  rule="Przed dodawaniem zamień do tej samej jednostki — inaczej łatwo o błąd.",
                  rule_ua="Перед додаванням переведи в ту саму одиницю — інакше легко помилитись.",
                  media="photo"),
            ],
            [
                R("Dwie jednostki → zamień do jednej.", "Дві одиниці → переведи в одну."),
                R("Na cm: metry ×100 + cm.", "У см: метри ×100 + см."),
                R("Często = zapis dziesiętny.", "Часто = десятковий запис."),
            ],
        ),

        # ——— 48 ———
        P(
            48, "page48.html", "D", "GEOMETRIA", "ГЕОМЕТРІЯ",
            "Proste prostopadłe i odległość", "Перпендикулярні прямі й відстань",
            "Prostopadłe tworzą kąt prosty. Odległość — najkrótsza droga.",
            "Перпендикулярні утворюють прямий кут. Відстань — найкоротший шлях.",
            "⊥ jak róg kartki!",
            "⊥ як кут аркуша!",
            [
                C("proste prostopadłe", "перпендикулярні прямі", "a ⊥ b",
                  "Proste prostopadłe przecinają się pod kątem prostym (90°).",
                  "Перпендикулярні прямі перетинаються під прямим кутом (90°).",
                  rule="Zapis: a ⊥ b. Na rysunku często znaczek □ w kącie.",
                  rule_ua="Запис: a ⊥ b. На малюнку часто значок □ у куті.",
                  media="diagram"),
                C("odcinki prostopadłe", "перпендикулярні відрізки", "AB ⊥ CD",
                  "Odcinki są prostopadłe, gdy leżą na prostych prostopadłych (lub tworzą 90°).",
                  "Відрізки перпендикулярні, коли лежать на перпендикулярних прямих (або утворюють 90°).",
                  rule="Boki kwadratu i prostokąta są parami prostopadłe.",
                  rule_ua="Сторони квадрата й прямокутника попарно перпендикулярні.",
                  media="cover"),
                C("odległość punktu od prostej", "відстань від точки до прямої", "najkrótszy odcinek ⊥",
                  "Odległość punktu od prostej to długość prostopadłej od punktu do tej prostej.",
                  "Відстань від точки до прямої — довжина перпендикуляра від точки до цієї прямої.",
                  rule="Z punktu prowadzisz prostopadłą do prostej — jej długość = odległość.",
                  rule_ua="З точки проводиш перпендикуляр до прямої — його довжина = відстань.",
                  media="diagram"),
                C("wysokość w figurze", "висота у фігурі", "h ⊥ podstawa",
                  "Wysokość trójkąta lub równoległoboku to prostopadła do podstawy.",
                  "Висота трикутника або паралелограма — перпендикуляр до основи.",
                  rule="Przy obliczaniu pola: zawsze wysokość jest ⊥ do wybranej podstawy.",
                  rule_ua="При обчисленні площі: висота завжди ⊥ до вибраної основи.",
                  media="photo"),
                C("w życiu", "у житті", "ściana ⊥ podłoga",
                  "Ściana i podłoga, róg zeszytu, skrzyżowanie „na krzyż” pod kątem prostym.",
                  "Стіна і підлога, кут зошита, перехрестя «навхрест» під прямим кутом.",
                  rule="Kątomierz lub ekierka pomagają sprawdzić, czy naprawdę 90°.",
                  rule_ua="Кутомір або косинець допомагають перевірити, чи справді 90°.",
                  media="photo"),
            ],
            [
                R("⊥ oznacza kąt 90°.", "⊥ означає кут 90°.", "⊥"),
                R("Odległość = długość prostopadłej.", "Відстань = довжина перпендикуляра."),
                R("Wysokość figury jest ⊥ do podstawy.", "Висота фігури ⊥ до основи."),
            ],
        ),

        # ——— 49 ———
        P(
            49, "page49.html", "D", "GEOMETRIA", "ГЕОМЕТРІЯ",
            "Suma kątów w trójkącie", "Сума кутів у трикутнику",
            "W każdym trójkącie suma kątów wewnętrznych to 180°.",
            "У кожному трикутнику сума внутрішніх кутів — 180°.",
            "Znasz dwa kąty → trzeci łatwy!",
            "Знаєш два кути → третій легкий!",
            [
                C("twierdzenie", "теорема", "α+β+γ = 180°",
                  "Suma miar kątów wewnętrznych dowolnego trójkąta wynosi zawsze 180°.",
                  "Сума мір внутрішніх кутів будь-якого трикутника завжди 180°.",
                  rule="Zapamiętaj jak prawo: w trójkącie kąty „domykają się” do półpełnego.",
                  rule_ua="Запам'ятай як закон: у трикутнику кути «замикаються» до розгорнутого.",
                  media="diagram"),
                C("obliczanie trzeciego", "обчислення третього", "40°+60°+? =180°",
                  "Gdy znasz dwa kąty, trzeci = 180° minus ich suma.",
                  "Коли знаєш два кути, третій = 180° мінус їхня сума.",
                  rule="? = 180° − (α+β). Przykład: 40+60=100 → trzeci = 80°.",
                  rule_ua="? = 180° − (α+β). Приклад: 40+60=100 → третій = 80°.",
                  media="cover"),
                C("trójkąt prostokątny", "прямокутний трикутник", "90° + … + … =180°",
                  "W trójkącie prostokątnym jeden kąt ma 90° — pozostałe dwa sumują się do 90°.",
                  "У прямокутному трикутнику один кут 90° — решта два дають у сумі 90°.",
                  rule="Ostre kąty w prostokątnym: α+β=90°. Są dopełniające.",
                  rule_ua="Гострі кути в прямокутному: α+β=90°. Вони доповняльні.",
                  media="diagram"),
                C("równoramienny", "рівнобедрений", "kąty przy podstawie równe",
                  "W trójkącie równoramiennym kąty przy podstawie są równe.",
                  "У рівнобедреному трикутнику кути при основі рівні.",
                  rule="Jeśli kąt przy wierzchołku = 40°, to przy podstawie: (180−40):2 = 70° każdy.",
                  rule_ua="Якщо кут при вершині = 40°, то при основі: (180−40):2 = 70° кожен.",
                  media="cover"),
                C("nierówność trójkąta", "нерівність трикутника", "a+b > c",
                  "Z trzech odcinków zbudujesz trójkąt tylko gdy suma dwóch krótszych > najdłuższego.",
                  "З трьох відрізків збудуєш трикутник лише коли сума двох коротших > найдовшого.",
                  rule="Sprawdź: a+b>c, a+c>b, b+c>a. Inaczej „nie domknie się”.",
                  rule_ua="Перевір: a+b>c, a+c>b, b+c>a. Інакше «не замкнеться».",
                  media="photo"),
            ],
            [
                R("W trójkącie α+β+γ = 180°.", "У трикутнику α+β+γ = 180°.", "180°"),
                R("Trzeci kąt = 180° − suma dwóch.", "Третій кут = 180° − сума двох."),
                R("a+b > c — warunek trójkąta.", "a+b > c — умова трикутника."),
            ],
        ),

        # ——— 50 ———
        P(
            50, "page50.html", "D", "GEOMETRIA", "ГЕОМЕТРІЯ",
            "Pole rombu i trapezu; ar, ha", "Площа ромба й трапеції; ар, га",
            "Wzory na pole + duże jednostki pola używane w terenie.",
            "Формули площі + великі одиниці площі для місцевості.",
            "Ar i hektar — pole „w życiu”!",
            "Ар і гектар — площа «в житті»!",
            [
                C("pole rombu", "площа ромба", "P = a·h  lub  (d₁·d₂)/2",
                  "Pole rombu: podstawa × wysokość albo połowa iloczynu przekątnych.",
                  "Площа ромба: основа × висота або половина добутку діагоналей.",
                  rule="P = a·h. Albo P = (d₁·d₂)/2 — gdy znasz przekątne.",
                  rule_ua="P = a·h. Або P = (d₁·d₂)/2 — коли знаєш діагоналі.",
                  media="diagram"),
                C("pole trapezu", "площа трапеції", "P = ((a+b)/2)·h",
                  "Pole trapezu: średnia arytmetyczna podstaw × wysokość.",
                  "Площа трапеції: середнє арифметичне основ × висота.",
                  rule="P = ((a+b)/2)·h. a i b — podstawy równoległe, h — wysokość między nimi.",
                  rule_ua="P = ((a+b)/2)·h. a і b — паралельні основи, h — висота між ними.",
                  media="diagram"),
                C("ar", "ар", "1 ar = 100 m²",
                  "Ar to 100 metrów kwadratowych — wygodny do małych działek.",
                  "Ар — 100 квадратних метрів: зручний для малих ділянок.",
                  rule="1 ar = 10 m × 10 m = 100 m².",
                  rule_ua="1 ар = 10 м × 10 м = 100 м².",
                  media="cover"),
                C("hektar", "гектар", "1 ha = 100 ar = 10 000 m²",
                  "Hektar to 100 arów — jednostka pól, łąk, lasów.",
                  "Гектар — 100 арів: одиниця полів, луків, лісів.",
                  rule="1 ha = 100 m × 100 m = 10 000 m² = 100 arów.",
                  rule_ua="1 га = 100 м × 100 м = 10 000 м² = 100 арів.",
                  media="cover"),
                C("zamiana jednostek pola", "перетворення одиниць площі", "m² ↔ ar ↔ ha",
                  "Przy polu zamieniasz przez 100 (ar) lub 10 000 (ha względem m²).",
                  "При площі перетворюєш через 100 (ар) або 10 000 (га щодо м²).",
                  rule="2,5 ha = 250 ar = 25 000 m². Nie myl z jednostkami długości!",
                  rule_ua="2,5 га = 250 ар = 25 000 м². Не плутай з одиницями довжини!",
                  media="photo"),
            ],
            [
                R(
                    "Pole rombu: a = bok, h = wysokość; albo d₁, d₂ = przekątne.",
                    "Площа ромба: a = сторона, h = висота; або d₁, d₂ = діагоналі.",
                    "P = a·h   lub   P = (d₁·d₂)/2",
                ),
                R(
                    "Pole trapezu: a, b = podstawy równoległe, h = wysokość.",
                    "Площа трапеції: a, b = паралельні основи, h = висота.",
                    "P = ((a + b)/2)·h",
                ),
                R(
                    "Jednostki pola: ar (działka) i hektar (pole).",
                    "Одиниці площі: ар (ділянка) і гектар (поле).",
                    "1 ar = 100 m² · 1 ha = 10 000 m²",
                ),
            ],
        ),

        # ——— 51 ———
        P(
            51, "page51.html", "D", "GEOMETRIA", "ГЕОМЕТРІЯ",
            "Graniastosłup, siatki, pole powierzchni", "Призма, сітки, площа поверхні",
            "Bryły z dwiema równoległymi podstawami + siatka i pole „opakowania”.",
            "Тіла з двома паралельними основами + сітка і площа «обгортки».",
            "Siatka = bryła na płasko!",
            "Сітка = тіло плазом!",
            [
                C("graniastosłup", "призма", "dwie podstawy + ściany boczne",
                  "Graniastosłup ma dwie równoległe, przystające podstawy i prostokątne (zwykle) ściany boczne.",
                  "Призма має дві паралельні рівні основи й (зазвичай) прямокутні бічні грані.",
                  rule="Prostopadłościan i sześcian to szczególne graniastosłupy.",
                  rule_ua="Прямокутний паралелепіпед і куб — особливі призми.",
                  media="cover"),
                C("graniastosłup prosty", "пряма призма", "krawędzie ⊥ podstawie",
                  "W graniastosłupie prostym krawędzie boczne są prostopadłe do podstaw.",
                  "У прямій призмі бічні ребра перпендикулярні до основ.",
                  rule="W szkole najczęściej pracujemy właśnie z graniastosłupami prostymi.",
                  rule_ua="У школі найчастіше працюємо саме з прямими призмами.",
                  media="diagram"),
                C("siatka bryły", "сітка тіла", "rozłożone ściany",
                  "Siatka to rysunek wszystkich ścian bryły rozłożonych na płaszczyźnie (bez nakładania).",
                  "Сітка — малюнок усіх граней тіла, розкладених на площині (без накладання).",
                  rule="Z siatki skleisz model. Policz, czy wszystkie ściany są i pasują krawędziami.",
                  rule_ua="Зі сітки склеїш модель. Порахуй, чи всі грані є і пасують ребрами.",
                  media="diagram"),
                C("pole powierzchni", "площа поверхні", "Pc = suma pól ścian",
                  "Pole powierzchni całkowitej to suma pól wszystkich ścian — ile „papieru” trzeba na opakowanie.",
                  "Площа повної поверхні — сума площ усіх граней: скільки «паперу» треба на обгортку.",
                  rule="Dla prostopadłościanu: Pc = 2(ab+bc+ac). Najpierw trzy pary ścian.",
                  rule_ua="Для прямокутного паралелепіпеда: Pc = 2(ab+bc+ac). Спочатку три пари граней.",
                  media="cover"),
                C("objętość graniastosłupa", "об'єм призми", "V = Pp · H",
                  "Objętość graniastosłupa prostego = pole podstawy × wysokość.",
                  "Об'єм прямої призми = площа основи × висота.",
                  rule="V = Pp · H. Dla prostopadłościanu Pp=a·b, więc V=a·b·c.",
                  rule_ua="V = Pp · H. Для паралелепіпеда Pp=a·b, тож V=a·b·c.",
                  media="photo"),
                C("ostrosłup — przypomnienie", "піраміда — нагадування", "V = (1/3)·Pp·H",
                  "Ostrosłup zbiega się w wierzchołku. Objętość to jedna trzecia graniastosłupa o tej samej podstawie i H.",
                  "Піраміда сходиться у вершині. Об'єм — одна третина призми з тією самою основою і H.",
                  rule="V = (1/3)·Pp·H. Pole powierzchni = Pp + pola trójkątów bocznych.",
                  rule_ua="V = (1/3)·Pp·H. Площа поверхні = Pp + площі бічних трикутників.",
                  media="cover"),
            ],
            [
                R("Graniastosłup: 2 podstawy + ściany boczne.", "Призма: 2 основи + бічні грані."),
                R("Pc = suma pól ścian.", "Pc = сума площ граней."),
                R("V = Pp · H (prosty).", "V = Pp · H (пряма).", "V=Pp·H"),
            ],
        ),
        # ——— 52–60 ———
        P(52, "page52.html", "C", "UŁAMKI", "ДРОБИ",
          "Obliczenia procentowe — wszystkie typy", "Відсоткові обчислення — усі типи",
          "Cztery typowe pytania o procenty — jak w klasach 6–8.",
          "Чотири типові питання про відсотки — як у класах 6–8.",
          "Które pytanie? Wybierz wzór!", "Яке питання? Вибери формулу!",
          [C("p% z liczby", "p% від числа", "20% z 50 = 10",
             "Obliczasz p procent danej liczby b — ile to jest „p ze stu” części b.",
             "Обчислюєш p відсотків даного числа b — скільки це «p зі ста» частин b.",
             rule="a = b · (p/100). Przykład: 20% z 50 = 50·0,20 = 10.",
             rule_ua="a = b · (p/100). Приклад: 20% від 50 = 50·0,20 = 10.", media="diagram"),
           C("jaki procent?", "який відсоток?", "15 z 60 = 25%",
             "Pytanie: jaki procent liczby b stanowi liczba a?",
             "Питання: який відсоток числа b становить число a?",
             rule="p = (a/b)·100%. Przykład: 15/60·100% = 25%.",
             rule_ua="p = (a/b)·100%. Приклад: 15/60·100% = 25%.", media="cover"),
           C("liczba z procentu", "число з відсотка", "30% = 24 → b=80",
             "Znasz p% i ich wartość a — szukasz całej liczby b.",
             "Знаєш p% і їхнє значення a — шукаєш усе число b.",
             rule="b = a·100/p. Przykład: 24 to 30% → b=24·100/30=80.",
             rule_ua="b = a·100/p. Приклад: 24 це 30% → b=24·100/30=80.", media="diagram"),
           C("zwiększenie / zmniejszenie", "збільшення / зменшення", "+20% / −15%",
             "Nowa wartość po wzroście lub spadku o p% — procenty liczymy od liczby wyjściowej.",
             "Нове значення після зростання або спаду на p% — відсотки рахуємо від початкового числа.",
             rule="Wzrost: b·(1+p/100). Spadek: b·(1−p/100).",
             rule_ua="Зростання: b·(1+p/100). Спад: b·(1−p/100).", media="cover"),
           C("podwójna zmiana", "подвійна зміна", "+20% potem −20%",
             "Dwie zmiany procentowe po kolei — wynik ≠ start (procenty od nowej bazy).",
             "Дві відсоткові зміни підряд — результат ≠ старт (відсотки від нової бази).",
             rule="100 → +20% = 120 → −20% = 96. Nie wraca do 100!",
             rule_ua="100 → +20% = 120 → −20% = 96. Не повертається до 100!", media="photo"),
           C("w zadaniach", "у задачах", "cena, test, rabat",
             "W zadaniu najpierw ustal, którego z czterech typów szukasz.",
             "У задачі спочатку з’ясуй, який із чотирьох типів шукаєш.",
             rule="Podkreśl dane: a, b, p. Wybierz wzór. Sprawdź, czy wynik ma sens.",
             rule_ua="Підкресли дані: a, b, p. Вибери формулу. Перевір, чи результат має сенс.", media="photo")],
          [R("p% z b: a=b·p/100.", "p% від b: a=b·p/100."),
           R("Jaki %: p=(a/b)·100%.", "Який %: p=(a/b)·100%."),
           R("Dwie zmiany ≠ powrót do startu.", "Дві зміни ≠ повернення до старту.")]),

        P(53, "page53.html", "B", "DZIAŁANIA", "ДІЇ",
          "Notacja wykładnicza i potęga potęgi", "Показниковий запис і степінь степеня",
          "Duże i małe liczby zapisujemy z 10ᵏ. Potęgi łączymy regułami.",
          "Великі й малі числа пишемо з 10ᵏ. Степені з’єднуємо правилами.",
          "10³ = 1000 — jedynka i zera!", "10³ = 1000 — одиниця і нулі!",
          [C("notacja wykładnicza", "показниковий запис", "a·10ᵏ",
             "Notacja wykładnicza: liczba w postaci a·10ᵏ, gdzie 1 ≤ a < 10, k całkowite.",
             "Показниковий запис: число у вигляді a·10ᵏ, де 1 ≤ a < 10, k ціле.",
             rule="3500 = 3,5·10³. 0,0042 = 4,2·10⁻³.",
             rule_ua="3500 = 3,5·10³. 0,0042 = 4,2·10⁻³.", media="diagram"),
           C("potęga potęgi", "степінь степеня", "(aᵐ)ⁿ = aᵐⁿ",
             "Potęgę podniesioną do potęgi upraszczasz: wykładniki mnożysz.",
             "Степінь, піднесений до степеня, спрощуєш: показники множиш.",
             rule="(2³)⁴ = 2¹². Podstawa ta sama, wykładniki mnożysz.",
             rule_ua="(2³)⁴ = 2¹². Основа та сама, показники множиш.", media="cover"),
           C("różne podstawy, ten sam wykładnik", "різні основи, той самий показник", "aⁿ·bⁿ=(a·b)ⁿ",
             "Gdy wykładnik ten sam, możesz mnożyć (lub dzielić) podstawy.",
             "Коли показник той самий, можна множити (або ділити) основи.",
             rule="2³·5³ = 10³. Oraz aⁿ:bⁿ = (a:b)ⁿ (b≠0).",
             rule_ua="2³·5³ = 10³. Та aⁿ:bⁿ = (a:b)ⁿ (b≠0).", media="diagram"),
           C("przypomnienie: ta sama podstawa", "нагадування: та сама основа", "aᵐ·aⁿ=aᵐ⁺ⁿ",
             "Przy tej samej podstawie: mnożenie → dodaj wykładniki; dzielenie → odejmij.",
             "При тій самій основі: множення → додай показники; ділення → відніми.",
             rule="2⁵·2³=2⁸; 2⁵:2³=2². Nie dodawaj podstaw!",
             rule_ua="2⁵·2³=2⁸; 2⁵:2³=2². Не додавай основи!", media="cover"),
           C("w nauce i technice", "у науці й техніці", "odległości, mikroby",
             "Astronomia i biologia lubią 10ᵏ — wygodniej niż setki zer.",
             "Астрономія й біологія люблять 10ᵏ — зручніше, ніж сотні нулів.",
             rule="Zapisuj w notacji, potem sprawdź „ile zer / jak małe”.",
             rule_ua="Записуй у нотації, потім перевір «скільки нулів / як мале».", media="photo")],
          [R("a·10ᵏ, 1≤a<10.", "a·10ᵏ, 1≤a<10.", "a·10ᵏ"),
           R("(aᵐ)ⁿ = aᵐⁿ.", "(aᵐ)ⁿ = aᵐⁿ."),
           R("aⁿ·bⁿ = (a·b)ⁿ.", "aⁿ·bⁿ = (a·b)ⁿ.")]),

        P(54, "page54.html", "B", "DZIAŁANIA", "ДІЇ",
          "Pierwiastek sześcienny i działania na √", "Кубічний корінь і дії з √",
          "∛ to „odwrócenie” sześcianu. Pierwiastki można upraszczać.",
          "∛ — «обернення» куба. Корені можна спрощувати.",
          "∛8 = 2, bo 2³=8!", "∛8 = 2, бо 2³=8!",
          [C("pierwiastek sześcienny", "кубічний корінь", "∛8 = 2",
             "Pierwiastek sześcienny z a to liczba, która podniesiona do 3. potęgi daje a.",
             "Кубічний корінь з a — число, яке в 3-му степені дає a.",
             rule="∛8=2, bo 2·2·2=8. ∛27=3; ∛64=4; ∛125=5.",
             rule_ua="∛8=2, бо 2·2·2=8. ∛27=3; ∛64=4; ∛125=5.", media="diagram"),
           C("związek z sześcianem", "зв'язок із кубом", "(∛a)³ = a",
             "Pierwiastek sześcienny i potęga trzecia się „odwracają”.",
             "Кубічний корінь і третій степінь «взаємно обернені».",
             rule="(∛a)³ = a oraz ∛(a³)=a.",
             rule_ua="(∛a)³ = a та ∛(a³)=a.", media="cover"),
           C("wyłączanie sprzed pierwiastka", "винесення з-під кореня", "√50 = 5√2",
             "Wyłączasz czynnik będący kwadratem doskonałym spod √.",
             "Виносиш множник, що є повним квадратом, з-під √.",
             rule="√50 = √(25·2) = 5√2. Szukaj największego kwadratu w iloczynie.",
             rule_ua="√50 = √(25·2) = 5√2. Шукай найбільший квадрат у добутку.", media="diagram"),
           C("włączanie pod pierwiastek", "внесення під корінь", "3√2 = √18",
             "Włączasz: podnosisz współczynnik do kwadratu i mnożysz pod √.",
             "Вносиш: підносиш коефіцієнт до квадрата і множиш під √.",
             rule="3√2 = √9·√2 = √18.",
             rule_ua="3√2 = √9·√2 = √18.", media="cover"),
           C("mnożenie i dzielenie pierwiastków", "множення і ділення коренів", "√a·√b=√(a·b)",
             "Pierwiastki tego samego stopnia mnożysz/dzielisz pod jednym znakiem.",
             "Корені того самого степеня множиш/ділиш під одним знаком.",
             rule="√12·√3 = √36 = 6. √50:√2 = √25 = 5.",
             rule_ua="√12·√3 = √36 = 6. √50:√2 = √25 = 5.", media="photo")],
          [R("∛a — liczba, której sześcian = a.", "∛a — число, куб якого = a.", "∛"),
           R("√(a·b)=√a·√b (a,b≥0).", "√(a·b)=√a·√b (a,b≥0)."),
           R("Wyłączaj kwadraty spod √.", "Винось квадрати з-під √.")]),

        P(55, "page55.html", "B", "DZIAŁANIA", "ДІЇ",
          "Mnożenie wyrażeń algebraicznych", "Множення алгебраїчних виразів",
          "Jednomian × suma oraz dwumian × dwumian — jak w klasach 7–8.",
          "Одночлен × сума та двочлен × двочлен — як у класах 7–8.",
          "Każdy z każdym!", "Кожен з кожним!",
          [C("jednomian × suma", "одночлен × сума", "3x(x+2)=3x²+6x",
             "Mnożysz jednomian przez każdy wyraz sumy (rozdzielność).",
             "Множиш одночлен на кожен доданок суми (розподільність).",
             rule="3x·(x+2) = 3x² + 6x.",
             rule_ua="3x·(x+2) = 3x² + 6x.", media="diagram"),
           C("dwumian × dwumian", "двочлен × двочлен", "(x+1)(x+3)",
             "Każdy wyraz pierwszego nawiasu mnożysz przez każdy wyraz drugiego.",
             "Кожен доданок перших дужок множиш на кожен доданок других.",
             rule="(x+1)(x+3)=x²+3x+x+3=x²+4x+3.",
             rule_ua="(x+1)(x+3)=x²+4x+3.", media="diagram"),
           C("metoda kolejności", "метод порядку", "każdy × każdy → redukcja",
             "Po mnożeniu zawsze redukuj wyrazy podobne — nie zostawiaj „rozwlekłej” sumy.",
             "Після множення завжди зведи подібні доданки — не залишай «розтягнутої» суми.",
             rule="Np. 3x+x=4x. Najpierw każdy z każdym, potem redukcja.",
             rule_ua="Напр. 3x+x=4x. Спочатку кожен з кожним, потім зведення.", media="cover"),
           C("znaki minus", "знаки мінус", "(x−2)(x+5)",
             "Uważaj na znaki: minus razy plus daje minus; minus razy minus daje plus.",
             "Увага на знаки: мінус на плюс дає мінус; мінус на мінус дає плюс.",
             rule="(x−2)(x+5)=x²+5x−2x−10=x²+3x−10.",
             rule_ua="(x−2)(x+5)=x²+3x−10.", media="cover"),
           C("sprawdzenie", "перевірка", "podstaw x=2",
             "Sprawdź liczbowo: podstaw konkretne x do nawiasów i do wyniku.",
             "Перевір числово: підстав конкретне x у дужки і в результат.",
             rule="Jeśli dla wybranego x obie strony się zgadzają — OK.",
             rule_ua="Якщо для вибраного x обидва боки збігаються — OK.", media="photo")],
          [R("Jednomian × każdy wyraz sumy.", "Одночлен × кожен доданок."),
           R("Dwumian × dwumian: każdy z każdym.", "Двочлен × двочлен: кожен з кожним."),
           R("Na końcu redukuj podobne.", "Наприкінці зведи подібні.")]),

        P(56, "page56.html", "B", "DZIAŁANIA", "ДІЇ",
          "Podział proporcjonalny", "Пропорційний поділ",
          "Dzielimy całość w danym stosunku — sprawiedliwie według części.",
          "Ділимо ціле в даному відношенні — справедливо за частинами.",
          "Stosunek 2:3 → pięć części!", "Відношення 2:3 → п'ять частин!",
          [C("podział proporcjonalny", "пропорційний поділ", "w stosunku m:n",
             "Całość dzielimy na części proporcjonalne do podanych liczb.",
             "Ціле ділимо на частини, пропорційні даним числам.",
             rule="Suma wag = m+n. Jedna część = całość : suma wag.",
             rule_ua="Сума ваг = m+n. Одна частина = ціле : сума ваг.", media="diagram"),
           C("stosunek", "відношення", "2:3",
             "Stosunek 2:3: na 2 części pierwszego przypadają 3 części drugiego.",
             "Відношення 2:3: на 2 частини першого припадають 3 частини другого.",
             rule="Razem 5 części. Pierwszy 2/5, drugi 3/5 całości.",
             rule_ua="Разом 5 частин. Перший 2/5, другий 3/5 цілого.", media="cover"),
           C("przykład", "приклад", "60 zł w stosunku 1:2",
             "60 zł dla Ali i Basi 1:2 → części 3; jedna=20 → Ala 20, Basia 40.",
             "60 zł для Алі й Басі 1:2 → частин 3; одна=20 → Аля 20, Бася 40.",
             rule="Sprawdź: 20:40=1:2 oraz 20+40=60.",
             rule_ua="Перевір: 20:40=1:2 та 20+40=60.", media="photo"),
           C("trzy osoby", "три особи", "a:b:c",
             "Przy trzech liczbach sumujesz wszystkie wagi.",
             "При трьох числах сумуєш усі ваги.",
             rule="120 w 2:3:1 → 6 części; jedna=20 → 40, 60, 20.",
             rule_ua="120 у 2:3:1 → 6 частин; одна=20 → 40, 60, 20.", media="cover"),
           C("związek z proporcją", "зв'язок із пропорцією", "x:y = m:n",
             "Wynik podziału spełnia proporcję: części mają się do siebie jak wagi m:n.",
             "Результат поділу задовольняє пропорцію: частини відносяться як ваги m:n.",
             rule="Możesz też ułożyć równanie z niewiadomą (np. x/y = m/n).",
             rule_ua="Можна й скласти рівняння з невідомим (напр. x/y = m/n).", media="diagram")],
          [R("Suma części → jedna część → mnoż.", "Сума частин → одна частина → множ."),
           R("Sprawdź: suma = całość i stosunek.", "Перевір: сума = ціле і відношення.")]),

        P(57, "page57.html", "D", "GEOMETRIA", "ГЕОМЕТРІЯ",
          "Twierdzenie Pitagorasa", "Теорема Піфагора",
          "W trójkącie prostokątnym: a² + b² = c² — kluczowe twierdzenie klasy 8.",
          "У прямокутному трикутнику: a² + b² = c² — ключова теорема 8 класу.",
          "Przeciwprostokątna naprzeciw prostego!", "Гіпотенуза навпроти прямого!",
          [C("twierdzenie Pitagorasa", "теорема Піфагора", "a² + b² = c²",
             "Suma kwadratów przyprostokątnych = kwadrat przeciwprostokątnej.",
             "Сума квадратів катетів = квадрат гіпотенузи.",
             rule="c — bok naprzeciw 90° (najdłuższy). a i b — przyprostokątne.",
             rule_ua="c — бік навпроти 90° (найдовший). a і b — катети.", media="diagram"),
           C("przyprostokątne i przeciwprostokątna", "катети і гіпотенуза", "a, b / c",
             "Przyprostokątne tworzą kąt prosty. Przeciwprostokątna leży naprzeciw 90°.",
             "Катети утворюють прямий кут. Гіпотенуза — навпроти 90°.",
             rule="Najpierw wskaż na rysunku, który bok to c!",
             rule_ua="Спочатку вкажи на малюнку, який бік — c!", media="cover"),
           C("obliczanie przeciwprostokątnej", "обчислення гіпотенузи", "c = √(a²+b²)",
             "Znasz a i b: podnieś do kwadratu, dodaj, potem wyciągnij pierwiastek.",
             "Знаєш a і b: піднеси до квадрата, додай, потім витягни корінь.",
             rule="3 i 4 → c=√(9+16)=5. Trójka pitagorejska 3-4-5.",
             rule_ua="3 і 4 → c=√(9+16)=5. Піфагорова трійка 3-4-5.", media="diagram"),
           C("obliczanie przyprostokątnej", "обчислення катета", "a = √(c²−b²)",
             "Znasz c i jedną przyprostokątną — odejmij kwadraty, potem pierwiastek.",
             "Знаєш c і один катет — відніми квадрати, потім корінь.",
             rule="c=13, b=5 → a=√(169−25)=12.",
             rule_ua="c=13, b=5 → a=√(169−25)=12.", media="cover"),
           C("w życiu", "у житті", "drabina, TV, przekątna",
             "Drabina przy ścianie, przekątna ekranu — twierdzenie Pitagorasa w praktyce.",
             "Драбина біля стіни, діагональ екрана — теорема Піфагора на практиці.",
             rule="Szkicuj trójkąt, oznacz a, b, c, podstaw do wzoru.",
             rule_ua="Намалюй трикутник, познач a, b, c, підстав у формулу.", media="photo"),
           C("trójki pitagorejskie", "піфагорові трійки", "3-4-5 · 5-12-13",
             "Naturalne a, b, c spełniające a²+b²=c² — warto znać na pamięć.",
             "Натуральні a, b, c з a²+b²=c² — варто знати напам'ять.",
             rule="3-4-5, 5-12-13, 6-8-10, 7-24-25…",
             rule_ua="3-4-5, 5-12-13, 6-8-10, 7-24-25…", media="diagram")],
          [R("a² + b² = c² (kąt prosty).", "a² + b² = c² (прямий кут).", "a²+b²=c²"),
           R("c naprzeciw 90°.", "c навпроти 90°."),
           R("Zapamiętaj 3-4-5 i 5-12-13.", "Запам'ятай 3-4-5 і 5-12-13.")]),

        P(58, "page58.html", "D", "GEOMETRIA", "ГЕОМЕТРІЯ",
          "Przystawanie trójkątów", "Рівність (конгруентність) трикутників",
          "Kiedy dwa trójkąty są „takie same”? Cechy BBB, BKB, KBK.",
          "Коли два трикутники «такі самі»? Ознаки ССС, СКС, КСК.",
          "BBB, BKB, KBK — cechy!", "ССС, СКС, КСК — ознаки!",
          [C("przystawanie", "конгруентність", "△ABC ≅ △DEF",
             "Trójkąty przystające: równe odpowiadające boki i kąty — ten sam kształt i rozmiar.",
             "Конгруентні трикутники: рівні відповідні сторони й кути — та сама форма і розмір.",
             rule="Zapis ≅. Kolejność wierzchołków = odpowiadanie.",
             rule_ua="Запис ≅. Порядок вершин = відповідність.", media="cover"),
           C("cecha BBB", "ознака ССС", "trzy boki = trzy boki",
             "Trzy boki jednego = trzy boki drugiego → przystawanie.",
             "Три сторони одного = три сторони другого → конгруентність.",
             rule="Wystarczą trzy pary równych boków.",
             rule_ua="Досить трьох пар рівних сторін.", media="diagram"),
           C("cecha BKB", "ознака СКС", "bok — kąt zawarty — bok",
             "Dwa boki i kąt między nimi równe odpowiadającym → przystawanie.",
             "Дві сторони і кут між ними рівні відповідним → конгруентність.",
             rule="Kąt musi być zawarty między tymi bokami!",
             rule_ua="Кут має бути між цими сторонами!", media="diagram"),
           C("cecha KBK", "ознака КСК", "kąt — bok — kąt",
             "Bok i dwa kąty do niego przyległe równe odpowiadającym → też wystarczy (cecha kąt–bok–kąt).",
             "Сторона і два кути, прилеглі до неї, рівні відповідним → теж досить (ознака кут–сторона–кут).",
             rule="Czasem z sumy 180° wyliczasz trzeci kąt i sprowadzasz do cechy KBK.",
             rule_ua="Іноді з суми 180° знаходиш третій кут і зводиш до ознаки КСК.", media="cover"),
           C("po co to?", "навіщо це?", "dowody, zadania",
             "Dzięki przystawaniu przenosisz równości boków i kątów — przydatne w dowodach i zadaniach.",
             "Завдяки конгруентності переносиш рівності сторін і кутів — корисно в доведеннях і задачах.",
             rule="Uzasadnij cechę → wypisz równe elementy → wypisz wniosek.",
             rule_ua="Обґрунтуй ознаку → випиши рівні елементи → зроби висновок.", media="photo")],
          [R("≅ — ten sam kształt i rozmiar.", "≅ — та сама форма і розмір.", "≅"),
           R("BBB, BKB, KBK — cechy.", "ССС, СКС, КСК — ознаки."),
           R("Kolejność wierzchołków ma znaczenie.", "Порядок вершин має значення.")]),

        P(59, "page59.html", "D", "GEOMETRIA", "ГЕОМЕТРІЯ",
          "Środek i długość odcinka", "Середина і довжина відрізка",
          "We współrzędnych: środek = średnia; długość ze wzoru jak Pitagoras.",
          "У координатах: середина = середнє; довжина з формули як Піфагор.",
          "Środek = średnia współrzędnych!", "Середина = середнє координат!",
          [C("środek odcinka", "середина відрізка", "M=((x₁+x₂)/2,(y₁+y₂)/2)",
             "Współrzędne środka = średnie współrzędnych końców.",
             "Координати середини = середні координат кінців.",
             rule="A(2,1), B(6,5) → M(4,3).",
             rule_ua="A(2,1), B(6,5) → M(4,3).", media="diagram"),
           C("długość odcinka", "довжина відрізка", "|AB|=√(Δx²+Δy²)",
             "Długość jak przeciwprostokątna: różnice współrzędnych → pierwiastek.",
             "Довжина як гіпотенуза: різниці координат → корінь.",
             rule="A(1,2), B(4,6): Δx=3, Δy=4 → |AB|=5.",
             rule_ua="A(1,2), B(4,6): Δx=3, Δy=4 → |AB|=5.", media="diagram"),
           C("drugi koniec", "другий кінець", "z A i M znajdź B",
             "Z jednego końca i środka: B = 2M − A (współrzędna po współrzędnej).",
             "З одного кінця і середини: B = 2M − A (координата за координатою).",
             rule="x_B=2x_M−x_A; y_B=2y_M−y_A.",
             rule_ua="x_B=2x_M−x_A; y_B=2y_M−y_A.", media="cover"),
           C("punkty kratowe", "цілочислові точки", "całkowite (x,y)",
             "Punkty kratowe mają całkowite współrzędne — przecięcia kratki.",
             "Цілочислові точки мають цілі координати — перетини клітинок.",
             rule="Na prostej AB szukaj innych punktów kratowych.",
             rule_ua="На прямій AB шукай інші цілочислові точки.", media="cover"),
           C("w zadaniach", "у задачах", "mapa, plan",
             "Plan, gra w kratkę, mapa skarbu — środek i odległość.",
             "План, гра в клітинку, мапа скарбу — середина й відстань.",
             rule="Narysuj osie, zaznacz punkty, potem wzór.",
             rule_ua="Намалюй осі, познач точки, потім формула.", media="photo")],
          [R("Środek: średnie x i y.", "Середина: середні x і y."),
           R("|AB|=√(Δx²+Δy²).", "|AB|=√(Δx²+Δy²).", "√"),
           R("Drugi koniec: 2M − A.", "Другий кінець: 2M − A.")]),

        P(60, "page60.html", "D", "GEOMETRIA", "ГЕОМЕТРІЯ",
          "Symetralna i dwusieczna", "Серединний перпендикуляр і бісектриса",
          "Symetralna dzieli odcinek na pół pod 90°. Dwusieczna dzieli kąt na pół.",
          "Серединний перпендикуляр ділить відрізок навпіл під 90°. Бісектриса ділить кут навпіл.",
          "Na pół — równo!", "Навпіл — порівну!",
          [C("symetralna odcinka", "серединний перпендикуляр", "⊥ w środku",
             "Symetralna odcinka to prosta prostopadła do odcinka, przechodząca przez jego środek.",
             "Серединний перпендикуляр — пряма, перпендикулярна до відрізка і проходить через його середину.",
             rule="Każdy punkt symetralnej jest w równej odległości od obu końców odcinka.",
             rule_ua="Кожна точка серединного перпендикуляра однаково віддалена від обох кінців відрізка.", media="diagram"),
           C("własność symetralnej", "властивість серединного перпендикуляра", "|PA|=|PB|",
             "Punkt P leży na symetralnej odcinka AB wtedy i tylko wtedy, gdy PA = PB.",
             "Точка P лежить на серединному перпендикулярі AB тоді й тільки тоді, коли PA = PB.",
             rule="Równe odległości od A i B ↔ punkt na symetralnej.",
             rule_ua="Рівні відстані від A і B ↔ точка на серединному перпендикулярі.", media="cover"),
           C("dwusieczna kąta", "бісектриса кута", "kąt ÷ 2",
             "Dwusieczna kąta to półprosta, która dzieli kąt na dwa kąty o równej mierze.",
             "Бісектриса кута — півпряма, що ділить кут на два кути з рівною мірою.",
             rule="Z wierzchołka: dwa kąty po α/2.",
             rule_ua="З вершини: два кути по α/2.", media="diagram"),
           C("własność dwusiecznej", "властивість бісектриси", "odległości od ramion",
             "Punkty dwusiecznej są równo odległe od obu ramion kąta.",
             "Точки бісектриси однаково віддалені від обох сторін кута.",
             rule="Środek okręgu wpisanego = przecięcie dwusiecznych.",
             rule_ua="Центр вписаного кола = перетин бісектрис.", media="cover"),
           C("w trójkącie", "у трикутнику", "trzy dwusieczne / symetralne",
             "Trzy dwusieczne spotykają się w jednym punkcie; trzy symetralne — też.",
             "Три бісектриси зустрічаються в одній точці; три серединні перпендикуляри — теж.",
             rule="Okrąg opisany ↔ symetralne. Wpisany ↔ dwusieczne.",
             rule_ua="Описане коло ↔ серединні перпендикуляри. Вписане ↔ бісектриси.", media="photo")],
          [R("Symetralna: ⊥ + środek odcinka.", "Серединний перпендикуляр: ⊥ + середина."),
           R("Dwusieczna: kąt na pół.", "Бісектриса: кут навпіл."),
           R("Równe odległości = własności.", "Рівні відстані = властивості.")]),
    ]
