# -*- coding: utf-8 -*-
"""Nowe strony 62+ : rozdzielenia + braki P1. Starych stron NIE usuwamy."""


def C(pl, ua, visual, def_pl, def_ua, wide="", **kwargs):
    d = {"pl": pl, "ua": ua, "visual": visual, "def_pl": def_pl, "def_ua": def_ua, **kwargs}
    if wide:
        d["wide"] = wide
    return d


def R(pl, ua, formula=""):
    d = {"pl": pl, "ua": ua}
    if formula:
        d["formula"] = formula
    return d


def P(n, file, cat, cat_pl, cat_ua, title_pl, title_ua, intro_pl, intro_ua, tip_pl, tip_ua, cards, remember):
    return {
        "n": n, "file": file, "cat": cat, "cat_pl": cat_pl, "cat_ua": cat_ua,
        "title_pl": title_pl, "title_ua": title_ua,
        "intro_pl": intro_pl, "intro_ua": intro_ua,
        "tip_pl": tip_pl, "tip_ua": tip_ua,
        "cards": cards, "remember": remember,
    }


def build_extra_pages():
    """Numery tymczasowe >61; structure_apply nadaje kolejne n po Fazie A."""
    pages = []

    def add(n, file, cat, cat_pl, cat_ua, title_pl, title_ua, intro_pl, intro_ua, tip_pl, tip_ua, cards, remember, **extra):
        p = P(n, file, cat, cat_pl, cat_ua, title_pl, title_ua, intro_pl, intro_ua, tip_pl, tip_ua, cards, remember)
        p.update(extra)
        p["_is_extra"] = True
        pages.append(p)

    # --- Rozdzielenia brył (stara s.36 zostaje) ---
    add(
        62, "page62.html", "D", "GEOMETRIA", "ГЕОМЕТРІЯ",
        "Walec", "Циліндр",
        "Bryła z dwoma równymi kołami i „płaszczem” dookoła",
        "Тіло з двома рівними кругами і «оболонкою» навколо",
        "Walec jak puszka lub rolka papieru.", "Циліндр як банка чи рулон паперу.",
        [
            C("walec", "циліндр", "puszka, rolka",
              "Bryła z dwiema równoległymi podstawami w kształcie koła i powierzchnią boczną.",
              "Тіло з двома паралельними круглими основами і бічною поверхнею.",
              klasa="klasy 4–8", media="cover"),
            C("podstawa walca", "основа циліндра", "koło",
              "Góra i dół walca to koła o tym samym promieniu.",
              "Верх і низ циліндра — круги з тим самим радіусом.",
              klasa="klasy 4–8", media="diagram"),
            C("wysokość walca", "висота циліндра", "h",
              "Odległość między podstawami (prostopadle).",
              "Відстань між основами (перпендикулярно).",
              klasa="klasy 7–8", media="diagram"),
            C("w życiu", "у житті", "puszka napoju",
              "Puszki, rury, rolki — często mają kształt walca.",
              "Банки, труби, рулони — часто мають форму циліндра.",
              klasa="klasy 4–6", media="photo"),
        ],
        [R("Walec: 2 podstawy-koła + powierzchnia boczna.", "Циліндр: 2 основи-круги + бічна поверхня."),
         R("Walec ≠ stożek ≠ kula.", "Циліндр ≠ конус ≠ куля."),
         R("Wysokość h — odległość między podstawami.", "Висота h — відстань між основами.")],
        asset_n=36,
        mistake_pl="Walec ≠ stożek. Walec ≠ kula. Obie podstawy walca to równe koła.",
        mistake_ua="Циліндр ≠ конус. Циліндр ≠ куля. Обидві основи циліндра — рівні круги.",
    )

    add(
        63, "page63.html", "D", "GEOMETRIA", "ГЕОМЕТРІЯ",
        "Stożek", "Конус",
        "Bryła z okrągłą podstawą zbiegającą się do wierzchołka",
        "Тіло з круглою основою, що сходиться до вершини",
        "Stożek jak rożek lodów albo czapka.", "Конус як ріжок морозива чи шапка.",
        [
            C("stożek", "конус", "rożek, czapka",
              "Bryła z okrągłą podstawą i wierzchołkiem; boczna powierzchnia zbiera się w punkt.",
              "Тіло з круглою основою і вершиною; бічна поверхня сходиться в точку.",
              klasa="klasy 4–8", media="cover"),
            C("podstawa stożka", "основа конуса", "koło",
              "Spód to koło.", "Низ — круг.",
              klasa="klasy 4–8", media="diagram"),
            C("wierzchołek stożka", "вершина конуса", "punkt S",
              "Punkt, w którym zbiegają się tworzące.",
              "Точка, в якій сходяться твірні.",
              klasa="klasy 4–8", media="diagram"),
            C("w życiu", "у житті", "rożek, lejek",
              "Rożek lodów, lejek, czapka party — kształt stożka.",
              "Ріжок морозива, лійка, ковпак — форма конуса.",
              klasa="klasy 4–6", media="photo"),
        ],
        [R("Stożek: koło (podstawa) + wierzchołek.", "Конус: круг (основа) + вершина."),
         R("Stożek ≠ walec (walec ma 2 podstawy).", "Конус ≠ циліндр (циліндр має 2 основи)."),
         R("Stożek ≠ ostrosłup (podstawa stożka to koło).", "Конус ≠ піраміда (основа конуса — круг).")],
        asset_n=36,
        mistake_pl="Stożek ≠ walec. Stożek ≠ ostrosłup. Podstawa stożka to koło (nie wielokąt).",
        mistake_ua="Конус ≠ циліндр. Конус ≠ піраміда. Основа конуса — круг (не многокутник).",
    )

    add(
        64, "page64.html", "D", "GEOMETRIA", "ГЕОМЕТРІЯ",
        "Kula i sfera", "Куля і сфера",
        "Kula to „pełna piłka”; sfera to jej powierzchnia",
        "Куля — «повний м'яч»; сфера — його поверхня",
        "Piłka to kula — środek w środku.", "М'яч — куля: центр усередині.",
        [
            C("kula", "куля", "piłka",
              "Zbiór punktów w przestrzeni w odległości ≤ r od środka (pełna bryła).",
              "Множина точок у просторі на відстані ≤ r від центра (повне тіло).",
              klasa="klasy 4–8", media="cover"),
            C("sfera", "сфера", "powierzchnia piłki",
              "Powierzchnia kuli — punkty dokładnie w odległości r od środka.",
              "Поверхня кулі — точки точно на відстані r від центра.",
              klasa="klasy 7–8", media="diagram"),
            C("środek i promień", "центр і радіус", "O, r",
              "Jak w kole: środek i odległość r.",
              "Як у крузі: центр і відстань r.",
              klasa="klasy 4–8", media="diagram"),
            C("w życiu", "у житті", "piłka, globus",
              "Piłka, pomarańcza, globus — przybliżona kula.",
              "М'яч, апельсин, глобус — наближена куля.",
              klasa="klasy 4–6", media="photo"),
        ],
        [R("Kula = pełna bryła; sfera = powierzchnia.", "Куля = повне тіло; сфера = поверхня."),
         R("Promień r: środek → powierzchnia.", "Радіус r: центр → поверхня."),
         R("Kula ≠ sfera (jak koło ≠ okrąg).", "Куля ≠ сфера (як круг ≠ коло).")],
        asset_n=36,
        mistake_pl="Mówią „sfera” na całą kulę; mylą kula/sfera jak koło/okrąg.",
        mistake_ua="Кажуть «сфера» на всю кулю; плутають куля/сфера як круг/коло.",
    )

    add(
        65, "page65.html", "D", "GEOMETRIA", "ГЕОМЕТРІЯ",
        "Ostrosłup — pole i objętość", "Піраміда — площа й об'єм",
        "Od rozpoznania do wzorów V i P (kl. 7–8)",
        "Від розпізнавання до формул V і P (кл. 7–8)",
        "Podstawa × wysokość / 3 — objętość.", "Основа × висота / 3 — об'єм.",
        [
            C("ostrosłup", "піраміда", "podstawa + wierzchołek",
              "Bryła: wielokątna podstawa i ściany zbiegające się w wierzchołku.",
              "Тіло: многокутна основа і грані, що сходяться у вершині.",
              klasa="klasy 4–8", media="cover"),
            C("ostrosłup prawidłowy", "правильна піраміда", "podstawa foremna",
              "Podstawa to wielokąt foremny; boczne krawędzie równe.",
              "Основа — правильний многокутник; бічні ребра рівні.",
              klasa="klasy 7–8", media="diagram"),
            C("objętość ostrosłupa", "об'єм піраміди", "V = (1/3)·P_podst·H",
              "Jedna trzecia iloczynu pola podstawy i wysokości.",
              "Одна третя добутку площі основи і висоти.",
              klasa="klasy 7–8", media="diagram",
              rule="V = ⅓ · Pole podstawy · wysokość",
              rule_ua="V = ⅓ · Площа основи · висота"),
            C("pole powierzchni", "площа поверхні", "P = P_podst + P_boczne",
              "Suma pola podstawy i pól ścian bocznych.",
              "Сума площі основи і площ бічних граней.",
              klasa="klasy 7–8", media="diagram"),
            C("wysokość ostrosłupa", "висота піраміди", "H",
              "Prostopadła z wierzchołka do płaszczyzny podstawy.",
              "Перпендикуляр із вершини до площини основи.",
              klasa="klasy 7–8", media="diagram"),
        ],
        [R("V = ⅓ · P_podstawy · H", "V = ⅓ · P_основи · H"),
         R("P = P_podstawy + P_boczne", "P = P_основи + P_бічні"),
         R("H — prostopadła z wierzchołka do płaszczyzny podstawy.", "H — перпендикуляр із вершини до площини основи."),
         R("Ostrosłup ≠ graniastosłup.", "Піраміда ≠ призма.")],
        asset_n=51,
        mistake_pl="Zapominają o ⅓ w objętości; mylą wysokość z krawędzią boczną; mylą z graniastosłupem.",
        mistake_ua="Забувають про ⅓ в об'ємі; плутають висоту з бічним ребром; плутають із призмою.",
    )

    # --- Braki P1 ---
    add(
        66, "page66.html", "B", "DZIAŁANIA", "ДІЇ",
        "Nierówności", "Нерівності",
        "Porównanie z niewiadomą: < > ≤ ≥",
        "Порівняння з невідомим: < > ≤ ≥",
        "Równanie: = . Nierówność: znak porównania.", "Рівняння: = . Нерівність: знак порівняння.",
        [
            C("nierówność", "нерівність", "x > 3",
              "Zapis porównania liczb lub wyrażeń ze znakiem < > ≤ ≥.",
              "Запис порівняння чисел або виразів зі знаком < > ≤ ≥.",
              klasa="klasy 7–8", media="cover"),
            C("rozwiązanie nierówności", "розв'язок нерівності", "x ≥ 2",
              "Zbiór wartości niewiadomej, dla których nierówność jest prawdziwa.",
              "Множина значень невідомого, для яких нерівність істинна.",
              klasa="klasy 7–8", media="diagram"),
            C("znaki", "знаки", "< > ≤ ≥",
              "Mniejsze, większe, nie większe, nie mniejsze.",
              "Менше, більше, не більше, не менше.",
              klasa="klasy 4–8", media="diagram"),
            C("na osi", "на осі", "promień / odcinek",
              "Rozwiązanie często rysujemy na osi liczbowej.",
              "Розв'язок часто малюємо на числовій прямій.",
              klasa="klasy 7–8", media="diagram"),
            C("a równanie?", "а рівняння?", "= vs <",
              "Równanie szuka równości; nierówność — całego zakresu.",
              "Рівняння шукає рівність; нерівність — цілий діапазон.",
              klasa="klasy 7–8", media="cover"),
        ],
        [R("Nierówność ≠ równanie (=).", "Нерівність ≠ рівняння (=)."),
         R("Znaki: < > ≤ ≥", "Знаки: < > ≤ ≥"),
         R("Rozwiązanie = zbiór wartości (często na osi).", "Розв'язок = множина значень (часто на осі)."),
         R("Przy mnożeniu/dzieleniu przez liczbę ujemną: odwróć znak nierówności.",
           "При множенні/діленні на від'ємне: зміни знак нерівності.")],
        mistake_pl="Traktują nierówność jak równanie (jedna wartość); zapominają odwrócić znak przy ×/(−).",
        mistake_ua="Ставляться до нерівності як до рівняння (одне значення); забувають змінити знак при ×/(−).",
    )

    add(
        67, "page67.html", "B", "DZIAŁANIA", "ДІЇ",
        "Przekształcanie wzorów", "Перетворення формул",
        "Wylicz niewiadomą z gotowego wzoru (v, s, t, pole…)",
        "Вирази невідоме з готової формули (v, s, t, площа…)",
        "Chcesz t? Przenieś i podziel — jak w równaniu.", "Хочеш t? Перенеси й поділи — як у рівнянні.",
        [
            C("przekształcanie wzoru", "перетворення формули", "s = v·t → t = s/v",
              "Wyizolowanie wybranej wielkości po jednej stronie równości.",
              "Виокремлення потрібної величини з одного боку рівності.",
              klasa="klasy 7–8", media="cover"),
            C("przykład: prędkość", "приклад: швидкість", "v = s/t",
              "Z s = v·t dostajesz v = s/t oraz t = s/v.",
              "З s = v·t маєш v = s/t і t = s/v.",
              klasa="klasy 7–8", media="diagram"),
            C("przykład: pole", "приклад: площа", "P = a·b → a = P/b",
              "To samo na wzorach geometrycznych.",
              "Те саме на геометричних формулах.",
              klasa="klasy 7–8", media="diagram"),
            C("krok po kroku", "крок за кроком", "÷ × + −",
              "Wykonuj odwrotne działania po obu stronach.",
              "Роби обернені дії з обох боків.",
              klasa="klasy 7–8", media="cover"),
        ],
        [R("s = v·t → v = s/t , t = s/v", "s = v·t → v = s/t , t = s/v"),
         R("P = a·b → a = P/b", "P = a·b → a = P/b"),
         R("Te same działania po obu stronach równości.", "Ті самі дії з обох боків рівності."),
         R("Jednostki muszą się zgadzać.", "Одиниці мають збігатися.")],
        asset_n=27,
        mistake_pl="Przenoszą litery bez działań po obu stronach; dzielą tylko jedną stronę; gubią jednostki.",
        mistake_ua="Переносять літери без дій з обох боків; ділять лише один бік; гублять одиниці.",
    )

    add(
        68, "page68.html", "D", "GEOMETRIA", "ГЕОМЕТРІЯ",
        "Wielokąt foremny", "Правильний многокутник",
        "Wszystkie boki równe i wszystkie kąty równe",
        "Усі сторони рівні і всі кути рівні",
        "Kwadrat to foremny 4-kąt.", "Квадрат — правильний 4-кутник.",
        [
            C("wielokąt foremny", "правильний многокутник", "równoboczny + równokątny",
              "Wielokąt o równych bokach i równych kątach wewnętrznych.",
              "Многокутник із рівними сторонами і рівними внутрішніми кутами.",
              klasa="klasy 7–8", media="cover"),
            C("przykłady", "приклади", "trójkąt równoboczny, kwadrat",
              "Foremny 3-kąt = równoboczny; foremny 4-kąt = kwadrat.",
              "Правильний 3-кутник = рівносторонній; 4-кутник = квадрат.",
              klasa="klasy 7–8", media="diagram"),
            C("środek", "центр", "okrąg opisany / wpisany",
              "Przy foremnych często pomaga okrąg opisany lub wpisany.",
              "У правильних часто допомагає описане або вписане коло.",
              klasa="klasy 7–8", media="diagram"),
        ],
        [R("Foremny = równe boki + równe kąty.", "Правильний = рівні сторони + рівні кути."),
         R("Foremny 3-kąt = trójkąt równoboczny.", "Правильний 3-кутник = рівносторонній трикутник."),
         R("Foremny 4-kąt = kwadrat.", "Правильний 4-кутник = квадрат."),
         R("Romb foremny tylko gdy kąty proste (= kwadrat).", "Ромб правильний лише при прямих кутах (= квадрат).")],
        asset_n=29,
        mistake_pl="Myślą, że każdy romb / każdy prostokąt jest foremny.",
        mistake_ua="Думають, що кожен ромб / кожен прямокутник правильний.",
    )

    add(
        69, "page69.html", "D", "GEOMETRIA", "ГЕОМЕТРІЯ",
        "Podobieństwo figur", "Подібність фігур",
        "Ten sam kształt, inny rozmiar — skala k",
        "Та сама форма, інший розмір — масштаб k",
        "Przystawanie = to samo + ten sam rozmiar. Podobieństwo = kształt.",
        "Конгруентність = те саме + розмір. Подібність = форма.",
        [
            C("podobieństwo", "подібність", "Δ ~ Δ",
              "Figury mają ten sam kształt; odpowiadające kąty równe, boki proporcjonalne.",
              "Фігури мають ту саму форму; відповідні кути рівні, сторони пропорційні.",
              klasa="klasy 7–8", media="cover"),
            C("skala podobieństwa", "коефіцієнт подібності", "k",
              "Stosunek długości odpowiadających boków.",
              "Відношення довжин відповідних сторін.",
              klasa="klasy 7–8", media="diagram"),
            C("a przystawanie?", "а конгруентність?", "≅ vs ~",
              "Przystające = podobne ze skalą k = 1.",
              "Конгруентні = подібні з k = 1.",
              klasa="klasy 7–8", media="diagram"),
            C("w życiu", "у житті", "mapa, model",
              "Mapa, model samochodu, powiększenie zdjęcia.",
              "Карта, модель авто, збільшення фото.",
              klasa="klasy 7–8", media="photo"),
        ],
        [R("Podobne: kąty równe, boki proporcjonalne (·k).", "Подібні: кути рівні, сторони пропорційні (·k)."),
         R("k = skala podobieństwa.", "k = коефіцієнт подібності."),
         R("k = 1 → figury przystające.", "k = 1 → конгруентні фігури."),
         R("~ ≠ ≅", "~ ≠ ≅")],
        asset_n=58,
        mistake_pl="Mylą podobieństwo z przystawaniem; biorą k jako różnicę boków zamiast stosunku.",
        mistake_ua="Плутають подібність із конгруентністю; беруть k як різницю сторін замість відношення.",
    )

    add(
        70, "page70.html", "D", "GEOMETRIA", "ГЕОМЕТРІЯ",
        "Okręgi wpisane i opisane", "Вписані й описані кола",
        "Okrąg w trójkącie / wokół trójkąta",
        "Коло в трикутнику / навколо трикутника",
        "Wpisany dotyka boków; opisany przechodzi przez wierzchołki.",
        "Вписане торкається сторін; описане проходить через вершини.",
        [
            C("okrąg wpisany", "вписане коло", "środek = przecięcie dwusiecznych",
              "Okrąg wewnątrz wielokąta, styczny do wszystkich boków.",
              "Коло всередині многокутника, дотичне до всіх сторін.",
              klasa="klasy 7–8", media="cover"),
            C("okrąg opisany", "описане коло", "środek = przecięcie symetralnych",
              "Okrąg przechodzący przez wszystkie wierzchołki wielokąta.",
              "Коло, що проходить через усі вершини многокутника.",
              klasa="klasy 7–8", media="diagram"),
            C("w trójkącie", "у трикутнику", "zawsze oba",
              "W każdym trójkącie istnieje okrąg wpisany i opisany.",
              "У кожному трикутнику є вписане й описане коло.",
              klasa="klasy 7–8", media="diagram"),
        ],
        [R("Okrąg wpisany: styczny do boków (środek = dwusieczne).", "Вписане коло: дотичне до сторін (центр = бісектриси)."),
         R("Okrąg opisany: przez wierzchołki (środek = symetralne).", "Описане коло: через вершини (центр = серединні перпендикуляри)."),
         R("W każdym trójkącie: oba okręgi istnieją.", "У кожному трикутнику: обидва кола існують."),
         R("Wpisany ≠ opisany.", "Вписане ≠ описане.")],
        asset_n=30,
        mistake_pl="Mylą wpisany z opisanym; mylą środek (dwusieczne vs symetralne).",
        mistake_ua="Плутають вписане з описаним; плутають центр (бісектриси vs серединні перпендикуляри).",
    )

    add(
        71, "page71.html", "D", "GEOMETRIA", "ГЕОМЕТРІЯ",
        "Przekształcenia geometryczne", "Геометричні перетворення",
        "Przesunięcie, obrót — obok symetrii",
        "Паралельне перенесення, поворот — поряд із симетрією",
        "Figura „jedzie”, „kręci się” lub odbija — kształt zostaje.",
        "Фігура «їде», «крутиться» чи відбивається — форма лишається.",
        [
            C("przesunięcie", "паралельне перенесення", "w bok o tyle samo",
              "Figurę przesuwamy w jednym kierunku o tę samą odległość — kształt i rozmiar zostają.",
              "Фігуру зсуваємо в одному напрямі на ту саму відстань — форма й розмір лишаються.",
              klasa="klasy 7–8", media="cover"),
            C("obrót", "поворот", "wokół punktu",
              "Figurę obracamy wokół punktu o dany kąt — jak wskazówka zegara.",
              "Фігуру обертаємо навколо точки на даний кут — як стрілка годинника.",
              klasa="klasy 7–8", media="diagram"),
            C("a symetria?", "а симетрія?", "odbicia",
              "Odbicie w osi lub względem punktu też zmienia położenie figury (osobna strona: Symetria).",
              "Відбиття в осі або відносно точки теж змінює положення фігури (окрема сторінка: Симетрія).",
              klasa="klasy 7–8", media="diagram"),
        ],
        [R("Przesunięcie: w bok o tę samą odległość.", "Перенесення: убік на ту саму відстань."),
         R("Obrót: punkt (środek) + kąt.", "Поворот: точка (центр) + кут."),
         R("Symetria osiowa / środkowa — też przekształcenia.", "Осьова / центральна симетрія — теж перетворення."),
         R("Przesunięcie ≠ obrót ≠ odbicie.", "Перенесення ≠ поворот ≠ відбиття.")],
        asset_n=37,
        mistake_pl="Mylą przesunięcie z obrotem; zapominają podać środek i kąt przy obrocie.",
        mistake_ua="Плутають перенесення з поворотом; забувають вказати центр і кут при повороті.",
    )

    add(
        72, "page72.html", "A", "LICZBY", "ЧИСЛА",
        "Liczby wymierne i niewymierne", "Раціональні та ірраціональні числа",
        "Ułamki, całkowite i (krótko) liczby niewymierne",
        "Дроби, цілі і (коротко) ірраціональні числа",
        "Wymierna = a/b. Niewymierna — nie da się tak zapisać (√2, π).",
        "Раціональне = a/b. Ірраціональне — так записати не можна (√2, π).",
        [
            C("liczba wymierna", "раціональне число", "a/b",
              "Liczba, którą da się zapisać jako iloraz dwóch liczb całkowitych (mianownik ≠ 0).",
              "Число, яке можна записати як частку двох цілих (знаменник ≠ 0).",
              klasa="klasy 7–8", media="cover"),
            C("przykłady wymiernych", "приклади раціональних", "−3, 0, 2/5, 1,25",
              "Całkowite, ułamki zwykłe i skończone dziesiętne są wymierne.",
              "Цілі, звичайні дроби й скінченні десяткові — раціональні.",
              klasa="klasy 7–8", media="diagram"),
            C("liczba niewymierna", "ірраціональне число", "√2, π",
              "Liczba, której nie da się zapisać jako a/b (a, b całkowite, b ≠ 0). W SP: znasz przykłady √2 i π.",
              "Число, яке не можна записати як a/b (a, b цілі, b ≠ 0). У початковій/середній школі: приклади √2 і π.",
              klasa="klasy 7–8", media="cover"),
            C("na osi", "на осі", "wymierne i niewymierne",
              "Na osi są wymierne i niewymierne; między dwiema wymiernymi jest inna wymierna.",
              "На осі є раціональні й ірраціональні; між двома раціональними є інше раціональне.",
              klasa="klasy 7–8", media="diagram"),
        ],
        [R("Liczby wymierne tworzą zbiór ℚ.", "Раціональні числа утворюють множину ℚ.",
            "ℚ = { a/b : a,b ∈ ℤ, b≠0 }"),
         R("ℤ ⊂ ℚ (całkowite są wymierne).", "ℤ ⊂ ℚ (цілі є раціональними)."),
         R("√2 i π — przykłady niewymiernych (SP).", "√2 і π — приклади ірраціональних (ШП)."),
         R("Wymierna = a/b (b ≠ 0).", "Раціональне = a/b (b ≠ 0).")],
        asset_n=3,
        mistake_pl="Myślą, że tylko ułamki zwykłe są wymierne; mylą niewymierne z „bardzo dużymi”.",
        mistake_ua="Думають, що лише звичайні дроби раціональні; плутають ірраціональні з «дуже великими».",
    )

    add(
        73, "page73.html", "D", "GEOMETRIA", "ГЕОМЕТРІЯ",
        "Środkowa w trójkącie", "Медіана в трикутнику",
        "Odcinek ze środka boku do przeciwległego wierzchołka",
        "Відрізок із середини сторони до протилежної вершини",
        "Środkowa ≠ wysokość ≠ dwusieczna (czasem się pokrywają).",
        "Медіана ≠ висота ≠ бісектриса (інколи збігаються).",
        [
            C("środkowa", "медіана", "środek boku → wierzchołek",
              "Odcinek łączący wierzchołek ze środkiem przeciwległego boku.",
              "Відрізок, що з'єднує вершину із серединою протилежної сторони.",
              klasa="klasy 6–8", media="cover"),
            C("trzy środkowe", "три медіани", "środek ciężkości",
              "Przecinają się w jednym punkcie (środek ciężkości).",
              "Перетинаються в одній точці (центр мас).",
              klasa="klasy 7–8", media="diagram"),
            C("a wysokość / dwusieczna?", "а висота / бісектриса?", "różne linie",
              "Wysokość: ⊥ do boku. Dwusieczna: dzieli kąt na pół. Środkowa: do środka boku.",
              "Висота: ⊥ до сторони. Бісектриса: ділить кут навпіл. Медіана: до середини сторони.",
              klasa="klasy 6–8", media="diagram"),
        ],
        [R("Środkowa: wierzchołek → środek przeciwległego boku.", "Медіана: вершина → середина протилежної сторони."),
         R("Środkowa ≠ wysokość ≠ dwusieczna (na ogół).", "Медіана ≠ висота ≠ бісектриса (зазвичай)."),
         R("W trójkącie równobocznym: środkowa = wysokość = dwusieczna.",
           "У рівносторонньому: медіана = висота = бісектриса."),
         R("Trzy środkowe przecinają się w jednym punkcie.", "Три медіани перетинаються в одній точці.")],
        asset_n=60,
        mistake_pl="Mylą środkową z wysokością lub dwusieczną kąta.",
        mistake_ua="Плутають медіану з висотою або бісектрисою кута.",
    )

    add(
        74, "page74.html", "F", "DANE", "ДАНІ",
        "Prawdopodobieństwo", "Ймовірність",
        "Szansa zdarzenia w doświadczeniu losowym",
        "Шанс події у випадковому досліді",
        "P = korzystne / wszystkie (gdy równie możliwe).",
        "P = сприятливі / усі (якщо рівноможливі).",
        [
            C("prawdopodobieństwo", "ймовірність", "0 ≤ P ≤ 1",
              "Liczba mówiąca, jak bardzo spodziewamy się zdarzenia.",
              "Число, що каже, наскільки очікуємо подію.",
              klasa="klasy 6–8", media="cover"),
            C("doświadczenie losowe", "випадковий дослід", "moneta, kostka",
              "Eksperyment, którego wyniku nie da się pewnie przewidzieć.",
              "Експеримент, результат якого не можна впевнено передбачити.",
              klasa="klasy 7–8", media="diagram"),
            C("zdarzenie", "подія", "wypadnie 6",
              "Wynik lub zbiór wyników doświadczenia.",
              "Результат або множина результатів досліду.",
              klasa="klasy 7–8", media="diagram"),
            C("wzór klasyczny", "класична формула", "P = k/n",
              "Gdy wyniki są równie możliwe: korzystne / wszystkie.",
              "Коли результати рівноможливі: сприятливі / усі.",
              klasa="klasy 7–8", media="cover",
              rule="P = liczba wyników korzystnych / liczba wszystkich wyników",
              rule_ua="P = кількість сприятливих / кількість усіх"),
        ],
        [R("0 ≤ P ≤ 1", "0 ≤ P ≤ 1"),
         R("P = korzystne / wszystkie (wyniki równie możliwe).", "P = сприятливі / усі (рівноможливі результати)."),
         R("P = 0 — niemożliwe; P = 1 — pewne.", "P = 0 — неможливе; P = 1 — певне."),
         R("Kostka: P(6) = 1/6.", "Кубик: P(6) = 1/6.")],
        asset_n=41,
        mistake_pl="Liczą P bez założenia równej szansy; mylą z kombinatoryką (samo zliczanie).",
        mistake_ua="Рахують P без рівної ймовірності; плутають із комбінаторикою (лише підрахунок).",
    )

    add(
        75, "page75.html", "E", "MIARY", "ВЕЛИЧИНИ",
        "Skala mapy", "Масштаб карти",
        "Jak odczytać odległość z mapy (1:… )",
        "Як прочитати відстань із карти (1:… )",
        "1:100 000 — 1 cm na mapie = 100 000 cm w terenie.",
        "1:100 000 — 1 см на карті = 100 000 см на місцевості.",
        [
            C("skala mapy", "масштаб карти", "1 : n",
              "Stosunek długości na mapie do długości w rzeczywistości.",
              "Відношення довжини на карті до довжини в дійсності.",
              klasa="klasy 5–7", media="cover"),
            C("obliczanie odległości", "обчислення відстані", "× n",
              "Zmierz na mapie i pomnóż przez mianownik skali (z jednostkami!).",
              "Виміряй на карті й помнож на знаменник масштабу (з одиницями!).",
              klasa="klasy 5–7", media="diagram"),
            C("przykład", "приклад", "1:50 000",
              "2 cm na mapie → 2·50 000 cm = 1 km w terenie.",
              "2 см на карті → 2·50 000 см = 1 км на місцевості.",
              klasa="klasy 5–7", media="cover"),
        ],
        [R("Skala 1 : n — 1 cm na mapie = n cm w terenie.", "Масштаб 1 : n — 1 см на карті = n см на місцевості."),
         R("Odległość w terenie = odległość na mapie × n.", "Відстань на місцевості = відстань на карті × n."),
         R("Przelicz jednostki (cm → m → km).", "Перетвори одиниці (см → м → км)."),
         R("Skala mapy ≠ prędkość.", "Масштаб карти ≠ швидкість.")],
        asset_n=27,
        mistake_pl="Dzielą zamiast mnożyć przez n; gubią przeliczenie cm→km.",
        mistake_ua="Ділять замість множити на n; гублять перетворення см→км.",
    )

    return pages
